// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * PermissionGrantDto
 * <p>
 * List of permission grants
 *
 */
@JsonTypeName("PermissionGrantDto")
@JsonPropertyOrder({
    "applicationAccess",
    "groupCustomFields",
    "groups",
    "permissionKeys",
    "projectRoles",
    "specialGrants",
    "userCustomFields",
    "users"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PermissionGrantDto {

    @JsonProperty("applicationAccess")
    protected List<String> applicationAccess;

    @JsonProperty("groupCustomFields")
    protected List<ProjectCreateResourceIDEntifier> groupCustomFields;

    @JsonProperty("groups")
    protected List<ProjectCreateResourceIDEntifier> groups;

    @JsonProperty("permissionKeys")
    protected List<String> permissionKeys;

    @JsonProperty("projectRoles")
    protected List<ProjectCreateResourceIDEntifier> projectRoles;

    @JsonProperty("specialGrants")
    protected List<String> specialGrants;

    @JsonProperty("userCustomFields")
    protected List<ProjectCreateResourceIDEntifier> userCustomFields;

    @JsonProperty("users")
    protected List<ProjectCreateResourceIDEntifier> users;

    /**
     * Constructs a validated instance of {@link PermissionGrantDto}.
     *
     * @param spec the specification to process
     */
    public PermissionGrantDto(Consumer<PermissionGrantDto> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected PermissionGrantDto() {
    }

    /**
     * Constructs a validated instance of {@link PermissionGrantDto}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PermissionGrantDto(Consumer)} instead.
     * @param applicationAccess applicationAccess
     * @param groupCustomFields groupCustomFields
     * @param groups groups
     * @param permissionKeys permissionKeys
     * @param projectRoles projectRoles
     * @param specialGrants specialGrants
     * @param userCustomFields userCustomFields
     * @param users users
     */
    @ApiStatus.Internal
    public PermissionGrantDto(List<String> applicationAccess, List<ProjectCreateResourceIDEntifier> groupCustomFields, List<ProjectCreateResourceIDEntifier> groups, List<String> permissionKeys, List<ProjectCreateResourceIDEntifier> projectRoles, List<String> specialGrants, List<ProjectCreateResourceIDEntifier> userCustomFields, List<ProjectCreateResourceIDEntifier> users) {
        this.applicationAccess = applicationAccess;
        this.groupCustomFields = groupCustomFields;
        this.groups = groups;
        this.permissionKeys = permissionKeys;
        this.projectRoles = projectRoles;
        this.specialGrants = specialGrants;
        this.userCustomFields = userCustomFields;
        this.users = users;
    }


    /**
     * Fluent getter for applicationAccess.
     *
     * @return applicationAccess
     */
    public List<String> applicationAccess() {
        return this.applicationAccess;
    }

    /**
     * Fluent setter for applicationAccess.
     *
     * @param applicationAccess applicationAccess
     * @return this
     */
    public PermissionGrantDto applicationAccess(List<String> applicationAccess) {
        this.applicationAccess = applicationAccess;
        return this;
    }

    /**
     * Gets the value of applicationAccess.
     *
     * @return applicationAccess
     */
    @JsonProperty("applicationAccess")
    public List<String> getApplicationAccess() {
        return this.applicationAccess;
    }

    /**
     * Sets the value of applicationAccess.
     *
     * @param applicationAccess applicationAccess
     */
    public void setApplicationAccess(List<String> applicationAccess) {
        this.applicationAccess = applicationAccess;
    }
    /**
     * Fluent getter for groupCustomFields.
     *
     * @return groupCustomFields
     */
    public List<ProjectCreateResourceIDEntifier> groupCustomFields() {
        return this.groupCustomFields;
    }

    /**
     * Fluent setter for groupCustomFields.
     *
     * @param groupCustomFields groupCustomFields
     * @return this
     */
    public PermissionGrantDto groupCustomFields(List<ProjectCreateResourceIDEntifier> groupCustomFields) {
        this.groupCustomFields = groupCustomFields;
        return this;
    }

    /**
     * Gets the value of groupCustomFields.
     *
     * @return groupCustomFields
     */
    @JsonProperty("groupCustomFields")
    public List<ProjectCreateResourceIDEntifier> getGroupCustomFields() {
        return this.groupCustomFields;
    }

    /**
     * Sets the value of groupCustomFields.
     *
     * @param groupCustomFields groupCustomFields
     */
    public void setGroupCustomFields(List<ProjectCreateResourceIDEntifier> groupCustomFields) {
        this.groupCustomFields = groupCustomFields;
    }
    /**
     * Fluent getter for groups.
     *
     * @return groups
     */
    public List<ProjectCreateResourceIDEntifier> groups() {
        return this.groups;
    }

    /**
     * Fluent setter for groups.
     *
     * @param groups groups
     * @return this
     */
    public PermissionGrantDto groups(List<ProjectCreateResourceIDEntifier> groups) {
        this.groups = groups;
        return this;
    }

    /**
     * Gets the value of groups.
     *
     * @return groups
     */
    @JsonProperty("groups")
    public List<ProjectCreateResourceIDEntifier> getGroups() {
        return this.groups;
    }

    /**
     * Sets the value of groups.
     *
     * @param groups groups
     */
    public void setGroups(List<ProjectCreateResourceIDEntifier> groups) {
        this.groups = groups;
    }
    /**
     * Fluent getter for permissionKeys.
     *
     * @return permissionKeys
     */
    public List<String> permissionKeys() {
        return this.permissionKeys;
    }

    /**
     * Fluent setter for permissionKeys.
     *
     * @param permissionKeys permissionKeys
     * @return this
     */
    public PermissionGrantDto permissionKeys(List<String> permissionKeys) {
        this.permissionKeys = permissionKeys;
        return this;
    }

    /**
     * Gets the value of permissionKeys.
     *
     * @return permissionKeys
     */
    @JsonProperty("permissionKeys")
    public List<String> getPermissionKeys() {
        return this.permissionKeys;
    }

    /**
     * Sets the value of permissionKeys.
     *
     * @param permissionKeys permissionKeys
     */
    public void setPermissionKeys(List<String> permissionKeys) {
        this.permissionKeys = permissionKeys;
    }
    /**
     * Fluent getter for projectRoles.
     *
     * @return projectRoles
     */
    public List<ProjectCreateResourceIDEntifier> projectRoles() {
        return this.projectRoles;
    }

    /**
     * Fluent setter for projectRoles.
     *
     * @param projectRoles projectRoles
     * @return this
     */
    public PermissionGrantDto projectRoles(List<ProjectCreateResourceIDEntifier> projectRoles) {
        this.projectRoles = projectRoles;
        return this;
    }

    /**
     * Gets the value of projectRoles.
     *
     * @return projectRoles
     */
    @JsonProperty("projectRoles")
    public List<ProjectCreateResourceIDEntifier> getProjectRoles() {
        return this.projectRoles;
    }

    /**
     * Sets the value of projectRoles.
     *
     * @param projectRoles projectRoles
     */
    public void setProjectRoles(List<ProjectCreateResourceIDEntifier> projectRoles) {
        this.projectRoles = projectRoles;
    }
    /**
     * Fluent getter for specialGrants.
     *
     * @return specialGrants
     */
    public List<String> specialGrants() {
        return this.specialGrants;
    }

    /**
     * Fluent setter for specialGrants.
     *
     * @param specialGrants specialGrants
     * @return this
     */
    public PermissionGrantDto specialGrants(List<String> specialGrants) {
        this.specialGrants = specialGrants;
        return this;
    }

    /**
     * Gets the value of specialGrants.
     *
     * @return specialGrants
     */
    @JsonProperty("specialGrants")
    public List<String> getSpecialGrants() {
        return this.specialGrants;
    }

    /**
     * Sets the value of specialGrants.
     *
     * @param specialGrants specialGrants
     */
    public void setSpecialGrants(List<String> specialGrants) {
        this.specialGrants = specialGrants;
    }
    /**
     * Fluent getter for userCustomFields.
     *
     * @return userCustomFields
     */
    public List<ProjectCreateResourceIDEntifier> userCustomFields() {
        return this.userCustomFields;
    }

    /**
     * Fluent setter for userCustomFields.
     *
     * @param userCustomFields userCustomFields
     * @return this
     */
    public PermissionGrantDto userCustomFields(List<ProjectCreateResourceIDEntifier> userCustomFields) {
        this.userCustomFields = userCustomFields;
        return this;
    }

    /**
     * Gets the value of userCustomFields.
     *
     * @return userCustomFields
     */
    @JsonProperty("userCustomFields")
    public List<ProjectCreateResourceIDEntifier> getUserCustomFields() {
        return this.userCustomFields;
    }

    /**
     * Sets the value of userCustomFields.
     *
     * @param userCustomFields userCustomFields
     */
    public void setUserCustomFields(List<ProjectCreateResourceIDEntifier> userCustomFields) {
        this.userCustomFields = userCustomFields;
    }
    /**
     * Fluent getter for users.
     *
     * @return users
     */
    public List<ProjectCreateResourceIDEntifier> users() {
        return this.users;
    }

    /**
     * Fluent setter for users.
     *
     * @param users users
     * @return this
     */
    public PermissionGrantDto users(List<ProjectCreateResourceIDEntifier> users) {
        this.users = users;
        return this;
    }

    /**
     * Gets the value of users.
     *
     * @return users
     */
    @JsonProperty("users")
    public List<ProjectCreateResourceIDEntifier> getUsers() {
        return this.users;
    }

    /**
     * Sets the value of users.
     *
     * @param users users
     */
    public void setUsers(List<ProjectCreateResourceIDEntifier> users) {
        this.users = users;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PermissionGrantDto that = (PermissionGrantDto) o;
        return
            Objects.equals(this.applicationAccess, that.applicationAccess) &&
            Objects.equals(this.groupCustomFields, that.groupCustomFields) &&
            Objects.equals(this.groups, that.groups) &&
            Objects.equals(this.permissionKeys, that.permissionKeys) &&
            Objects.equals(this.projectRoles, that.projectRoles) &&
            Objects.equals(this.specialGrants, that.specialGrants) &&
            Objects.equals(this.userCustomFields, that.userCustomFields) &&
            Objects.equals(this.users, that.users);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.applicationAccess, 
            this.groupCustomFields, 
            this.groups, 
            this.permissionKeys, 
            this.projectRoles, 
            this.specialGrants, 
            this.userCustomFields, 
            this.users
        );
    }

    @Override
    public String toString() {
        return "PermissionGrantDto{" +
            "applicationAccess=" + applicationAccess + ", " + 
            "groupCustomFields=" + groupCustomFields + ", " + 
            "groups=" + groups + ", " + 
            "permissionKeys=" + permissionKeys + ", " + 
            "projectRoles=" + projectRoles + ", " + 
            "specialGrants=" + specialGrants + ", " + 
            "userCustomFields=" + userCustomFields + ", " + 
            "users=" + users +
            "}";
    }
}
