// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * OperatorEnumd10419
 * <p>
 * The operator between the field and the operand.
 *
 */
@JsonTypeName("OperatorEnumd10419")
@Generated(value = "io.github.primelib.primecodegen")
public enum OperatorEnumd10419 {
    AFTER("after"),
    BEFORE("before"),
    BY("by"),
    DURING("during"),
    FROM("from"),
    ON("on"),
    TO("to"),
    ;

    private final String value;

    OperatorEnumd10419(String value) {
        this.value = value;
    }
}
