// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * ViewTypeEnum
 * <p>
 * The view type of the context. Only `GIC`(Global Issue Create), `IssueView` and `IssueTransition` are supported. Null is treated as a wildcard, meaning the UI modification will be applied to all view types. Each UI modification context can have a maximum of one wildcard.
 *
 */
@JsonTypeName("ViewTypeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum ViewTypeEnum {
    GIC("GIC"),
    ISSUE_TRANSITION("IssueTransition"),
    ISSUE_VIEW("IssueView"),
    ;

    private final String value;

    ViewTypeEnum(String value) {
        this.value = value;
    }
}
