// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.PageBeanScreen;
import io.github.primelib.jira4j.rest.v2.models.PageBeanScreenWithTab;
import io.github.primelib.jira4j.rest.v2.models.Screen;
import io.github.primelib.jira4j.rest.v2.models.ScreenableField;
import io.github.primelib.jira4j.rest.v2.operations.Delete2ScreenByScreenIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2FieldByFieldIDScreensV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2ScreenByScreenIDAvailableFieldsV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2ScreensV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2ScreensAddToDefaultByFieldIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2ScreensV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2ScreenByScreenIDV1OperationSpec;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientScreensConsumerApi
 *
 * This resource represents the screens used to record issue details. Use it to:
 * 
 *  *  get details of all screens.
 *  *  get details of all the fields available for use on screens.
 *  *  create screens.
 *  *  delete screens.
 *  *  update screens.
 *  *  add a field to the default screen.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientScreensConsumerApi {
    private final JiraRestClientScreensApi api;

    public JiraRestClientScreensConsumerApi(JiraRestClientScreensApi api) {
        this.api = api;
    }


    /**
    * Get2FieldByFieldIDScreensV1
    * Get screens for a field
    * Returns a [paginated](#pagination) list of the screens a field is used in.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>fieldId: The ID of the field to return screens for.</li>
    *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
    *   <li>maxResults: The maximum number of items to return per page.</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about screens in the response. This parameter accepts `tab` which returns details about the screen tabs the field is used in.</li>
    * </ul>
    */
    public PageBeanScreenWithTab Get2FieldByFieldIDScreensV1(Consumer<Get2FieldByFieldIDScreensV1OperationSpec> spec) {
        Get2FieldByFieldIDScreensV1OperationSpec r = new Get2FieldByFieldIDScreensV1OperationSpec(spec);
        return api.Get2FieldByFieldIDScreensV1(r.fieldId(), r.startAt(), r.maxResults(), r.expand());
    }

    /**
    * Get2ScreensV1
    * Get screens
    * Returns a [paginated](#pagination) list of all screens or those specified by one or more screen IDs.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
    *   <li>maxResults: The maximum number of items to return per page.</li>
    *   <li>id: The list of screen IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&amp;id=10001`.</li>
    *   <li>queryString: String used to perform a case-insensitive partial match with screen name.</li>
    *   <li>scope: The scope filter string. To filter by multiple scope, provide an ampersand-separated list. For example, `scope=GLOBAL&amp;scope=PROJECT`.</li>
    *   <li>orderBy: [Order](#ordering) the results by a field:   *  `id` Sorts by screen ID.  *  `name` Sorts by screen name.</li>
    * </ul>
    */
    public PageBeanScreen Get2ScreensV1(Consumer<Get2ScreensV1OperationSpec> spec) {
        Get2ScreensV1OperationSpec r = new Get2ScreensV1OperationSpec(spec);
        return api.Get2ScreensV1(r.startAt(), r.maxResults(), r.id(), r.queryString(), r.scope(), r.orderBy());
    }

    /**
    * Post2ScreensV1
    * Create screen
    * Creates a screen with a default field tab.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: </li>
    * </ul>
    */
    public Screen Post2ScreensV1(Consumer<Post2ScreensV1OperationSpec> spec) {
        Post2ScreensV1OperationSpec r = new Post2ScreensV1OperationSpec(spec);
        return api.Post2ScreensV1(r.payload());
    }

    /**
    * Post2ScreensAddToDefaultByFieldIDV1
    * Add field to default screen
    * Adds a field to the default tab of the default screen.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>fieldId: The ID of the field.</li>
    * </ul>
    */
    public Object Post2ScreensAddToDefaultByFieldIDV1(Consumer<Post2ScreensAddToDefaultByFieldIDV1OperationSpec> spec) {
        Post2ScreensAddToDefaultByFieldIDV1OperationSpec r = new Post2ScreensAddToDefaultByFieldIDV1OperationSpec(spec);
        return api.Post2ScreensAddToDefaultByFieldIDV1(r.fieldId());
    }

    /**
    * Put2ScreenByScreenIDV1
    * Update screen
    * Updates a screen. Only screens used in classic projects can be updated.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>screenId: The ID of the screen.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public Screen Put2ScreenByScreenIDV1(Consumer<Put2ScreenByScreenIDV1OperationSpec> spec) {
        Put2ScreenByScreenIDV1OperationSpec r = new Put2ScreenByScreenIDV1OperationSpec(spec);
        return api.Put2ScreenByScreenIDV1(r.screenId(), r.payload());
    }

    /**
    * Delete2ScreenByScreenIDV1
    * Delete screen
    * Deletes a screen. A screen cannot be deleted if it is used in a screen scheme, workflow, or workflow draft.
    * 
    * Only screens used in classic projects can be deleted.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>screenId: The ID of the screen.</li>
    * </ul>
    */
    public void Delete2ScreenByScreenIDV1(Consumer<Delete2ScreenByScreenIDV1OperationSpec> spec) {
        Delete2ScreenByScreenIDV1OperationSpec r = new Delete2ScreenByScreenIDV1OperationSpec(spec);
        api.Delete2ScreenByScreenIDV1(r.screenId());
    }

    /**
    * Get2ScreenByScreenIDAvailableFieldsV1
    * Get available screen fields
    * Returns the fields that can be added to a tab on a screen.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>screenId: The ID of the screen.</li>
    * </ul>
    */
    public List<ScreenableField> Get2ScreenByScreenIDAvailableFieldsV1(Consumer<Get2ScreenByScreenIDAvailableFieldsV1OperationSpec> spec) {
        Get2ScreenByScreenIDAvailableFieldsV1OperationSpec r = new Get2ScreenByScreenIDAvailableFieldsV1OperationSpec(spec);
        return api.Get2ScreenByScreenIDAvailableFieldsV1(r.screenId());
    }

}
