// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.EntityProperty;
import io.github.primelib.jira4j.rest.v2.models.OperationMessage;
import io.github.primelib.jira4j.rest.v2.models.PropertyKeys;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * JiraRestClientAppPropertiesApi
 *
 * This resource represents app properties. Use it to store arbitrary data for your
 * [Connect app](https://developer.atlassian.com/cloud/jira/platform/index/#connect-apps).
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraRestClientAppPropertiesApi {

    /**
    * GetAtlassianConnect1AddonByAddonKeyPropertiesV1
    * Get app properties
    * Gets all the properties of an app.
    * 
    * **[Permissions](#permissions) required:** Only a Connect app whose key matches `addonKey` can make this request.
    * Additionally, Forge apps can access Connect app properties (stored against the same `app.connect.key`).
    *
    * @param addonKey The key of the app, as defined in its descriptor.
    */
    @RequestLine("GET /rest/atlassian-connect/1/addons/{addonKey}/properties")
    @Headers({
        "Accept: application/json"
    })
    PropertyKeys GetAtlassianConnect1AddonByAddonKeyPropertiesV1(
            @NotNull @Param("addonKey") String addonKey
    );

    /**
    * GetAtlassianConnect1AddonByAddonKeyPropertyByPropertyKeyV1
    * Get app property
    * Returns the key and value of an app's property.
    * 
    * **[Permissions](#permissions) required:** Only a Connect app whose key matches `addonKey` can make this request.
    * Additionally, Forge apps can access Connect app properties (stored against the same `app.connect.key`).
    *
    * @param addonKey The key of the app, as defined in its descriptor.
    * @param propertyKey The key of the property.
    */
    @RequestLine("GET /rest/atlassian-connect/1/addons/{addonKey}/properties/{propertyKey}")
    @Headers({
        "Accept: application/json"
    })
    EntityProperty GetAtlassianConnect1AddonByAddonKeyPropertyByPropertyKeyV1(
            @NotNull @Param("addonKey") String addonKey,
            @NotNull @Param("propertyKey") String propertyKey
    );

    /**
    * PutAtlassianConnect1AddonByAddonKeyPropertyByPropertyKeyV1
    * Set app property
    * Sets the value of an app's property. Use this resource to store custom data for your app.
    * 
    * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
    * 
    * **[Permissions](#permissions) required:** Only a Connect app whose key matches `addonKey` can make this request.
    * Additionally, Forge apps can access Connect app properties (stored against the same `app.connect.key`).
    *
    * @param addonKey The key of the app, as defined in its descriptor.
    * @param propertyKey The key of the property.
    * @param payload 
    */
    @RequestLine("PUT /rest/atlassian-connect/1/addons/{addonKey}/properties/{propertyKey}")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    OperationMessage PutAtlassianConnect1AddonByAddonKeyPropertyByPropertyKeyV1(
            @NotNull @Param("addonKey") String addonKey,
            @NotNull @Param("propertyKey") String propertyKey,
            @NotNull Object payload
    );

    /**
    * DeleteAtlassianConnect1AddonByAddonKeyPropertyByPropertyKeyV1
    * Delete app property
    * Deletes an app's property.
    * 
    * **[Permissions](#permissions) required:** Only a Connect app whose key matches `addonKey` can make this request.
    * Additionally, Forge apps can access Connect app properties (stored against the same `app.connect.key`).
    *
    * @param addonKey The key of the app, as defined in its descriptor.
    * @param propertyKey The key of the property.
    */
    @RequestLine("DELETE /rest/atlassian-connect/1/addons/{addonKey}/properties/{propertyKey}")
    void DeleteAtlassianConnect1AddonByAddonKeyPropertyByPropertyKeyV1(
            @NotNull @Param("addonKey") String addonKey,
            @NotNull @Param("propertyKey") String propertyKey
    );

    /**
    * PutForge1AppPropertyByPropertyKeyV1
    * Set app property (Forge)
    * Sets the value of a Forge app's property.
    * These values can be retrieved in [Jira expressions](/cloud/jira/platform/jira-expressions/)
    * through the `app` [context variable](/cloud/jira/platform/jira-expressions/#context-variables).
    * They are also available in [entity property display conditions](/platform/forge/manifest-reference/display-conditions/entity-property-conditions/).
    * 
    * For other use cases, use the [Storage API](/platform/forge/runtime-reference/storage-api/).
    * 
    * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
    * 
    * **[Permissions](#permissions) required:** Only Forge apps can make this request.
    * 
    * The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
    *
    * @param propertyKey The key of the property.
    * @param payload 
    */
    @RequestLine("PUT /rest/forge/1/app/properties/{propertyKey}")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    OperationMessage PutForge1AppPropertyByPropertyKeyV1(
            @NotNull @Param("propertyKey") String propertyKey,
            @NotNull Object payload
    );

    /**
    * DeleteForge1AppPropertyByPropertyKeyV1
    * Delete app property (Forge)
    * Deletes a Forge app's property.
    * 
    * **[Permissions](#permissions) required:** Only Forge apps can make this request.
    * 
    * The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
    *
    * @param propertyKey The key of the property.
    */
    @RequestLine("DELETE /rest/forge/1/app/properties/{propertyKey}")
    void DeleteForge1AppPropertyByPropertyKeyV1(
            @NotNull @Param("propertyKey") String propertyKey
    );

}
