// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.BulkChangelogResponseBean;
import io.github.primelib.jira4j.rest.v2.models.BulkIssueResults;
import io.github.primelib.jira4j.rest.v2.models.CreatedIssue;
import io.github.primelib.jira4j.rest.v2.models.CreatedIssues;
import io.github.primelib.jira4j.rest.v2.models.IssueArchivalSyncResponse;
import io.github.primelib.jira4j.rest.v2.models.IssueBean;
import io.github.primelib.jira4j.rest.v2.models.IssueCreateMetadata;
import io.github.primelib.jira4j.rest.v2.models.IssueEvent;
import io.github.primelib.jira4j.rest.v2.models.IssueLimitReportResponseBean;
import io.github.primelib.jira4j.rest.v2.models.IssueUpdateMetadata;
import io.github.primelib.jira4j.rest.v2.models.PageBeanChangelog;
import io.github.primelib.jira4j.rest.v2.models.PageOfChangelogs;
import io.github.primelib.jira4j.rest.v2.models.Transitions;
import io.github.primelib.jira4j.rest.v2.operations.Delete2IssueByIssueIDOrKeyV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2EventsV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueByIssueIDOrKeyChangelogV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueByIssueIDOrKeyEditmetaV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueByIssueIDOrKeyTransitionsV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueByIssueIDOrKeyV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueCreatemetaByProjectIDOrKeyIssuetypeByIssueTypeIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueCreatemetaByProjectIDOrKeyIssuetypesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueCreatemetaV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueLimitReportV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2ChangelogBulkfetchV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueArchiveV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueBulkV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueBulkfetchV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueByIssueIDOrKeyChangelogListV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueByIssueIDOrKeyNotifyV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueByIssueIDOrKeyTransitionsV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssueArchiveV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssueByIssueIDOrKeyV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssueUnarchiveV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssuesArchiveExportV1OperationSpec;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientIssuesConsumerApi
 *
 * This resource represents Jira issues. Use it to:
 * 
 *  *  create or edit issues, individually or in bulk.
 *  *  retrieve metadata about the options for creating or editing issues.
 *  *  delete an issue.
 *  *  assign a user to an issue.
 *  *  get issue changelogs.
 *  *  send notifications about an issue.
 *  *  get details of the transitions available for an issue.
 *  *  transition an issue.
 *  *  Archive issues.
 *  *  Unarchive issues.
 *  *  Export archived issues.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientIssuesConsumerApi {
    private final JiraRestClientIssuesApi api;

    public JiraRestClientIssuesConsumerApi(JiraRestClientIssuesApi api) {
        this.api = api;
    }


    /**
    * Post2ChangelogBulkfetchV1
    * Bulk fetch changelogs
    * Bulk fetch changelogs for multiple issues and filter by fields
    * 
    * Returns a paginated list of all changelogs for given issues sorted by changelog date and issue IDs, starting from the oldest changelog and smallest issue ID.
    * 
    * Issues are identified by their ID or key, and optionally changelogs can be filtered by their field IDs. You can request the changelogs of up to 1000 issues and can filter them by up to 10 field IDs.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the projects that the issues are in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issues.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: A JSON object containing the bulk fetch changelog request filters such as issue IDs and field IDs.</li>
    * </ul>
    */
    public BulkChangelogResponseBean Post2ChangelogBulkfetchV1(Consumer<Post2ChangelogBulkfetchV1OperationSpec> spec) {
        Post2ChangelogBulkfetchV1OperationSpec r = new Post2ChangelogBulkfetchV1OperationSpec(spec);
        return api.Post2ChangelogBulkfetchV1(r.payload());
    }

    /**
    * Get2EventsV1
    * Get events
    * Returns all issue events.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    */
    public List<IssueEvent> Get2EventsV1(Consumer<Get2EventsV1OperationSpec> spec) {
        Get2EventsV1OperationSpec r = new Get2EventsV1OperationSpec(spec);
        return api.Get2EventsV1();
    }

    /**
    * Post2IssueV1
    * Create issue
    * Creates an issue or, where the option to create subtasks is enabled in Jira, a subtask. A transition may be applied, to move the issue or subtask to a workflow step other than the default start step, and issue properties set.
    * 
    * The content of the issue or subtask is defined using `update` and `fields`. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get). These are the same fields that appear on the issue's create screen.
    * 
    * Creating a subtask differs from creating an issue as follows:
    * 
    *  *  `issueType` must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get) to find subtask issue types).
    *  *  `parent` must contain the ID or key of the parent issue.
    * 
    * **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which the issue or subtask is created.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>updateHistory: Whether the project in which the issue is created is added to the user's **Recently viewed** project list, as shown under **Projects** in Jira. When provided, the issue type and request type are added to the user's history for a project. These values are then used to provide defaults on the issue create screen.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public CreatedIssue Post2IssueV1(Consumer<Post2IssueV1OperationSpec> spec) {
        Post2IssueV1OperationSpec r = new Post2IssueV1OperationSpec(spec);
        return api.Post2IssueV1(r.updateHistory(), r.payload());
    }

    /**
    * Put2IssueArchiveV1
    * Archive issue(s) by issue ID/key
    * Enables admins to archive up to 1000 issues in a single request using issue ID/key, returning details of the issue(s) archived in the process and the errors encountered, if any.
    * 
    * **Note that:**
    * 
    *  *  you can't archive subtasks directly, only through their parent issues
    *  *  you can only archive issues from software, service management, and business projects
    * 
    * **[Permissions](#permissions) required:** Jira admin or site admin: [global permission](https://confluence.atlassian.com/x/x4dKLg)
    * 
    * **License required:** Premium or Enterprise
    * 
    * **Signed-in users only:** This API can't be accessed anonymously.
    * 
    *   
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: Contains a list of issue keys or IDs to be archived.</li>
    * </ul>
    */
    public IssueArchivalSyncResponse Put2IssueArchiveV1(Consumer<Put2IssueArchiveV1OperationSpec> spec) {
        Put2IssueArchiveV1OperationSpec r = new Put2IssueArchiveV1OperationSpec(spec);
        return api.Put2IssueArchiveV1(r.payload());
    }

    /**
    * Post2IssueArchiveV1
    * Archive issue(s) by JQL
    * Enables admins to archive up to 100,000 issues in a single request using JQL, returning the URL to check the status of the submitted request.
    * 
    * You can use the [get task](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-tasks/#api-rest-api-3-task-taskid-get) and [cancel task](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-tasks/#api-rest-api-3-task-taskid-cancel-post) APIs to manage the request.
    * 
    * **Note that:**
    * 
    *  *  you can't archive subtasks directly, only through their parent issues
    *  *  you can only archive issues from software, service management, and business projects
    * 
    * **[Permissions](#permissions) required:** Jira admin or site admin: [global permission](https://confluence.atlassian.com/x/x4dKLg)
    * 
    * **License required:** Premium or Enterprise
    * 
    * **Signed-in users only:** This API can't be accessed anonymously.
    * 
    * **Rate limiting:** Only a single request per jira instance can be active at any given time.
    * 
    *   
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: A JQL query specifying the issues to archive. Note that subtasks can only be archived through their parent issues.</li>
    * </ul>
    */
    public void Post2IssueArchiveV1(Consumer<Post2IssueArchiveV1OperationSpec> spec) {
        Post2IssueArchiveV1OperationSpec r = new Post2IssueArchiveV1OperationSpec(spec);
        api.Post2IssueArchiveV1(r.payload());
    }

    /**
    * Post2IssueBulkV1
    * Bulk create issue
    * Creates upto **50** issues and, where the option to create subtasks is enabled in Jira, subtasks. Transitions may be applied, to move the issues or subtasks to a workflow step other than the default start step, and issue properties set.
    * 
    * The content of each issue or subtask is defined using `update` and `fields`. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get). These are the same fields that appear on the issues' create screens.
    * 
    * Creating a subtask differs from creating an issue as follows:
    * 
    *  *  `issueType` must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get) to find subtask issue types).
    *  *  `parent` the must contain the ID or key of the parent issue.
    * 
    * **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which each issue or subtask is created.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: </li>
    * </ul>
    */
    public CreatedIssues Post2IssueBulkV1(Consumer<Post2IssueBulkV1OperationSpec> spec) {
        Post2IssueBulkV1OperationSpec r = new Post2IssueBulkV1OperationSpec(spec);
        return api.Post2IssueBulkV1(r.payload());
    }

    /**
    * Post2IssueBulkfetchV1
    * Bulk fetch issues
    * Returns the details for a set of requested issues. You can request up to 100 issues.
    * 
    * Each issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned.
    * 
    * Issues will be returned in ascending `id` order. If there are errors, Jira will return a list of issues which couldn't be fetched along with error messages.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: A JSON object containing the information about which issues and fields to fetch.</li>
    * </ul>
    */
    public BulkIssueResults Post2IssueBulkfetchV1(Consumer<Post2IssueBulkfetchV1OperationSpec> spec) {
        Post2IssueBulkfetchV1OperationSpec r = new Post2IssueBulkfetchV1OperationSpec(spec);
        return api.Post2IssueBulkfetchV1(r.payload());
    }

    /**
    * Get2IssueCreatemetaV1
    * Get create issue metadata
    * Returns details of projects, issue types within projects, and, when requested, the create screen fields for each issue type for the user. Use the information to populate the requests in [ Create issue](#api-rest-api-2-issue-post) and [Create issues](#api-rest-api-2-issue-bulk-post).
    * 
    * Deprecated, see [Create Issue Meta Endpoint Deprecation Notice](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-1304).
    * 
    * The request can be restricted to specific projects or issue types using the query parameters. The response will contain information for the valid projects, issue types, or project and issue type combinations requested. Note that invalid project, issue type, or project and issue type combinations do not generate errors.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>projectIds: List of project IDs. This parameter accepts a comma-separated list. Multiple project IDs can also be provided using an ampersand-separated list. For example, `projectIds=10000,10001&amp;projectIds=10020,10021`. This parameter may be provided with `projectKeys`.</li>
    *   <li>projectKeys: List of project keys. This parameter accepts a comma-separated list. Multiple project keys can also be provided using an ampersand-separated list. For example, `projectKeys=proj1,proj2&amp;projectKeys=proj3`. This parameter may be provided with `projectIds`.</li>
    *   <li>issuetypeIds: List of issue type IDs. This parameter accepts a comma-separated list. Multiple issue type IDs can also be provided using an ampersand-separated list. For example, `issuetypeIds=10000,10001&amp;issuetypeIds=10020,10021`. This parameter may be provided with `issuetypeNames`.</li>
    *   <li>issuetypeNames: List of issue type names. This parameter accepts a comma-separated list. Multiple issue type names can also be provided using an ampersand-separated list. For example, `issuetypeNames=name1,name2&amp;issuetypeNames=name3`. This parameter may be provided with `issuetypeIds`.</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about issue metadata in the response. This parameter accepts `projects.issuetypes.fields`, which returns information about the fields in the issue creation screen for each issue type. Fields hidden from the screen are not returned. Use the information to populate the `fields` and `update` fields in [Create issue](#api-rest-api-2-issue-post) and [Create issues](#api-rest-api-2-issue-bulk-post).</li>
    * </ul>
    * @deprecated
    */
    @Deprecated
    public IssueCreateMetadata Get2IssueCreatemetaV1(Consumer<Get2IssueCreatemetaV1OperationSpec> spec) {
        Get2IssueCreatemetaV1OperationSpec r = new Get2IssueCreatemetaV1OperationSpec(spec);
        return api.Get2IssueCreatemetaV1(r.projectIds(), r.projectKeys(), r.issuetypeIds(), r.issuetypeNames(), r.expand());
    }

    /**
    * Get2IssueCreatemetaByProjectIDOrKeyIssuetypesV1
    * Get create metadata issue types for a project
    * Returns a page of issue type metadata for a specified project. Use the information to populate the requests in [ Create issue](#api-rest-api-2-issue-post) and [Create issues](#api-rest-api-2-issue-bulk-post).
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>projectIdOrKey: The ID or key of the project.</li>
    *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
    *   <li>maxResults: The maximum number of items to return per page.</li>
    * </ul>
    */
    public Map<String, Object> Get2IssueCreatemetaByProjectIDOrKeyIssuetypesV1(Consumer<Get2IssueCreatemetaByProjectIDOrKeyIssuetypesV1OperationSpec> spec) {
        Get2IssueCreatemetaByProjectIDOrKeyIssuetypesV1OperationSpec r = new Get2IssueCreatemetaByProjectIDOrKeyIssuetypesV1OperationSpec(spec);
        return api.Get2IssueCreatemetaByProjectIDOrKeyIssuetypesV1(r.projectIdOrKey(), r.startAt(), r.maxResults());
    }

    /**
    * Get2IssueCreatemetaByProjectIDOrKeyIssuetypeByIssueTypeIDV1
    * Get create field metadata for a project and issue type id
    * Returns a page of field metadata for a specified project and issuetype id. Use the information to populate the requests in [ Create issue](#api-rest-api-2-issue-post) and [Create issues](#api-rest-api-2-issue-bulk-post).
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>projectIdOrKey: The ID or key of the project.</li>
    *   <li>issueTypeId: The issuetype ID.</li>
    *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
    *   <li>maxResults: The maximum number of items to return per page.</li>
    * </ul>
    */
    public Map<String, Object> Get2IssueCreatemetaByProjectIDOrKeyIssuetypeByIssueTypeIDV1(Consumer<Get2IssueCreatemetaByProjectIDOrKeyIssuetypeByIssueTypeIDV1OperationSpec> spec) {
        Get2IssueCreatemetaByProjectIDOrKeyIssuetypeByIssueTypeIDV1OperationSpec r = new Get2IssueCreatemetaByProjectIDOrKeyIssuetypeByIssueTypeIDV1OperationSpec(spec);
        return api.Get2IssueCreatemetaByProjectIDOrKeyIssuetypeByIssueTypeIDV1(r.projectIdOrKey(), r.issueTypeId(), r.startAt(), r.maxResults());
    }

    /**
    * Get2IssueLimitReportV1
    * Get issue limit report
    * Returns all issues breaching and approaching per-issue limits.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) is required for the project the issues are in. Results may be incomplete otherwise
    *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>isReturningKeys: Return issue keys instead of issue ids in the response.  Usage: Add `?isReturningKeys=true` to the end of the path to request issue keys.</li>
    * </ul>
    */
    public IssueLimitReportResponseBean Get2IssueLimitReportV1(Consumer<Get2IssueLimitReportV1OperationSpec> spec) {
        Get2IssueLimitReportV1OperationSpec r = new Get2IssueLimitReportV1OperationSpec(spec);
        return api.Get2IssueLimitReportV1(r.isReturningKeys());
    }

    /**
    * Put2IssueUnarchiveV1
    * Unarchive issue(s) by issue keys/ID
    * Enables admins to unarchive up to 1000 issues in a single request using issue ID/key, returning details of the issue(s) unarchived in the process and the errors encountered, if any.
    * 
    * **Note that:**
    * 
    *  *  you can't unarchive subtasks directly, only through their parent issues
    *  *  you can only unarchive issues from software, service management, and business projects
    * 
    * **[Permissions](#permissions) required:** Jira admin or site admin: [global permission](https://confluence.atlassian.com/x/x4dKLg)
    * 
    * **License required:** Premium or Enterprise
    * 
    * **Signed-in users only:** This API can't be accessed anonymously.
    * 
    *   
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: Contains a list of issue keys or IDs to be unarchived.</li>
    * </ul>
    */
    public IssueArchivalSyncResponse Put2IssueUnarchiveV1(Consumer<Put2IssueUnarchiveV1OperationSpec> spec) {
        Put2IssueUnarchiveV1OperationSpec r = new Put2IssueUnarchiveV1OperationSpec(spec);
        return api.Put2IssueUnarchiveV1(r.payload());
    }

    /**
    * Get2IssueByIssueIDOrKeyV1
    * Get issue
    * Returns the details for an issue.
    * 
    * The issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned. The issue key returned in the response is the key of the issue found.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>fields: A list of fields to return for the issue. This parameter accepts a comma-separated list. Use it to retrieve a subset of fields. Allowed values:   *  `*all` Returns all fields.  *  `*navigable` Returns navigable fields.  *  Any issue field, prefixed with a minus to exclude.  Examples:   *  `summary,comment` Returns only the summary and comments fields.  *  `-description` Returns all (default) fields except description.  *  `*navigable,-comment` Returns all navigable fields except comment.  This parameter may be specified multiple times. For example, `fields=field1,field2&amp; fields=field3`.  Note: All fields are returned by default. This differs from [Search for issues using JQL (GET)](#api-rest-api-2-search-get) and [Search for issues using JQL (POST)](#api-rest-api-2-search-post) where the default is all navigable fields.</li>
    *   <li>fieldsByKeys: Whether fields in `fields` are referenced by keys rather than IDs. This parameter is useful where fields have been added by a connect app and a field's key may differ from its ID.</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about the issues in the response. This parameter accepts a comma-separated list. Expand options include:   *  `renderedFields` Returns field values rendered in HTML format.  *  `names` Returns the display name of each field.  *  `schema` Returns the schema describing a field type.  *  `transitions` Returns all possible transitions for the issue.  *  `editmeta` Returns information about how each field can be edited.  *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.  *  `versionedRepresentations` Returns a JSON array for each version of a field's value, with the highest number representing the most recent version. Note: When included in the request, the `fields` parameter is ignored.</li>
    *   <li>properties: A list of issue properties to return for the issue. This parameter accepts a comma-separated list. Allowed values:   *  `*all` Returns all issue properties.  *  Any issue property key, prefixed with a minus to exclude.  Examples:   *  `*all` Returns all properties.  *  `*all,-prop1` Returns all properties except `prop1`.  *  `prop1,prop2` Returns `prop1` and `prop2` properties.  This parameter may be specified multiple times. For example, `properties=prop1,prop2&amp; properties=prop3`.</li>
    *   <li>updateHistory: Whether the project in which the issue is created is added to the user's **Recently viewed** project list, as shown under **Projects** in Jira. This also populates the [JQL issues search](#api-rest-api-2-search-get) `lastViewed` field.</li>
    *   <li>failFast: Whether to fail the request quickly in case of an error while loading fields for an issue. For `failFast=true`, if one field fails, the entire operation fails. For `failFast=false`, the operation will continue even if a field fails. It will return a valid response, but without values for the failed field(s).</li>
    * </ul>
    */
    public IssueBean Get2IssueByIssueIDOrKeyV1(Consumer<Get2IssueByIssueIDOrKeyV1OperationSpec> spec) {
        Get2IssueByIssueIDOrKeyV1OperationSpec r = new Get2IssueByIssueIDOrKeyV1OperationSpec(spec);
        return api.Get2IssueByIssueIDOrKeyV1(r.issueIdOrKey(), r.fields(), r.fieldsByKeys(), r.expand(), r.properties(), r.updateHistory(), r.failFast());
    }

    /**
    * Put2IssueByIssueIDOrKeyV1
    * Edit issue
    * Edits an issue. Issue properties may be updated as part of the edit. Please note that issue transition is not supported and is ignored here. To transition an issue, please use [Transition issue](#api-rest-api-2-issue-issueIdOrKey-transitions-post).
    * 
    * The edits to the issue's fields are defined using `update` and `fields`. The fields that can be edited are determined using [ Get edit issue metadata](#api-rest-api-2-issue-issueIdOrKey-editmeta-get).
    * 
    * The parent field may be set by key or ID. For standard issue types, the parent may be removed by setting `update.parent.set.none` to *true*.
    * 
    * Connect apps having an app user with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), can override the screen security configuration using `overrideScreenSecurity` and `overrideEditableFlag`.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* and *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>notifyUsers: Whether a notification email about the issue update is sent to all watchers. To disable the notification, administer Jira or administer project permissions are required. If the user doesn't have the necessary permission the request is ignored.</li>
    *   <li>overrideScreenSecurity: Whether screen security is overridden to enable hidden fields to be edited. Available to Connect app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).</li>
    *   <li>overrideEditableFlag: Whether screen security is overridden to enable uneditable fields to be edited. Available to Connect app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).</li>
    *   <li>returnIssue: Whether the response should contain the issue with fields edited in this request. The returned issue will have the same format as in the [Get issue API](#api-rest-api-3-issue-issueidorkey-get).</li>
    *   <li>expand: The Get issue API expand parameter to use in the response if the `returnIssue` parameter is `true`.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public Object Put2IssueByIssueIDOrKeyV1(Consumer<Put2IssueByIssueIDOrKeyV1OperationSpec> spec) {
        Put2IssueByIssueIDOrKeyV1OperationSpec r = new Put2IssueByIssueIDOrKeyV1OperationSpec(spec);
        return api.Put2IssueByIssueIDOrKeyV1(r.issueIdOrKey(), r.notifyUsers(), r.overrideScreenSecurity(), r.overrideEditableFlag(), r.returnIssue(), r.expand(), r.payload());
    }

    /**
    * Delete2IssueByIssueIDOrKeyV1
    * Delete issue
    * Deletes an issue.
    * 
    * An issue cannot be deleted if it has one or more subtasks. To delete an issue with subtasks, set `deleteSubtasks`. This causes the issue's subtasks to be deleted with the issue.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* and *Delete issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>deleteSubtasks: Whether the issue's subtasks are deleted when the issue is deleted.</li>
    * </ul>
    */
    public void Delete2IssueByIssueIDOrKeyV1(Consumer<Delete2IssueByIssueIDOrKeyV1OperationSpec> spec) {
        Delete2IssueByIssueIDOrKeyV1OperationSpec r = new Delete2IssueByIssueIDOrKeyV1OperationSpec(spec);
        api.Delete2IssueByIssueIDOrKeyV1(r.issueIdOrKey(), r.deleteSubtasks());
    }

    /**
    * Put2IssueByIssueIDOrKeyAssigneeV1
    * Assign issue
    * Assigns an issue to a user. Use this operation when the calling user does not have the *Edit Issues* permission but has the *Assign issue* permission for the project that the issue is in.
    * 
    * If `name` or `accountId` is set to:
    * 
    *  *  `"-1"`, the issue is assigned to the default assignee for the project.
    *  *  `null`, the issue is set to unassigned.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse Projects* and *Assign Issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue to be assigned.</li>
    *   <li>payload: The request object with the user that the issue is assigned to.</li>
    * </ul>
    */
    public void Put2IssueByIssueIDOrKeyAssigneeV1(Consumer<Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec> spec) {
        Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec r = new Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec(spec);
        api.Put2IssueByIssueIDOrKeyAssigneeV1(r.issueIdOrKey(), r.payload());
    }

    /**
    * Get2IssueByIssueIDOrKeyChangelogV1
    * Get changelogs
    * Returns a [paginated](#pagination) list of all changelogs for an issue sorted by date, starting from the oldest.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
    *   <li>maxResults: The maximum number of items to return per page.</li>
    * </ul>
    */
    public PageBeanChangelog Get2IssueByIssueIDOrKeyChangelogV1(Consumer<Get2IssueByIssueIDOrKeyChangelogV1OperationSpec> spec) {
        Get2IssueByIssueIDOrKeyChangelogV1OperationSpec r = new Get2IssueByIssueIDOrKeyChangelogV1OperationSpec(spec);
        return api.Get2IssueByIssueIDOrKeyChangelogV1(r.issueIdOrKey(), r.startAt(), r.maxResults());
    }

    /**
    * Post2IssueByIssueIDOrKeyChangelogListV1
    * Get changelogs by IDs
    * Returns changelogs for an issue specified by a list of changelog IDs.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public PageOfChangelogs Post2IssueByIssueIDOrKeyChangelogListV1(Consumer<Post2IssueByIssueIDOrKeyChangelogListV1OperationSpec> spec) {
        Post2IssueByIssueIDOrKeyChangelogListV1OperationSpec r = new Post2IssueByIssueIDOrKeyChangelogListV1OperationSpec(spec);
        return api.Post2IssueByIssueIDOrKeyChangelogListV1(r.issueIdOrKey(), r.payload());
    }

    /**
    * Get2IssueByIssueIDOrKeyEditmetaV1
    * Get edit issue metadata
    * Returns the edit screen fields for an issue that are visible to and editable by the user. Use the information to populate the requests in [Edit issue](#api-rest-api-2-issue-issueIdOrKey-put).
    * 
    * This endpoint will check for these conditions:
    * 
    * 1.  Field is available on a field screen - through screen, screen scheme, issue type screen scheme, and issue type scheme configuration. `overrideScreenSecurity=true` skips this condition.
    * 2.  Field is visible in the [field configuration](https://support.atlassian.com/jira-cloud-administration/docs/change-a-field-configuration/). `overrideScreenSecurity=true` skips this condition.
    * 3.  Field is shown on the issue: each field has different conditions here. For example: Attachment field only shows if attachments are enabled. Assignee only shows if user has permissions to assign the issue.
    * 4.  If a field is custom then it must have valid custom field context, applicable for its project and issue type. All system fields are assumed to have context in all projects and all issue types.
    * 5.  Issue has a project, issue type, and status defined.
    * 6.  Issue is assigned to a valid workflow, and the current status has assigned a workflow step. `overrideEditableFlag=true` skips this condition.
    * 7.  The current workflow step is editable. This is true by default, but [can be disabled by setting](https://support.atlassian.com/jira-cloud-administration/docs/use-workflow-properties/) the `jira.issue.editable` property to `false`. `overrideEditableFlag=true` skips this condition.
    * 8.  User has [Edit issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/).
    * 9.  Workflow permissions allow editing a field. This is true by default but [can be modified](https://support.atlassian.com/jira-cloud-administration/docs/use-workflow-properties/) using `jira.permission.*` workflow properties.
    * 
    * Fields hidden using [Issue layout settings page](https://support.atlassian.com/jira-software-cloud/docs/configure-field-layout-in-the-issue-view/) remain editable.
    * 
    * Connect apps having an app user with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), can return additional details using:
    * 
    *  *  `overrideScreenSecurity` When this flag is `true`, then this endpoint skips checking if fields are available through screens, and field configuration (conditions 1. and 2. from the list above).
    *  *  `overrideEditableFlag` When this flag is `true`, then this endpoint skips checking if workflow is present and if the current step is editable (conditions 6. and 7. from the list above).
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    * 
    * Note: For any fields to be editable the user must have the *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>overrideScreenSecurity: Whether hidden fields are returned. Available to Connect app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).</li>
    *   <li>overrideEditableFlag: Whether non-editable fields are returned. Available to Connect app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).</li>
    * </ul>
    */
    public IssueUpdateMetadata Get2IssueByIssueIDOrKeyEditmetaV1(Consumer<Get2IssueByIssueIDOrKeyEditmetaV1OperationSpec> spec) {
        Get2IssueByIssueIDOrKeyEditmetaV1OperationSpec r = new Get2IssueByIssueIDOrKeyEditmetaV1OperationSpec(spec);
        return api.Get2IssueByIssueIDOrKeyEditmetaV1(r.issueIdOrKey(), r.overrideScreenSecurity(), r.overrideEditableFlag());
    }

    /**
    * Post2IssueByIssueIDOrKeyNotifyV1
    * Send notification for issue
    * Creates an email notification for an issue and adds it to the mail queue.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: ID or key of the issue that the notification is sent for.</li>
    *   <li>payload: The request object for the notification and recipients.</li>
    * </ul>
    */
    public void Post2IssueByIssueIDOrKeyNotifyV1(Consumer<Post2IssueByIssueIDOrKeyNotifyV1OperationSpec> spec) {
        Post2IssueByIssueIDOrKeyNotifyV1OperationSpec r = new Post2IssueByIssueIDOrKeyNotifyV1OperationSpec(spec);
        api.Post2IssueByIssueIDOrKeyNotifyV1(r.issueIdOrKey(), r.payload());
    }

    /**
    * Get2IssueByIssueIDOrKeyTransitionsV1
    * Get transitions
    * Returns either all transitions or a transition that can be performed by the user on an issue, based on the issue's status.
    * 
    * Note, if a request is made for a transition that does not exist or cannot be performed on the issue, given its status, the response will return any empty transitions list.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required: A list or transition is returned only when the user has:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    * 
    * However, if the user does not have the *Transition issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) the response will not list any transitions.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about transitions in the response. This parameter accepts `transitions.fields`, which returns information about the fields in the transition screen for each transition. Fields hidden from the screen are not returned. Use this information to populate the `fields` and `update` fields in [Transition issue](#api-rest-api-2-issue-issueIdOrKey-transitions-post).</li>
    *   <li>transitionId: The ID of the transition.</li>
    *   <li>skipRemoteOnlyCondition: Whether transitions with the condition *Hide From User Condition* are included in the response.</li>
    *   <li>includeUnavailableTransitions: Whether details of transitions that fail a condition are included in the response</li>
    *   <li>sortByOpsBarAndStatus: Whether the transitions are sorted by ops-bar sequence value first then category order (Todo, In Progress, Done) or only by ops-bar sequence value.</li>
    * </ul>
    */
    public Transitions Get2IssueByIssueIDOrKeyTransitionsV1(Consumer<Get2IssueByIssueIDOrKeyTransitionsV1OperationSpec> spec) {
        Get2IssueByIssueIDOrKeyTransitionsV1OperationSpec r = new Get2IssueByIssueIDOrKeyTransitionsV1OperationSpec(spec);
        return api.Get2IssueByIssueIDOrKeyTransitionsV1(r.issueIdOrKey(), r.expand(), r.transitionId(), r.skipRemoteOnlyCondition(), r.includeUnavailableTransitions(), r.sortByOpsBarAndStatus());
    }

    /**
    * Post2IssueByIssueIDOrKeyTransitionsV1
    * Transition issue
    * Performs an issue transition and, if the transition has a screen, updates the fields from the transition screen.
    * 
    * sortByCategory To update the fields on the transition screen, specify the fields in the `fields` or `update` parameters in the request body. Get details about the fields using [ Get transitions](#api-rest-api-2-issue-issueIdOrKey-transitions-get) with the `transitions.fields` expand.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* and *Transition issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public void Post2IssueByIssueIDOrKeyTransitionsV1(Consumer<Post2IssueByIssueIDOrKeyTransitionsV1OperationSpec> spec) {
        Post2IssueByIssueIDOrKeyTransitionsV1OperationSpec r = new Post2IssueByIssueIDOrKeyTransitionsV1OperationSpec(spec);
        api.Post2IssueByIssueIDOrKeyTransitionsV1(r.issueIdOrKey(), r.payload());
    }

    /**
    * Put2IssuesArchiveExportV1
    * Export archived issue(s)
    * Enables admins to retrieve details of all archived issues. Upon a successful request, the admin who submitted it will receive an email with a link to download a CSV file with the issue details.
    * 
    * Note that this API only exports the values of system fields and archival-specific fields (`ArchivedBy` and `ArchivedDate`). Custom fields aren't supported.
    * 
    * **[Permissions](#permissions) required:** Jira admin or site admin: [global permission](https://confluence.atlassian.com/x/x4dKLg)
    * 
    * **License required:** Premium or Enterprise
    * 
    * **Signed-in users only:** This API can't be accessed anonymously.
    * 
    * **Rate limiting:** Only a single request can be active at any given time.
    * 
    *   
    * 
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: You can filter the issues in your request by the `projects`, `archivedBy`, `archivedDate`, `issueTypes`, and `reporters` fields. All filters are optional. If you don't provide any filters, you'll get a list of up to one million archived issues.</li>
    * </ul>
    */
    public void Put2IssuesArchiveExportV1(Consumer<Put2IssuesArchiveExportV1OperationSpec> spec) {
        Put2IssuesArchiveExportV1OperationSpec r = new Put2IssuesArchiveExportV1OperationSpec(spec);
        api.Put2IssuesArchiveExportV1(r.payload());
    }

}
