// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.ConnectModules;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * JiraRestClientDynamicModulesApi
 *
 * This resource represents [modules registered dynamically](https://developer.atlassian.com/cloud/jira/platform/dynamic-modules/)
 * by [Connect apps](https://developer.atlassian.com/cloud/jira/platform/index/#connect-apps).
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraRestClientDynamicModulesApi {

    /**
    * GetAtlassianConnect1AppModuleDynamicV1
    * Get modules
    * Returns all modules registered dynamically by the calling app.
    * 
    * **[Permissions](#permissions) required:** Only Connect apps can make this request.
    *
    */
    @RequestLine("GET /rest/atlassian-connect/1/app/module/dynamic")
    @Headers({
        "Accept: application/json"
    })
    ConnectModules GetAtlassianConnect1AppModuleDynamicV1();

    /**
    * PostAtlassianConnect1AppModuleDynamicV1
    * Register modules
    * Registers a list of modules.
    * 
    * **[Permissions](#permissions) required:** Only Connect apps can make this request.
    *
    * @param payload 
    */
    @RequestLine("POST /rest/atlassian-connect/1/app/module/dynamic")
    @Headers({
        "Content-Type: application/json"
    })
    void PostAtlassianConnect1AppModuleDynamicV1(
            @NotNull ConnectModules payload
    );

    /**
    * DeleteAtlassianConnect1AppModuleDynamicV1
    * Remove modules
    * Remove all or a list of modules registered by the calling app.
    * 
    * **[Permissions](#permissions) required:** Only Connect apps can make this request.
    *
    * @param moduleKey The key of the module to remove. To include multiple module keys, provide multiple copies of this parameter.
    * For example, `moduleKey=dynamic-attachment-entity-property&amp;moduleKey=dynamic-select-field`.
    * Nonexistent keys are ignored.
    */
    @RequestLine("DELETE /rest/atlassian-connect/1/app/module/dynamic?moduleKey={moduleKey}")
    void DeleteAtlassianConnect1AppModuleDynamicV1(
            @Nullable @Param("moduleKey") List<String> moduleKey
    );

}
