// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.AuditRecords;
import io.github.primelib.jira4j.rest.v2.operations.Get2AuditingRecordV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientAuditRecordsConsumerApi
 *
 * This resource represents audits that record activities undertaken in Jira. Use it to get a list of audit records.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientAuditRecordsConsumerApi {
    private final JiraRestClientAuditRecordsApi api;

    public JiraRestClientAuditRecordsConsumerApi(JiraRestClientAuditRecordsApi api) {
        this.api = api;
    }


    /**
    * Get2AuditingRecordV1
    * Get audit records
    * Returns a list of audit records. The list can be filtered to include items:
    * 
    *  *  where each item in `filter` has at least one match in any of these fields:
    *     
    *      *  `summary`
    *      *  `category`
    *      *  `eventSource`
    *      *  `objectItem.name` If the object is a user, account ID is available to filter.
    *      *  `objectItem.parentName`
    *      *  `objectItem.typeName`
    *      *  `changedValues.changedFrom`
    *      *  `changedValues.changedTo`
    *      *  `remoteAddress`
    *     
    *     For example, if `filter` contains *man ed*, an audit record containing `summary": "User added to group"` and `"category": "group management"` is returned.
    *  *  created on or after a date and time.
    *  *  created or or before a date and time.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>offset: The number of records to skip before returning the first result.</li>
    *   <li>limit: The maximum number of results to return.</li>
    *   <li>filter: The strings to match with audit field content, space separated.</li>
    *   <li>from: The date and time on or after which returned audit records must have been created. If `to` is provided `from` must be before `to` or no audit records are returned.</li>
    *   <li>to: The date and time on or before which returned audit results must have been created. If `from` is provided `to` must be after `from` or no audit records are returned.</li>
    * </ul>
    */
    public AuditRecords Get2AuditingRecordV1(Consumer<Get2AuditingRecordV1OperationSpec> spec) {
        Get2AuditingRecordV1OperationSpec r = new Get2AuditingRecordV1OperationSpec(spec);
        return api.Get2AuditingRecordV1(r.offset(), r.limit(), r.filter(), r.from(), r.to());
    }

}
