// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.IssueMatches;
import io.github.primelib.jira4j.rest.v2.models.IssuePickerSuggestions;
import io.github.primelib.jira4j.rest.v2.models.IssuesAndJqlqueries;
import io.github.primelib.jira4j.rest.v2.models.JqlcountRequestBean;
import io.github.primelib.jira4j.rest.v2.models.JqlcountResultsBean;
import io.github.primelib.jira4j.rest.v2.models.SearchAndReconcileRequestBean;
import io.github.primelib.jira4j.rest.v2.models.SearchAndReconcileResults;
import io.github.primelib.jira4j.rest.v2.models.SearchRequestBean;
import io.github.primelib.jira4j.rest.v2.models.SearchResults;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * JiraRestClientIssueSearchApi
 *
 * This resource represents various ways to search for issues. Use it to search for issues with a JQL query and find issues to populate an issue picker.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraRestClientIssueSearchApi {

    /**
    * Get2IssuePickerV1
    * Get issue picker suggestions
    * Returns lists of issues matching a query string. Use this resource to provide auto-completion suggestions when the user is looking for an issue using a word or string.
    * 
    * This operation returns two lists:
    * 
    *  *  `History Search` which includes issues from the user's history of created, edited, or viewed issues that contain the string in the `query` parameter.
    *  *  `Current Search` which includes issues that match the JQL expression in `currentJQL` and contain the string in the `query` parameter.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** None.
    *
    * @param query A string to match against text fields in the issue such as title, description, or comments.
    * @param currentJql A JQL query defining a list of issues to search for the query term. Note that `username` and `userkey` cannot be used as search terms for this parameter, due to privacy reasons. Use `accountId` instead.
    * @param currentIssueKey The key of an issue to exclude from search results. For example, the issue the user is viewing when they perform this query.
    * @param currentProjectId The ID of a project that suggested issues must belong to.
    * @param showSubTasks Indicate whether to include subtasks in the suggestions list.
    * @param showSubTaskParent When `currentIssueKey` is a subtask, whether to include the parent issue in the suggestions if it matches the query.
    */
    @RequestLine("GET /rest/api/2/issue/picker?query={query}&currentJql={currentJql}&currentIssueKey={currentIssueKey}&currentProjectId={currentProjectId}&showSubTasks={showSubTasks}&showSubTaskParent={showSubTaskParent}")
    @Headers({
        "Accept: application/json"
    })
    IssuePickerSuggestions Get2IssuePickerV1(
            @Nullable @Param("query") String query,
            @Nullable @Param("currentJql") String currentJql,
            @Nullable @Param("currentIssueKey") String currentIssueKey,
            @Nullable @Param("currentProjectId") String currentProjectId,
            @Nullable @Param("showSubTasks") Boolean showSubTasks,
            @Nullable @Param("showSubTaskParent") Boolean showSubTaskParent
    );

    /**
    * Post2JqlMatchV1
    * Check issues against JQL
    * Checks whether one or more issues would be returned by one or more JQL queries.
    * 
    * **[Permissions](#permissions) required:** None, however, issues are only matched against JQL queries where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param payload 
    */
    @RequestLine("POST /rest/api/2/jql/match")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    IssueMatches Post2JqlMatchV1(
            @NotNull IssuesAndJqlqueries payload
    );

    /**
    * Get2SearchV1
    * Currently being removed. Search for issues using JQL (GET)
    * Endpoint is currently being removed. [More details](https://developer.atlassian.com/changelog/#CHANGE-2046)
    * 
    * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ).
    * 
    * If the JQL query expression is too large to be encoded as a query parameter, use the [POST](#api-rest-api-2-search-post) version of this resource.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param jql The [JQL](https://confluence.atlassian.com/x/egORLQ) that defines the search. Note:
    * 
    *  *  If no JQL expression is provided, all issues are returned.
    *  *  `username` and `userkey` cannot be used as search terms due to privacy reasons. Use `accountId` instead.
    *  *  If a user has hidden their email address in their user profile, partial matches of the email address will not find the user. An exact match is required.
    * @param startAt The index of the first item to return in a page of results (page offset).
    * @param maxResults The maximum number of items to return per page. To manage page size, Jira may return fewer items per page where a large number of fields or properties are requested. The greatest number of items returned per page is achieved when requesting `id` or `key` only.
    * @param validateQuery Determines how to validate the JQL query and treat the validation results. Supported values are:
    * 
    *  *  `strict` Returns a 400 response code if any errors are found, along with a list of all errors (and warnings).
    *  *  `warn` Returns all errors as warnings.
    *  *  `none` No validation is performed.
    *  *  `true` *Deprecated* A legacy synonym for `strict`.
    *  *  `false` *Deprecated* A legacy synonym for `warn`.
    * 
    * Note: If the JQL is not correctly formed a 400 response code is returned, regardless of the `validateQuery` value.
    * @param fields A list of fields to return for each issue, use it to retrieve a subset of fields. This parameter accepts a comma-separated list. Expand options include:
    * 
    *  *  `*all` Returns all fields.
    *  *  `*navigable` Returns navigable fields.
    *  *  Any issue field, prefixed with a minus to exclude.
    * 
    * Examples:
    * 
    *  *  `summary,comment` Returns only the summary and comments fields.
    *  *  `-description` Returns all navigable (default) fields except description.
    *  *  `*all,-comment` Returns all fields except comments.
    * 
    * This parameter may be specified multiple times. For example, `fields=field1,field2&amp;fields=field3`.
    * 
    * Note: All navigable fields are returned by default. This differs from [GET issue](#api-rest-api-2-issue-issueIdOrKey-get) where the default is all fields.
    * @param expand Use [expand](#expansion) to include additional information about issues in the response. This parameter accepts a comma-separated list. Expand options include:
    * 
    *  *  `renderedFields` Returns field values rendered in HTML format.
    *  *  `names` Returns the display name of each field.
    *  *  `schema` Returns the schema describing a field type.
    *  *  `transitions` Returns all possible transitions for the issue.
    *  *  `operations` Returns all possible operations for the issue.
    *  *  `editmeta` Returns information about how each field can be edited.
    *  *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.
    *  *  `versionedRepresentations` Instead of `fields`, returns `versionedRepresentations` a JSON array containing each version of a field's value, with the highest numbered item representing the most recent version.
    * @param properties A list of issue property keys for issue properties to include in the results. This parameter accepts a comma-separated list. Multiple properties can also be provided using an ampersand separated list. For example, `properties=prop1,prop2&amp;properties=prop3`. A maximum of 5 issue property keys can be specified.
    * @param fieldsByKeys Reference fields by their key (rather than ID).
    * @param failFast Whether to fail the request quickly in case of an error while loading fields for an issue. For `failFast=true`, if one field fails, the entire operation fails. For `failFast=false`, the operation will continue even if a field fails. It will return a valid response, but without values for the failed field(s).
    * @deprecated
    */
    @RequestLine("GET /rest/api/2/search?jql={jql}&startAt={startAt}&maxResults={maxResults}&validateQuery={validateQuery}&fields={fields}&expand={expand}&properties={properties}&fieldsByKeys={fieldsByKeys}&failFast={failFast}")
    @Headers({
        "Accept: application/json"
    })
    @Deprecated
    SearchResults Get2SearchV1(
            @Nullable @Param("jql") String jql,
            @Nullable @Param("startAt") Integer startAt,
            @Nullable @Param("maxResults") Integer maxResults,
            @Nullable @Param("validateQuery") String validateQuery,
            @Nullable @Param("fields") List<String> fields,
            @Nullable @Param("expand") String expand,
            @Nullable @Param("properties") List<String> properties,
            @Nullable @Param("fieldsByKeys") Boolean fieldsByKeys,
            @Nullable @Param("failFast") Boolean failFast
    );

    /**
    * Post2SearchV1
    * Currently being removed. Search for issues using JQL (POST)
    * Endpoint is currently being removed. [More details](https://developer.atlassian.com/changelog/#CHANGE-2046)
    * 
    * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ).
    * 
    * There is a [GET](#api-rest-api-2-search-get) version of this resource that can be used for smaller JQL query expressions.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param payload A JSON object containing the search request.
    * @deprecated
    */
    @RequestLine("POST /rest/api/2/search")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    @Deprecated
    SearchResults Post2SearchV1(
            @NotNull SearchRequestBean payload
    );

    /**
    * Post2SearchApproximateCountV1
    * Count issues using JQL
    * Provide an estimated count of the issues that match the [JQL](https://confluence.atlassian.com/x/egORLQ). Recent updates might not be immediately visible in the returned output. This endpoint requires JQL to be bounded.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param payload A JSON object containing the search request.
    */
    @RequestLine("POST /rest/api/2/search/approximate-count")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    JqlcountResultsBean Post2SearchApproximateCountV1(
            @NotNull JqlcountRequestBean payload
    );

    /**
    * Get2SearchJqlV1
    * Search for issues using JQL enhanced search (GET)
    * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ). Recent updates might not be immediately visible in the returned search results. If you need [read-after-write](https://developer.atlassian.com/cloud/jira/platform/search-and-reconcile/) consistency, you can utilize the `reconcileIssues` parameter to ensure stronger consistency assurances. This operation can be accessed anonymously.
    * 
    * If the JQL query expression is too large to be encoded as a query parameter, use the [POST](#api-rest-api-2-search-post) version of this resource.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param jql A [JQL](https://confluence.atlassian.com/x/egORLQ) expression. For performance reasons, this parameter requires a bounded query. A bounded query is a query with a search restriction.
    * 
    *  *  Example of an unbounded query: `order by key desc`.
    *  *  Example of a bounded query: `assignee = currentUser() order by key`.
    * 
    * Additionally, `orderBy` clause can contain a maximum of 7 fields.
    * @param nextPageToken The token for a page to fetch that is not the first page. The first page has a `nextPageToken` of `null`. Use the `nextPageToken` to fetch the next page of issues.
    * 
    * Note: The `nextPageToken` field is **not included** in the response for the last page, indicating there is no next page.
    * @param maxResults The maximum number of items to return per page. To manage page size, API may return fewer items per page where a large number of fields or properties are requested. The greatest number of items returned per page is achieved when requesting `id` or `key` only. It returns max 5000 issues.
    * @param fields A list of fields to return for each issue, use it to retrieve a subset of fields. This parameter accepts a comma-separated list. Expand options include:
    * 
    *  *  `*all` Returns all fields.
    *  *  `*navigable` Returns navigable fields.
    *  *  `id` Returns only issue IDs.
    *  *  Any issue field, prefixed with a minus to exclude.
    * 
    * The default is `id`.
    * 
    * Examples:
    * 
    *  *  `summary,comment` Returns only the summary and comments fields only.
    *  *  `-description` Returns all navigable (default) fields except description.
    *  *  `*all,-comment` Returns all fields except comments.
    * 
    * Multiple `fields` parameters can be included in a request.
    * 
    * Note: By default, this resource returns IDs only. This differs from [GET issue](#api-rest-api-2-issue-issueIdOrKey-get) where the default is all fields.
    * @param expand Use [expand](#expansion) to include additional information about issues in the response. Note that, unlike the majority of instances where `expand` is specified, `expand` is defined as a comma-delimited string of values. The expand options are:
    * 
    *  *  `renderedFields` Returns field values rendered in HTML format.
    *  *  `names` Returns the display name of each field.
    *  *  `schema` Returns the schema describing a field type.
    *  *  `transitions` Returns all possible transitions for the issue.
    *  *  `operations` Returns all possible operations for the issue.
    *  *  `editmeta` Returns information about how each field can be edited.
    *  *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.
    *  *  `versionedRepresentations` Instead of `fields`, returns `versionedRepresentations` a JSON array containing each version of a field's value, with the highest numbered item representing the most recent version.
    * 
    * Examples: `"names,changelog"` Returns the display name of each field as well as a list of recent updates to an issue.
    * @param properties A list of up to 5 issue properties to include in the results. This parameter accepts a comma-separated list.
    * @param fieldsByKeys Reference fields by their key (rather than ID). The default is `false`.
    * @param failFast Fail this request early if we can't retrieve all field data.
    * @param reconcileIssues Strong consistency issue ids to be reconciled with search results. Accepts max 50 ids
    */
    @RequestLine("GET /rest/api/2/search/jql?jql={jql}&nextPageToken={nextPageToken}&maxResults={maxResults}&fields={fields}&expand={expand}&properties={properties}&fieldsByKeys={fieldsByKeys}&failFast={failFast}&reconcileIssues={reconcileIssues}")
    @Headers({
        "Accept: application/json"
    })
    SearchAndReconcileResults Get2SearchJqlV1(
            @Nullable @Param("jql") String jql,
            @Nullable @Param("nextPageToken") String nextPageToken,
            @Nullable @Param("maxResults") Integer maxResults,
            @Nullable @Param("fields") List<String> fields,
            @Nullable @Param("expand") String expand,
            @Nullable @Param("properties") List<String> properties,
            @Nullable @Param("fieldsByKeys") Boolean fieldsByKeys,
            @Nullable @Param("failFast") Boolean failFast,
            @Nullable @Param("reconcileIssues") List<Long> reconcileIssues
    );

    /**
    * Post2SearchJqlV1
    * Search for issues using JQL enhanced search (POST)
    * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ). Recent updates might not be immediately visible in the returned search results. If you need [read-after-write](https://developer.atlassian.com/cloud/jira/platform/search-and-reconcile/) consistency, you can utilize the `reconcileIssues` parameter to ensure stronger consistency assurances. This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param payload 
    */
    @RequestLine("POST /rest/api/2/search/jql")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    SearchAndReconcileResults Post2SearchJqlV1(
            @NotNull SearchAndReconcileRequestBean payload
    );

}
