// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.ServiceRegistry;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * JiraRestClientServiceRegistryApi
 *
 * This resource represents a service registry. Use it to retrieve attributes related to a [service registry](https://support.atlassian.com/jira-service-management-cloud/docs/what-is-services/) in JSM.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraRestClientServiceRegistryApi {

    /**
    * GetAtlassianConnect1ServiceRegistryV1
    * Retrieve the attributes of service registries
    * Retrieve the attributes of given service registries.
    * 
    * **[Permissions](#permissions) required:** Only Connect apps can make this request and the servicesIds belong to the tenant you are requesting
    *
    * @param serviceIds The ID of the services (the strings starting with "b:" need to be decoded in Base64).
    */
    @RequestLine("GET /rest/atlassian-connect/1/service-registry?serviceIds={serviceIds}")
    @Headers({
        "Accept: application/json"
    })
    List<ServiceRegistry> GetAtlassianConnect1ServiceRegistryV1(
            @NotNull @Param("serviceIds") List<String> serviceIds
    );

}
