// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.License;
import io.github.primelib.jira4j.rest.v2.models.LicenseMetric;
import io.github.primelib.jira4j.rest.v2.operations.Get2InstanceLicenseV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2LicenseApproximateLicenseCountProductByApplicationKeyV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2LicenseApproximateLicenseCountV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientLicenseMetricsConsumerApi
 *
 * This resource represents license metrics. Use it to get available metrics for Jira licences.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientLicenseMetricsConsumerApi {
    private final JiraRestClientLicenseMetricsApi api;

    public JiraRestClientLicenseMetricsConsumerApi(JiraRestClientLicenseMetricsApi api) {
        this.api = api;
    }


    /**
    * Get2InstanceLicenseV1
    * Get license
    * Returns licensing information about the Jira instance.
    * 
    * **[Permissions](#permissions) required:** None.
    *
    */
    public License Get2InstanceLicenseV1(Consumer<Get2InstanceLicenseV1OperationSpec> spec) {
        Get2InstanceLicenseV1OperationSpec r = new Get2InstanceLicenseV1OperationSpec(spec);
        return api.Get2InstanceLicenseV1();
    }

    /**
    * Get2LicenseApproximateLicenseCountV1
    * Get approximate license count
    * Returns the approximate number of user accounts across all Jira licenses. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    */
    public LicenseMetric Get2LicenseApproximateLicenseCountV1(Consumer<Get2LicenseApproximateLicenseCountV1OperationSpec> spec) {
        Get2LicenseApproximateLicenseCountV1OperationSpec r = new Get2LicenseApproximateLicenseCountV1OperationSpec(spec);
        return api.Get2LicenseApproximateLicenseCountV1();
    }

    /**
    * Get2LicenseApproximateLicenseCountProductByApplicationKeyV1
    * Get approximate application license count
    * Returns the total approximate number of user accounts for a single Jira license. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>applicationKey: The ID of the application, represents a specific version of Jira.</li>
    * </ul>
    */
    public LicenseMetric Get2LicenseApproximateLicenseCountProductByApplicationKeyV1(Consumer<Get2LicenseApproximateLicenseCountProductByApplicationKeyV1OperationSpec> spec) {
        Get2LicenseApproximateLicenseCountProductByApplicationKeyV1OperationSpec r = new Get2LicenseApproximateLicenseCountProductByApplicationKeyV1OperationSpec(spec);
        return api.Get2LicenseApproximateLicenseCountProductByApplicationKeyV1(r.applicationKey());
    }

}
