// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.PermissionGrants;
import io.github.primelib.jira4j.rest.v2.models.PermissionSchemes;
import io.github.primelib.jira4j.rest.v2.operations.Delete2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Delete2PermissionschemeBySchemeIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2PermissionschemeBySchemeIDPermissionV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2PermissionschemeBySchemeIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2PermissionschemeV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2PermissionschemeBySchemeIDPermissionV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2PermissionschemeV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2PermissionschemeBySchemeIDV1OperationSpec;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientPermissionSchemesConsumerApi
 *
 * This resource represents permission schemes. Use it to get, create, update, and delete permission schemes as well as get, create, update, and delete details of the permissions granted in those schemes.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientPermissionSchemesConsumerApi {
    private final JiraRestClientPermissionSchemesApi api;

    public JiraRestClientPermissionSchemesConsumerApi(JiraRestClientPermissionSchemesApi api) {
        this.api = api;
    }


    /**
    * Get2PermissionschemeV1
    * Get all permission schemes
    * Returns all permission schemes.
    * 
    * ### About permission schemes and grants ###
    * 
    * A permission scheme is a collection of permission grants. A permission grant consists of a `holder` and a `permission`.
    * 
    * #### Holder object ####
    * 
    * The `holder` object contains information about the user or group being granted the permission. For example, the *Administer projects* permission is granted to a group named *Teams in space administrators*. In this case, the type is `"type": "group"`, and the parameter is the group name, `"parameter": "Teams in space administrators"` and the value is group ID, `"value": "ca85fac0-d974-40ca-a615-7af99c48d24f"`.
    * 
    * The `holder` object is defined by the following properties:
    * 
    *  *  `type` Identifies the user or group (see the list of types below).
    *  *  `parameter` As a group's name can change, use of `value` is recommended. The value of this property depends on the `type`. For example, if the `type` is a group, then you need to specify the group name.
    *  *  `value` The value of this property depends on the `type`. If the `type` is a group, then you need to specify the group ID. For other `type` it has the same value as `parameter`
    * 
    * The following `types` are available. The expected values for `parameter` and `value` are given in parentheses (some types may not have a `parameter` or `value`):
    * 
    *  *  `anyone` Grant for anonymous users.
    *  *  `applicationRole` Grant for users with access to the specified application (application name, application name). See [Update product access settings](https://confluence.atlassian.com/x/3YxjL) for more information.
    *  *  `assignee` Grant for the user currently assigned to an issue.
    *  *  `group` Grant for the specified group (`parameter` : group name, `value` : group ID).
    *  *  `groupCustomField` Grant for a user in the group selected in the specified custom field (`parameter` : custom field ID, `value` : custom field ID).
    *  *  `projectLead` Grant for a project lead.
    *  *  `projectRole` Grant for the specified project role (`parameter` :project role ID, `value` : project role ID).
    *  *  `reporter` Grant for the user who reported the issue.
    *  *  `sd.customer.portal.only` Jira Service Desk only. Grants customers permission to access the customer portal but not Jira. See [Customizing Jira Service Desk permissions](https://confluence.atlassian.com/x/24dKLg) for more information.
    *  *  `user` Grant for the specified user (`parameter` : user ID - historically this was the userkey but that is deprecated and the account ID should be used, `value` : user ID).
    *  *  `userCustomField` Grant for a user selected in the specified custom field (`parameter` : custom field ID, `value` : custom field ID).
    * 
    * #### Built-in permissions ####
    * 
    * The [built-in Jira permissions](https://confluence.atlassian.com/x/yodKLg) are listed below. Apps can also define custom permissions. See the [project permission](https://developer.atlassian.com/cloud/jira/platform/modules/project-permission/) and [global permission](https://developer.atlassian.com/cloud/jira/platform/modules/global-permission/) module documentation for more information.
    * 
    * **Administration permissions**
    * 
    *  *  `ADMINISTER_PROJECTS`
    *  *  `EDIT_WORKFLOW`
    *  *  `EDIT_ISSUE_LAYOUT`
    * 
    * **Project permissions**
    * 
    *  *  `BROWSE_PROJECTS`
    *  *  `MANAGE_SPRINTS_PERMISSION` (Jira Software only)
    *  *  `SERVICEDESK_AGENT` (Jira Service Desk only)
    *  *  `VIEW_DEV_TOOLS` (Jira Software only)
    *  *  `VIEW_READONLY_WORKFLOW`
    * 
    * **Issue permissions**
    * 
    *  *  `ASSIGNABLE_USER`
    *  *  `ASSIGN_ISSUES`
    *  *  `CLOSE_ISSUES`
    *  *  `CREATE_ISSUES`
    *  *  `DELETE_ISSUES`
    *  *  `EDIT_ISSUES`
    *  *  `LINK_ISSUES`
    *  *  `MODIFY_REPORTER`
    *  *  `MOVE_ISSUES`
    *  *  `RESOLVE_ISSUES`
    *  *  `SCHEDULE_ISSUES`
    *  *  `SET_ISSUE_SECURITY`
    *  *  `TRANSITION_ISSUES`
    * 
    * **Voters and watchers permissions**
    * 
    *  *  `MANAGE_WATCHERS`
    *  *  `VIEW_VOTERS_AND_WATCHERS`
    * 
    * **Comments permissions**
    * 
    *  *  `ADD_COMMENTS`
    *  *  `DELETE_ALL_COMMENTS`
    *  *  `DELETE_OWN_COMMENTS`
    *  *  `EDIT_ALL_COMMENTS`
    *  *  `EDIT_OWN_COMMENTS`
    * 
    * **Attachments permissions**
    * 
    *  *  `CREATE_ATTACHMENTS`
    *  *  `DELETE_ALL_ATTACHMENTS`
    *  *  `DELETE_OWN_ATTACHMENTS`
    * 
    * **Time tracking permissions**
    * 
    *  *  `DELETE_ALL_WORKLOGS`
    *  *  `DELETE_OWN_WORKLOGS`
    *  *  `EDIT_ALL_WORKLOGS`
    *  *  `EDIT_OWN_WORKLOGS`
    *  *  `WORK_ON_ISSUES`
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>expand: Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are included when you specify any value. Expand options include:   *  `all` Returns all expandable information.  *  `field` Returns information about the custom field granted the permission.  *  `group` Returns information about the group that is granted the permission.  *  `permissions` Returns all permission grants for each permission scheme.  *  `projectRole` Returns information about the project role granted the permission.  *  `user` Returns information about the user who is granted the permission.</li>
    * </ul>
    */
    public PermissionSchemes Get2PermissionschemeV1(Consumer<Get2PermissionschemeV1OperationSpec> spec) {
        Get2PermissionschemeV1OperationSpec r = new Get2PermissionschemeV1OperationSpec(spec);
        return api.Get2PermissionschemeV1(r.expand());
    }

    /**
    * Post2PermissionschemeV1
    * Create permission scheme
    * Creates a new permission scheme. You can create a permission scheme with or without defining a set of permission grants.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>expand: Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are always included when you specify any value. Expand options include:   *  `all` Returns all expandable information.  *  `field` Returns information about the custom field granted the permission.  *  `group` Returns information about the group that is granted the permission.  *  `permissions` Returns all permission grants for each permission scheme.  *  `projectRole` Returns information about the project role granted the permission.  *  `user` Returns information about the user who is granted the permission.</li>
    *   <li>payload: The permission scheme to create.</li>
    * </ul>
    */
    public Map<String, Object> Post2PermissionschemeV1(Consumer<Post2PermissionschemeV1OperationSpec> spec) {
        Post2PermissionschemeV1OperationSpec r = new Post2PermissionschemeV1OperationSpec(spec);
        return api.Post2PermissionschemeV1(r.expand(), r.payload());
    }

    /**
    * Get2PermissionschemeBySchemeIDV1
    * Get permission scheme
    * Returns a permission scheme.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>schemeId: The ID of the permission scheme to return.</li>
    *   <li>expand: Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are included when you specify any value. Expand options include:   *  `all` Returns all expandable information.  *  `field` Returns information about the custom field granted the permission.  *  `group` Returns information about the group that is granted the permission.  *  `permissions` Returns all permission grants for each permission scheme.  *  `projectRole` Returns information about the project role granted the permission.  *  `user` Returns information about the user who is granted the permission.</li>
    * </ul>
    */
    public Map<String, Object> Get2PermissionschemeBySchemeIDV1(Consumer<Get2PermissionschemeBySchemeIDV1OperationSpec> spec) {
        Get2PermissionschemeBySchemeIDV1OperationSpec r = new Get2PermissionschemeBySchemeIDV1OperationSpec(spec);
        return api.Get2PermissionschemeBySchemeIDV1(r.schemeId(), r.expand());
    }

    /**
    * Put2PermissionschemeBySchemeIDV1
    * Update permission scheme
    * Updates a permission scheme. Below are some important things to note when using this resource:
    * 
    *  *  If a permissions list is present in the request, then it is set in the permission scheme, overwriting *all existing* grants.
    *  *  If you want to update only the name and description, then do not send a permissions list in the request.
    *  *  Sending an empty list will remove all permission grants from the permission scheme.
    * 
    * If you want to add or delete a permission grant instead of updating the whole list, see [Create permission grant](#api-rest-api-2-permissionscheme-schemeId-permission-post) or [Delete permission scheme entity](#api-rest-api-2-permissionscheme-schemeId-permission-permissionId-delete).
    * 
    * See [About permission schemes and grants](../api-group-permission-schemes/#about-permission-schemes-and-grants) for more details.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>schemeId: The ID of the permission scheme to update.</li>
    *   <li>expand: Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are always included when you specify any value. Expand options include:   *  `all` Returns all expandable information.  *  `field` Returns information about the custom field granted the permission.  *  `group` Returns information about the group that is granted the permission.  *  `permissions` Returns all permission grants for each permission scheme.  *  `projectRole` Returns information about the project role granted the permission.  *  `user` Returns information about the user who is granted the permission.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public Map<String, Object> Put2PermissionschemeBySchemeIDV1(Consumer<Put2PermissionschemeBySchemeIDV1OperationSpec> spec) {
        Put2PermissionschemeBySchemeIDV1OperationSpec r = new Put2PermissionschemeBySchemeIDV1OperationSpec(spec);
        return api.Put2PermissionschemeBySchemeIDV1(r.schemeId(), r.expand(), r.payload());
    }

    /**
    * Delete2PermissionschemeBySchemeIDV1
    * Delete permission scheme
    * Deletes a permission scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>schemeId: The ID of the permission scheme being deleted.</li>
    * </ul>
    */
    public void Delete2PermissionschemeBySchemeIDV1(Consumer<Delete2PermissionschemeBySchemeIDV1OperationSpec> spec) {
        Delete2PermissionschemeBySchemeIDV1OperationSpec r = new Delete2PermissionschemeBySchemeIDV1OperationSpec(spec);
        api.Delete2PermissionschemeBySchemeIDV1(r.schemeId());
    }

    /**
    * Get2PermissionschemeBySchemeIDPermissionV1
    * Get permission scheme grants
    * Returns all permission grants for a permission scheme.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>schemeId: The ID of the permission scheme.</li>
    *   <li>expand: Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are always included when you specify any value. Expand options include:   *  `permissions` Returns all permission grants for each permission scheme.  *  `user` Returns information about the user who is granted the permission.  *  `group` Returns information about the group that is granted the permission.  *  `projectRole` Returns information about the project role granted the permission.  *  `field` Returns information about the custom field granted the permission.  *  `all` Returns all expandable information.</li>
    * </ul>
    */
    public PermissionGrants Get2PermissionschemeBySchemeIDPermissionV1(Consumer<Get2PermissionschemeBySchemeIDPermissionV1OperationSpec> spec) {
        Get2PermissionschemeBySchemeIDPermissionV1OperationSpec r = new Get2PermissionschemeBySchemeIDPermissionV1OperationSpec(spec);
        return api.Get2PermissionschemeBySchemeIDPermissionV1(r.schemeId(), r.expand());
    }

    /**
    * Post2PermissionschemeBySchemeIDPermissionV1
    * Create permission grant
    * Creates a permission grant in a permission scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>schemeId: The ID of the permission scheme in which to create a new permission grant.</li>
    *   <li>expand: Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are always included when you specify any value. Expand options include:   *  `permissions` Returns all permission grants for each permission scheme.  *  `user` Returns information about the user who is granted the permission.  *  `group` Returns information about the group that is granted the permission.  *  `projectRole` Returns information about the project role granted the permission.  *  `field` Returns information about the custom field granted the permission.  *  `all` Returns all expandable information.</li>
    *   <li>payload: The permission grant to create.</li>
    * </ul>
    */
    public Map<String, Object> Post2PermissionschemeBySchemeIDPermissionV1(Consumer<Post2PermissionschemeBySchemeIDPermissionV1OperationSpec> spec) {
        Post2PermissionschemeBySchemeIDPermissionV1OperationSpec r = new Post2PermissionschemeBySchemeIDPermissionV1OperationSpec(spec);
        return api.Post2PermissionschemeBySchemeIDPermissionV1(r.schemeId(), r.expand(), r.payload());
    }

    /**
    * Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1
    * Get permission scheme grant
    * Returns a permission grant.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>schemeId: The ID of the permission scheme.</li>
    *   <li>permissionId: The ID of the permission grant.</li>
    *   <li>expand: Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are always included when you specify any value. Expand options include:   *  `all` Returns all expandable information.  *  `field` Returns information about the custom field granted the permission.  *  `group` Returns information about the group that is granted the permission.  *  `permissions` Returns all permission grants for each permission scheme.  *  `projectRole` Returns information about the project role granted the permission.  *  `user` Returns information about the user who is granted the permission.</li>
    * </ul>
    */
    public Map<String, Object> Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1(Consumer<Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec> spec) {
        Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec r = new Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec(spec);
        return api.Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1(r.schemeId(), r.permissionId(), r.expand());
    }

    /**
    * Delete2PermissionschemeBySchemeIDPermissionByPermissionIDV1
    * Delete permission scheme grant
    * Deletes a permission grant from a permission scheme. See [About permission schemes and grants](../api-group-permission-schemes/#about-permission-schemes-and-grants) for more details.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>schemeId: The ID of the permission scheme to delete the permission grant from.</li>
    *   <li>permissionId: The ID of the permission grant to delete.</li>
    * </ul>
    */
    public void Delete2PermissionschemeBySchemeIDPermissionByPermissionIDV1(Consumer<Delete2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec> spec) {
        Delete2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec r = new Delete2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec(spec);
        api.Delete2PermissionschemeBySchemeIDPermissionByPermissionIDV1(r.schemeId(), r.permissionId());
    }

}
