// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.PageBeanComment;
import io.github.primelib.jira4j.rest.v2.operations.Delete2IssueByIssueIDOrKeyCommentByIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueByIssueIDOrKeyCommentByIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssueByIssueIDOrKeyCommentV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2CommentListV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssueByIssueIDOrKeyCommentV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssueByIssueIDOrKeyCommentByIDV1OperationSpec;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientIssueCommentsConsumerApi
 *
 * This resource represents issue comments. Use it to:
 * 
 *  *  get, create, update, and delete a comment from an issue.
 *  *  get all comments from issue.
 *  *  get a list of comments by comment ID.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientIssueCommentsConsumerApi {
    private final JiraRestClientIssueCommentsApi api;

    public JiraRestClientIssueCommentsConsumerApi(JiraRestClientIssueCommentsApi api) {
        this.api = api;
    }


    /**
    * Post2CommentListV1
    * Get comments by IDs
    * Returns a [paginated](#pagination) list of comments specified by a list of comment IDs.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Comments are returned where the user:
    * 
    *  *  has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>expand: Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts a comma-separated list. Expand options include:   *  `renderedBody` Returns the comment body rendered in HTML.  *  `properties` Returns the comment's properties.</li>
    *   <li>payload: The list of comment IDs.</li>
    * </ul>
    */
    public PageBeanComment Post2CommentListV1(Consumer<Post2CommentListV1OperationSpec> spec) {
        Post2CommentListV1OperationSpec r = new Post2CommentListV1OperationSpec(spec);
        return api.Post2CommentListV1(r.expand(), r.payload());
    }

    /**
    * Get2IssueByIssueIDOrKeyCommentV1
    * Get comments
    * Returns all comments for an issue.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Comments are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is role visibility is restricted to.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
    *   <li>maxResults: The maximum number of items to return per page.</li>
    *   <li>orderBy: [Order](#ordering) the results by a field. Accepts *created* to sort comments by their created date.</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.</li>
    * </ul>
    */
    public Map<String, Object> Get2IssueByIssueIDOrKeyCommentV1(Consumer<Get2IssueByIssueIDOrKeyCommentV1OperationSpec> spec) {
        Get2IssueByIssueIDOrKeyCommentV1OperationSpec r = new Get2IssueByIssueIDOrKeyCommentV1OperationSpec(spec);
        return api.Get2IssueByIssueIDOrKeyCommentV1(r.issueIdOrKey(), r.startAt(), r.maxResults(), r.orderBy(), r.expand());
    }

    /**
    * Post2IssueByIssueIDOrKeyCommentV1
    * Add comment
    * Adds a comment to an issue.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* and *Add comments* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public Map<String, Object> Post2IssueByIssueIDOrKeyCommentV1(Consumer<Post2IssueByIssueIDOrKeyCommentV1OperationSpec> spec) {
        Post2IssueByIssueIDOrKeyCommentV1OperationSpec r = new Post2IssueByIssueIDOrKeyCommentV1OperationSpec(spec);
        return api.Post2IssueByIssueIDOrKeyCommentV1(r.issueIdOrKey(), r.expand(), r.payload());
    }

    /**
    * Get2IssueByIssueIDOrKeyCommentByIDV1
    * Get comment
    * Returns a comment.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>id: The ID of the comment.</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.</li>
    * </ul>
    */
    public Map<String, Object> Get2IssueByIssueIDOrKeyCommentByIDV1(Consumer<Get2IssueByIssueIDOrKeyCommentByIDV1OperationSpec> spec) {
        Get2IssueByIssueIDOrKeyCommentByIDV1OperationSpec r = new Get2IssueByIssueIDOrKeyCommentByIDV1OperationSpec(spec);
        return api.Get2IssueByIssueIDOrKeyCommentByIDV1(r.issueIdOrKey(), r.id(), r.expand());
    }

    /**
    * Put2IssueByIssueIDOrKeyCommentByIDV1
    * Update comment
    * Updates a comment.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  *Edit all comments*[ project permission](https://confluence.atlassian.com/x/yodKLg) to update any comment or *Edit own comments* to update comment created by the user.
    *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
    * 
    * **WARNING:** Child comments inherit visibility from their parent comment. Attempting to update a child comment's visibility will result in a 400 (Bad Request) error.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>id: The ID of the comment.</li>
    *   <li>notifyUsers: Whether users are notified when a comment is updated.</li>
    *   <li>overrideEditableFlag: Whether screen security is overridden to enable uneditable fields to be edited. Available to Connect app users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).</li>
    *   <li>expand: Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public Map<String, Object> Put2IssueByIssueIDOrKeyCommentByIDV1(Consumer<Put2IssueByIssueIDOrKeyCommentByIDV1OperationSpec> spec) {
        Put2IssueByIssueIDOrKeyCommentByIDV1OperationSpec r = new Put2IssueByIssueIDOrKeyCommentByIDV1OperationSpec(spec);
        return api.Put2IssueByIssueIDOrKeyCommentByIDV1(r.issueIdOrKey(), r.id(), r.notifyUsers(), r.overrideEditableFlag(), r.expand(), r.payload());
    }

    /**
    * Delete2IssueByIssueIDOrKeyCommentByIDV1
    * Delete comment
    * Deletes a comment.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  *Delete all comments*[ project permission](https://confluence.atlassian.com/x/yodKLg) to delete any comment or *Delete own comments* to delete comment created by the user,
    *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>issueIdOrKey: The ID or key of the issue.</li>
    *   <li>id: The ID of the comment.</li>
    * </ul>
    */
    public void Delete2IssueByIssueIDOrKeyCommentByIDV1(Consumer<Delete2IssueByIssueIDOrKeyCommentByIDV1OperationSpec> spec) {
        Delete2IssueByIssueIDOrKeyCommentByIDV1OperationSpec r = new Delete2IssueByIssueIDOrKeyCommentByIDV1OperationSpec(spec);
        api.Delete2IssueByIssueIDOrKeyCommentByIDV1(r.issueIdOrKey(), r.id());
    }

}
