// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.TimeTrackingConfiguration;
import io.github.primelib.jira4j.rest.v2.models.TimeTrackingProvIDEr;
import io.github.primelib.jira4j.rest.v2.operations.Get2ConfigurationTimetrackingListV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2ConfigurationTimetrackingOptionsV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2ConfigurationTimetrackingV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2ConfigurationTimetrackingOptionsV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2ConfigurationTimetrackingV1OperationSpec;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientTimeTrackingConsumerApi
 *
 * This resource represents time tracking and time tracking providers. Use it to get and set the time tracking provider, get and set the time tracking options, and disable time tracking.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientTimeTrackingConsumerApi {
    private final JiraRestClientTimeTrackingApi api;

    public JiraRestClientTimeTrackingConsumerApi(JiraRestClientTimeTrackingApi api) {
        this.api = api;
    }


    /**
    * Get2ConfigurationTimetrackingV1
    * Get selected time tracking provider
    * Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then a successful but empty response is returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    */
    public TimeTrackingProvIDEr Get2ConfigurationTimetrackingV1(Consumer<Get2ConfigurationTimetrackingV1OperationSpec> spec) {
        Get2ConfigurationTimetrackingV1OperationSpec r = new Get2ConfigurationTimetrackingV1OperationSpec(spec);
        return api.Get2ConfigurationTimetrackingV1();
    }

    /**
    * Put2ConfigurationTimetrackingV1
    * Select time tracking provider
    * Selects a time tracking provider.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: </li>
    * </ul>
    */
    public void Put2ConfigurationTimetrackingV1(Consumer<Put2ConfigurationTimetrackingV1OperationSpec> spec) {
        Put2ConfigurationTimetrackingV1OperationSpec r = new Put2ConfigurationTimetrackingV1OperationSpec(spec);
        api.Put2ConfigurationTimetrackingV1(r.payload());
    }

    /**
    * Get2ConfigurationTimetrackingListV1
    * Get all time tracking providers
    * Returns all time tracking providers. By default, Jira only has one time tracking provider: *JIRA provided time tracking*. However, you can install other time tracking providers via apps from the Atlassian Marketplace. For more information on time tracking providers, see the documentation for the [ Time Tracking Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/) module.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    */
    public List<TimeTrackingProvIDEr> Get2ConfigurationTimetrackingListV1(Consumer<Get2ConfigurationTimetrackingListV1OperationSpec> spec) {
        Get2ConfigurationTimetrackingListV1OperationSpec r = new Get2ConfigurationTimetrackingListV1OperationSpec(spec);
        return api.Get2ConfigurationTimetrackingListV1();
    }

    /**
    * Get2ConfigurationTimetrackingOptionsV1
    * Get time tracking settings
    * Returns the time tracking settings. This includes settings such as the time format, default time unit, and others. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    */
    public TimeTrackingConfiguration Get2ConfigurationTimetrackingOptionsV1(Consumer<Get2ConfigurationTimetrackingOptionsV1OperationSpec> spec) {
        Get2ConfigurationTimetrackingOptionsV1OperationSpec r = new Get2ConfigurationTimetrackingOptionsV1OperationSpec(spec);
        return api.Get2ConfigurationTimetrackingOptionsV1();
    }

    /**
    * Put2ConfigurationTimetrackingOptionsV1
    * Set time tracking settings
    * Sets the time tracking settings.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: </li>
    * </ul>
    */
    public TimeTrackingConfiguration Put2ConfigurationTimetrackingOptionsV1(Consumer<Put2ConfigurationTimetrackingOptionsV1OperationSpec> spec) {
        Put2ConfigurationTimetrackingOptionsV1OperationSpec r = new Put2ConfigurationTimetrackingOptionsV1OperationSpec(spec);
        return api.Put2ConfigurationTimetrackingOptionsV1(r.payload());
    }

}
