// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.Locale;
import io.github.primelib.jira4j.rest.v2.models.User;
import io.github.primelib.jira4j.rest.v2.operations.Delete2MypreferencesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2MypreferencesLocaleV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2MypreferencesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2MyselfV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2MypreferencesLocaleV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2MypreferencesV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientMyselfConsumerApi
 *
 * This resource represents information about the current user, such as basic details, group membership, application roles, preferences, and locale. Use it to get, create, update, and delete (restore default) values of the user's preferences and locale.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientMyselfConsumerApi {
    private final JiraRestClientMyselfApi api;

    public JiraRestClientMyselfConsumerApi(JiraRestClientMyselfApi api) {
        this.api = api;
    }


    /**
    * Get2MypreferencesV1
    * Get preference
    * Returns the value of a preference of the current user.
    * 
    * Note that these keys are deprecated:
    * 
    *  *  *jira.user.locale* The locale of the user. By default this is not set and the user takes the locale of the instance.
    *  *  *jira.user.timezone* The time zone of the user. By default this is not set and the user takes the timezone of the instance.
    * 
    * These system preferences keys will be deprecated by 15/07/2024. You can still retrieve these keys, but it will not have any impact on Notification behaviour.
    * 
    *  *  *user.notifications.watcher* Whether the user gets notified when they are watcher.
    *  *  *user.notifications.assignee* Whether the user gets notified when they are assignee.
    *  *  *user.notifications.reporter* Whether the user gets notified when they are reporter.
    *  *  *user.notifications.mentions* Whether the user gets notified when they are mentions.
    * 
    * Use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API to manage timezone and locale instead.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>key: The key of the preference.</li>
    * </ul>
    */
    public String Get2MypreferencesV1(Consumer<Get2MypreferencesV1OperationSpec> spec) {
        Get2MypreferencesV1OperationSpec r = new Get2MypreferencesV1OperationSpec(spec);
        return api.Get2MypreferencesV1(r.key());
    }

    /**
    * Put2MypreferencesV1
    * Set preference
    * Creates a preference for the user or updates a preference's value by sending a plain text string. For example, `false`. An arbitrary preference can be created with the value containing up to 255 characters. In addition, the following keys define system preferences that can be set or created:
    * 
    *  *  *user.notifications.mimetype* The mime type used in notifications sent to the user. Defaults to `html`.
    *  *  *user.default.share.private* Whether new [ filters](https://confluence.atlassian.com/x/eQiiLQ) are set to private. Defaults to `true`.
    *  *  *user.keyboard.shortcuts.disabled* Whether keyboard shortcuts are disabled. Defaults to `false`.
    *  *  *user.autowatch.disabled* Whether the user automatically watches issues they create or add a comment to. By default, not set: the user takes the instance autowatch setting.
    *  *  *user.notifiy.own.changes* Whether the user gets notified of their own changes.
    * 
    * Note that these keys are deprecated:
    * 
    *  *  *jira.user.locale* The locale of the user. By default, not set. The user takes the instance locale.
    *  *  *jira.user.timezone* The time zone of the user. By default, not set. The user takes the instance timezone.
    * 
    * These system preferences keys will be deprecated by 15/07/2024. You can still use these keys to create arbitrary preferences, but it will not have any impact on Notification behaviour.
    * 
    *  *  *user.notifications.watcher* Whether the user gets notified when they are watcher.
    *  *  *user.notifications.assignee* Whether the user gets notified when they are assignee.
    *  *  *user.notifications.reporter* Whether the user gets notified when they are reporter.
    *  *  *user.notifications.mentions* Whether the user gets notified when they are mentions.
    * 
    * Use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API to manage timezone and locale instead.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>key: The key of the preference. The maximum length is 255 characters.</li>
    *   <li>payload: The value of the preference as a plain text string. The maximum length is 255 characters.</li>
    * </ul>
    */
    public void Put2MypreferencesV1(Consumer<Put2MypreferencesV1OperationSpec> spec) {
        Put2MypreferencesV1OperationSpec r = new Put2MypreferencesV1OperationSpec(spec);
        api.Put2MypreferencesV1(r.key(), r.payload());
    }

    /**
    * Delete2MypreferencesV1
    * Delete preference
    * Deletes a preference of the user, which restores the default value of system defined settings.
    * 
    * Note that these keys are deprecated:
    * 
    *  *  *jira.user.locale* The locale of the user. By default, not set. The user takes the instance locale.
    *  *  *jira.user.timezone* The time zone of the user. By default, not set. The user takes the instance timezone.
    * 
    * Use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API to manage timezone and locale instead.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>key: The key of the preference.</li>
    * </ul>
    */
    public void Delete2MypreferencesV1(Consumer<Delete2MypreferencesV1OperationSpec> spec) {
        Delete2MypreferencesV1OperationSpec r = new Delete2MypreferencesV1OperationSpec(spec);
        api.Delete2MypreferencesV1(r.key());
    }

    /**
    * Get2MypreferencesLocaleV1
    * Get locale
    * Returns the locale for the user.
    * 
    * If the user has no language preference set (which is the default setting) or this resource is accessed anonymous, the browser locale detected by Jira is returned. Jira detects the browser locale using the *Accept-Language* header in the request. However, if this doesn't match a locale available Jira, the site default locale is returned.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** None.
    *
    */
    public Locale Get2MypreferencesLocaleV1(Consumer<Get2MypreferencesLocaleV1OperationSpec> spec) {
        Get2MypreferencesLocaleV1OperationSpec r = new Get2MypreferencesLocaleV1OperationSpec(spec);
        return api.Get2MypreferencesLocaleV1();
    }

    /**
    * Put2MypreferencesLocaleV1
    * Set locale
    * Deprecated, use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API instead.
    * 
    * Sets the locale of the user. The locale must be one supported by the instance of Jira.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>payload: The locale defined in a LocaleBean.</li>
    * </ul>
    * @deprecated
    */
    @Deprecated
    public void Put2MypreferencesLocaleV1(Consumer<Put2MypreferencesLocaleV1OperationSpec> spec) {
        Put2MypreferencesLocaleV1OperationSpec r = new Put2MypreferencesLocaleV1OperationSpec(spec);
        api.Put2MypreferencesLocaleV1(r.payload());
    }

    /**
    * Get2MyselfV1
    * Get current user
    * Returns details for the current user.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>expand: Use [expand](#expansion) to include additional information about user in the response. This parameter accepts a comma-separated list. Expand options include:   *  `groups` Returns all groups, including nested groups, the user belongs to.  *  `applicationRoles` Returns the application roles the user is assigned to.</li>
    * </ul>
    */
    public User Get2MyselfV1(Consumer<Get2MyselfV1OperationSpec> spec) {
        Get2MyselfV1OperationSpec r = new Get2MyselfV1OperationSpec(spec);
        return api.Get2MyselfV1(r.expand());
    }

}
