// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.operations.Delete2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientWorkflowTransitionPropertiesConsumerApi
 *
 * This resource represents workflow transition properties, which provides for storing custom data against a workflow transition. Use it to get, create, and delete workflow transition properties as well as get a list of property keys for a workflow transition. Workflow transition properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientWorkflowTransitionPropertiesConsumerApi {
    private final JiraRestClientWorkflowTransitionPropertiesApi api;

    public JiraRestClientWorkflowTransitionPropertiesConsumerApi(JiraRestClientWorkflowTransitionPropertiesApi api) {
        this.api = api;
    }


    /**
    * Get2WorkflowTransitionByTransitionIDPropertiesV1
    * Get workflow transition properties
    * This will be removed on [June 1, 2026](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-2570); fetch transition properties from [Bulk get workflows](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflows/#api-rest-api-3-workflows-post) instead.
    * 
    * Returns the properties on a workflow transition. Transition properties are used to change the behavior of a transition. For more information, see [Transition properties](https://confluence.atlassian.com/x/zIhKLg#Advancedworkflowconfiguration-transitionproperties) and [Workflow properties](https://confluence.atlassian.com/x/JYlKLg).
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>transitionId: The ID of the transition. To get the ID, view the workflow in text mode in the Jira administration console. The ID is shown next to the transition.</li>
    *   <li>includeReservedKeys: Some properties with keys that have the *jira.* prefix are reserved, which means they are not editable. To include these properties in the results, set this parameter to *true*.</li>
    *   <li>key: The key of the property being returned, also known as the name of the property. If this parameter is not specified, all properties on the transition are returned.</li>
    *   <li>workflowName: The name of the workflow that the transition belongs to.</li>
    *   <li>workflowMode: The workflow status. Set to *live* for active and inactive workflows, or *draft* for draft workflows.</li>
    * </ul>
    * @deprecated
    */
    @Deprecated
    public Map<String, Object> Get2WorkflowTransitionByTransitionIDPropertiesV1(Consumer<Get2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec> spec) {
        Get2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec r = new Get2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec(spec);
        return api.Get2WorkflowTransitionByTransitionIDPropertiesV1(r.transitionId(), r.includeReservedKeys(), r.key(), r.workflowName(), r.workflowMode());
    }

    /**
    * Put2WorkflowTransitionByTransitionIDPropertiesV1
    * Update workflow transition property
    * This will be removed on [June 1, 2026](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-2570); update transition properties using [Bulk update workflows](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflows/#api-rest-api-3-workflows-update-post) instead.
    * 
    * Updates a workflow transition by changing the property value. Trying to update a property that does not exist results in a new property being added to the transition. Transition properties are used to change the behavior of a transition. For more information, see [Transition properties](https://confluence.atlassian.com/x/zIhKLg#Advancedworkflowconfiguration-transitionproperties) and [Workflow properties](https://confluence.atlassian.com/x/JYlKLg).
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>transitionId: The ID of the transition. To get the ID, view the workflow in text mode in the Jira admin settings. The ID is shown next to the transition.</li>
    *   <li>key: The key of the property being updated, also known as the name of the property. Set this to the same value as the `key` defined in the request body.</li>
    *   <li>workflowName: The name of the workflow that the transition belongs to.</li>
    *   <li>workflowMode: The workflow status. Set to `live` for inactive workflows or `draft` for draft workflows. Active workflows cannot be edited.</li>
    *   <li>payload: </li>
    * </ul>
    * @deprecated
    */
    @Deprecated
    public Map<String, Object> Put2WorkflowTransitionByTransitionIDPropertiesV1(Consumer<Put2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec> spec) {
        Put2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec r = new Put2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec(spec);
        return api.Put2WorkflowTransitionByTransitionIDPropertiesV1(r.transitionId(), r.key(), r.workflowName(), r.workflowMode(), r.payload());
    }

    /**
    * Post2WorkflowTransitionByTransitionIDPropertiesV1
    * Create workflow transition property
    * This will be removed on [June 1, 2026](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-2570); add transition properties using [Bulk update workflows](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflows/#api-rest-api-3-workflows-update-post) instead.
    * 
    * Adds a property to a workflow transition. Transition properties are used to change the behavior of a transition. For more information, see [Transition properties](https://confluence.atlassian.com/x/zIhKLg#Advancedworkflowconfiguration-transitionproperties) and [Workflow properties](https://confluence.atlassian.com/x/JYlKLg).
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>transitionId: The ID of the transition. To get the ID, view the workflow in text mode in the Jira admin settings. The ID is shown next to the transition.</li>
    *   <li>key: The key of the property being added, also known as the name of the property. Set this to the same value as the `key` defined in the request body.</li>
    *   <li>workflowName: The name of the workflow that the transition belongs to.</li>
    *   <li>workflowMode: The workflow status. Set to *live* for inactive workflows or *draft* for draft workflows. Active workflows cannot be edited.</li>
    *   <li>payload: </li>
    * </ul>
    * @deprecated
    */
    @Deprecated
    public Map<String, Object> Post2WorkflowTransitionByTransitionIDPropertiesV1(Consumer<Post2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec> spec) {
        Post2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec r = new Post2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec(spec);
        return api.Post2WorkflowTransitionByTransitionIDPropertiesV1(r.transitionId(), r.key(), r.workflowName(), r.workflowMode(), r.payload());
    }

    /**
    * Delete2WorkflowTransitionByTransitionIDPropertiesV1
    * Delete workflow transition property
    * This will be removed on [June 1, 2026](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-2570); delete transition properties using [Bulk update workflows](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflows/#api-rest-api-3-workflows-update-post) instead.
    * 
    * Deletes a property from a workflow transition. Transition properties are used to change the behavior of a transition. For more information, see [Transition properties](https://confluence.atlassian.com/x/zIhKLg#Advancedworkflowconfiguration-transitionproperties) and [Workflow properties](https://confluence.atlassian.com/x/JYlKLg).
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>transitionId: The ID of the transition. To get the ID, view the workflow in text mode in the Jira admin settings. The ID is shown next to the transition.</li>
    *   <li>key: The name of the transition property to delete, also known as the name of the property.</li>
    *   <li>workflowName: The name of the workflow that the transition belongs to.</li>
    *   <li>workflowMode: The workflow status. Set to `live` for inactive workflows or `draft` for draft workflows. Active workflows cannot be edited.</li>
    * </ul>
    * @deprecated
    */
    @Deprecated
    public void Delete2WorkflowTransitionByTransitionIDPropertiesV1(Consumer<Delete2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec> spec) {
        Delete2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec r = new Delete2WorkflowTransitionByTransitionIDPropertiesV1OperationSpec(spec);
        api.Delete2WorkflowTransitionByTransitionIDPropertiesV1(r.transitionId(), r.key(), r.workflowName(), r.workflowMode());
    }

}
