// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.ProjectCategory;
import io.github.primelib.jira4j.rest.v2.models.UpdatedProjectCategory;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * JiraRestClientProjectCategoriesApi
 *
 * This resource represents project categories. Use it to create, update, and delete project categories as well as obtain a list of all project categories and details of individual categories. For more information on managing project categories, see [Adding, assigning, and deleting project categories](https://confluence.atlassian.com/x/-A5WMg).
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraRestClientProjectCategoriesApi {

    /**
    * Get2ProjectCategoryV1
    * Get all project categories
    * Returns all project categories.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    */
    @RequestLine("GET /rest/api/2/projectCategory")
    @Headers({
        "Accept: application/json"
    })
    List<ProjectCategory> Get2ProjectCategoryV1();

    /**
    * Post2ProjectCategoryV1
    * Create project category
    * Creates a project category.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param payload 
    */
    @RequestLine("POST /rest/api/2/projectCategory")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    ProjectCategory Post2ProjectCategoryV1(
            @NotNull ProjectCategory payload
    );

    /**
    * Get2ProjectCategoryByIDV1
    * Get project category by ID
    * Returns a project category.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
    *
    * @param id The ID of the project category.
    */
    @RequestLine("GET /rest/api/2/projectCategory/{id}")
    @Headers({
        "Accept: application/json"
    })
    ProjectCategory Get2ProjectCategoryByIDV1(
            @NotNull @Param("id") Long id
    );

    /**
    * Put2ProjectCategoryByIDV1
    * Update project category
    * Updates a project category.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param id 
    * @param payload 
    */
    @RequestLine("PUT /rest/api/2/projectCategory/{id}")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    UpdatedProjectCategory Put2ProjectCategoryByIDV1(
            @NotNull @Param("id") Long id,
            @NotNull ProjectCategory payload
    );

    /**
    * Delete2ProjectCategoryByIDV1
    * Delete project category
    * Deletes a project category.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param id ID of the project category to delete.
    */
    @RequestLine("DELETE /rest/api/2/projectCategory/{id}")
    void Delete2ProjectCategoryByIDV1(
            @NotNull @Param("id") Long id
    );

}
