// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.IssueTypeIDS;
import io.github.primelib.jira4j.rest.v2.models.IssueTypeScreenSchemeDetails;
import io.github.primelib.jira4j.rest.v2.models.IssueTypeScreenSchemeId;
import io.github.primelib.jira4j.rest.v2.models.IssueTypeScreenSchemeMappingDetails;
import io.github.primelib.jira4j.rest.v2.models.IssueTypeScreenSchemeProjectAssociation;
import io.github.primelib.jira4j.rest.v2.models.IssueTypeScreenSchemeUpdateDetails;
import io.github.primelib.jira4j.rest.v2.models.PageBeanIssueTypeScreenScheme;
import io.github.primelib.jira4j.rest.v2.models.PageBeanIssueTypeScreenSchemeItem;
import io.github.primelib.jira4j.rest.v2.models.PageBeanIssueTypeScreenSchemesProjects;
import io.github.primelib.jira4j.rest.v2.models.PageBeanProjectDetails;
import io.github.primelib.jira4j.rest.v2.models.UpdateDefaultScreenScheme;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * JiraRestClientIssueTypeScreenSchemesApi
 *
 * This resource represents issue type screen schemes. Use it to:
 * 
 *  *  get issue type screen schemes and a list of the projects that use them.
 *  *  create issue type screen schemes.
 *  *  update issue type screen schemes.
 *  *  delete issue type screen schemes.
 *  *  associate issue type screen schemes with projects.
 *  *  append issue type to screen scheme mappings to issue type screen schemes.
 *  *  remove issue type to screen scheme mappings from issue type screen schemes.
 *  *  update default screen scheme of issue type screen scheme.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraRestClientIssueTypeScreenSchemesApi {

    /**
    * Get2IssuetypescreenschemeV1
    * Get issue type screen schemes
    * Returns a [paginated](#pagination) list of issue type screen schemes.
    * 
    * Only issue type screen schemes used in classic projects are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param startAt The index of the first item to return in a page of results (page offset).
    * @param maxResults The maximum number of items to return per page.
    * @param id The list of issue type screen scheme IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&amp;id=10001`.
    * @param queryString String used to perform a case-insensitive partial match with issue type screen scheme name.
    * @param orderBy [Order](#ordering) the results by a field:
    * 
    *  *  `name` Sorts by issue type screen scheme name.
    *  *  `id` Sorts by issue type screen scheme ID.
    * @param expand Use [expand](#expansion) to include additional information in the response. This parameter accepts `projects` that, for each issue type screen schemes, returns information about the projects the issue type screen scheme is assigned to.
    */
    @RequestLine("GET /rest/api/2/issuetypescreenscheme?startAt={startAt}&maxResults={maxResults}&id={id}&queryString={queryString}&orderBy={orderBy}&expand={expand}")
    @Headers({
        "Accept: application/json"
    })
    PageBeanIssueTypeScreenScheme Get2IssuetypescreenschemeV1(
            @Nullable @Param("startAt") Long startAt,
            @Nullable @Param("maxResults") Integer maxResults,
            @Nullable @Param("id") List<Long> id,
            @Nullable @Param("queryString") String queryString,
            @Nullable @Param("orderBy") String orderBy,
            @Nullable @Param("expand") String expand
    );

    /**
    * Post2IssuetypescreenschemeV1
    * Create issue type screen scheme
    * Creates an issue type screen scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param payload An issue type screen scheme bean.
    */
    @RequestLine("POST /rest/api/2/issuetypescreenscheme")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    IssueTypeScreenSchemeId Post2IssuetypescreenschemeV1(
            @NotNull IssueTypeScreenSchemeDetails payload
    );

    /**
    * Get2IssuetypescreenschemeMappingV1
    * Get issue type screen scheme items
    * Returns a [paginated](#pagination) list of issue type screen scheme items.
    * 
    * Only issue type screen schemes used in classic projects are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param startAt The index of the first item to return in a page of results (page offset).
    * @param maxResults The maximum number of items to return per page.
    * @param issueTypeScreenSchemeId The list of issue type screen scheme IDs. To include multiple issue type screen schemes, separate IDs with ampersand: `issueTypeScreenSchemeId=10000&amp;issueTypeScreenSchemeId=10001`.
    */
    @RequestLine("GET /rest/api/2/issuetypescreenscheme/mapping?startAt={startAt}&maxResults={maxResults}&issueTypeScreenSchemeId={issueTypeScreenSchemeId}")
    @Headers({
        "Accept: application/json"
    })
    PageBeanIssueTypeScreenSchemeItem Get2IssuetypescreenschemeMappingV1(
            @Nullable @Param("startAt") Long startAt,
            @Nullable @Param("maxResults") Integer maxResults,
            @Nullable @Param("issueTypeScreenSchemeId") List<Long> issueTypeScreenSchemeId
    );

    /**
    * Get2IssuetypescreenschemeProjectV1
    * Get issue type screen schemes for projects
    * Returns a [paginated](#pagination) list of issue type screen schemes and, for each issue type screen scheme, a list of the projects that use it.
    * 
    * Only issue type screen schemes used in classic projects are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param startAt The index of the first item to return in a page of results (page offset).
    * @param maxResults The maximum number of items to return per page.
    * @param projectId The list of project IDs. To include multiple projects, separate IDs with ampersand: `projectId=10000&amp;projectId=10001`.
    */
    @RequestLine("GET /rest/api/2/issuetypescreenscheme/project?startAt={startAt}&maxResults={maxResults}&projectId={projectId}")
    @Headers({
        "Accept: application/json"
    })
    PageBeanIssueTypeScreenSchemesProjects Get2IssuetypescreenschemeProjectV1(
            @Nullable @Param("startAt") Long startAt,
            @Nullable @Param("maxResults") Integer maxResults,
            @NotNull @Param("projectId") List<Long> projectId
    );

    /**
    * Put2IssuetypescreenschemeProjectV1
    * Assign issue type screen scheme to project
    * Assigns an issue type screen scheme to a project.
    * 
    * Issue type screen schemes can only be assigned to classic projects.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param payload 
    */
    @RequestLine("PUT /rest/api/2/issuetypescreenscheme/project")
    @Headers({
        "Content-Type: application/json"
    })
    void Put2IssuetypescreenschemeProjectV1(
            @NotNull IssueTypeScreenSchemeProjectAssociation payload
    );

    /**
    * Put2IssuetypescreenschemeByIssueTypeScreenSchemeIDV1
    * Update issue type screen scheme
    * Updates an issue type screen scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param issueTypeScreenSchemeId The ID of the issue type screen scheme.
    * @param payload The issue type screen scheme update details.
    */
    @RequestLine("PUT /rest/api/2/issuetypescreenscheme/{issueTypeScreenSchemeId}")
    @Headers({
        "Content-Type: application/json"
    })
    void Put2IssuetypescreenschemeByIssueTypeScreenSchemeIDV1(
            @NotNull @Param("issueTypeScreenSchemeId") String issueTypeScreenSchemeId,
            @NotNull IssueTypeScreenSchemeUpdateDetails payload
    );

    /**
    * Delete2IssuetypescreenschemeByIssueTypeScreenSchemeIDV1
    * Delete issue type screen scheme
    * Deletes an issue type screen scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param issueTypeScreenSchemeId The ID of the issue type screen scheme.
    */
    @RequestLine("DELETE /rest/api/2/issuetypescreenscheme/{issueTypeScreenSchemeId}")
    void Delete2IssuetypescreenschemeByIssueTypeScreenSchemeIDV1(
            @NotNull @Param("issueTypeScreenSchemeId") String issueTypeScreenSchemeId
    );

    /**
    * Put2IssuetypescreenschemeByIssueTypeScreenSchemeIDMappingV1
    * Append mappings to issue type screen scheme
    * Appends issue type to screen scheme mappings to an issue type screen scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param issueTypeScreenSchemeId The ID of the issue type screen scheme.
    * @param payload 
    */
    @RequestLine("PUT /rest/api/2/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping")
    @Headers({
        "Content-Type: application/json"
    })
    void Put2IssuetypescreenschemeByIssueTypeScreenSchemeIDMappingV1(
            @NotNull @Param("issueTypeScreenSchemeId") String issueTypeScreenSchemeId,
            @NotNull IssueTypeScreenSchemeMappingDetails payload
    );

    /**
    * Put2IssuetypescreenschemeByIssueTypeScreenSchemeIDMappingDefaultV1
    * Update issue type screen scheme default screen scheme
    * Updates the default screen scheme of an issue type screen scheme. The default screen scheme is used for all unmapped issue types.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param issueTypeScreenSchemeId The ID of the issue type screen scheme.
    * @param payload 
    */
    @RequestLine("PUT /rest/api/2/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping/default")
    @Headers({
        "Content-Type: application/json"
    })
    void Put2IssuetypescreenschemeByIssueTypeScreenSchemeIDMappingDefaultV1(
            @NotNull @Param("issueTypeScreenSchemeId") String issueTypeScreenSchemeId,
            @NotNull UpdateDefaultScreenScheme payload
    );

    /**
    * Post2IssuetypescreenschemeByIssueTypeScreenSchemeIDMappingRemoveV1
    * Remove mappings from issue type screen scheme
    * Removes issue type to screen scheme mappings from an issue type screen scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param issueTypeScreenSchemeId The ID of the issue type screen scheme.
    * @param payload 
    */
    @RequestLine("POST /rest/api/2/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping/remove")
    @Headers({
        "Content-Type: application/json"
    })
    void Post2IssuetypescreenschemeByIssueTypeScreenSchemeIDMappingRemoveV1(
            @NotNull @Param("issueTypeScreenSchemeId") String issueTypeScreenSchemeId,
            @NotNull IssueTypeIDS payload
    );

    /**
    * Get2IssuetypescreenschemeByIssueTypeScreenSchemeIDProjectV1
    * Get issue type screen scheme projects
    * Returns a [paginated](#pagination) list of projects associated with an issue type screen scheme.
    * 
    * Only company-managed projects associated with an issue type screen scheme are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param issueTypeScreenSchemeId The ID of the issue type screen scheme.
    * @param startAt The index of the first item to return in a page of results (page offset).
    * @param maxResults The maximum number of items to return per page.
    * @param query 
    */
    @RequestLine("GET /rest/api/2/issuetypescreenscheme/{issueTypeScreenSchemeId}/project?startAt={startAt}&maxResults={maxResults}&query={query}")
    @Headers({
        "Accept: application/json"
    })
    PageBeanProjectDetails Get2IssuetypescreenschemeByIssueTypeScreenSchemeIDProjectV1(
            @NotNull @Param("issueTypeScreenSchemeId") Long issueTypeScreenSchemeId,
            @Nullable @Param("startAt") Long startAt,
            @Nullable @Param("maxResults") Integer maxResults,
            @Nullable @Param("query") String query
    );

}
