// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.ScreenableField;
import io.github.primelib.jira4j.rest.v2.operations.Delete2ScreenByScreenIDTabByTabIDFieldByIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2ScreenByScreenIDTabByTabIDFieldByIDMoveV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraRestClientScreenTabFieldsConsumerApi
 *
 * This resource represents the screen tab fields used to record issue details. Use it to get, add, move, and remove fields from screen tabs.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraRestClientScreenTabFieldsConsumerApi {
    private final JiraRestClientScreenTabFieldsApi api;

    public JiraRestClientScreenTabFieldsConsumerApi(JiraRestClientScreenTabFieldsApi api) {
        this.api = api;
    }


    /**
    * Get2ScreenByScreenIDTabByTabIDFieldsV1
    * Get all screen tab fields
    * Returns all fields for a screen tab.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) when the project key is specified, providing that the screen is associated with the project through a Screen Scheme and Issue Type Screen Scheme.
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>screenId: The ID of the screen.</li>
    *   <li>tabId: The ID of the screen tab.</li>
    *   <li>projectKey: The key of the project.</li>
    * </ul>
    */
    public List<ScreenableField> Get2ScreenByScreenIDTabByTabIDFieldsV1(Consumer<Get2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec> spec) {
        Get2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec r = new Get2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec(spec);
        return api.Get2ScreenByScreenIDTabByTabIDFieldsV1(r.screenId(), r.tabId(), r.projectKey());
    }

    /**
    * Post2ScreenByScreenIDTabByTabIDFieldsV1
    * Add screen tab field
    * Adds a field to a screen tab.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>screenId: The ID of the screen.</li>
    *   <li>tabId: The ID of the screen tab.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public ScreenableField Post2ScreenByScreenIDTabByTabIDFieldsV1(Consumer<Post2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec> spec) {
        Post2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec r = new Post2ScreenByScreenIDTabByTabIDFieldsV1OperationSpec(spec);
        return api.Post2ScreenByScreenIDTabByTabIDFieldsV1(r.screenId(), r.tabId(), r.payload());
    }

    /**
    * Delete2ScreenByScreenIDTabByTabIDFieldByIDV1
    * Remove screen tab field
    * Removes a field from a screen tab.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>screenId: The ID of the screen.</li>
    *   <li>tabId: The ID of the screen tab.</li>
    *   <li>id: The ID of the field.</li>
    * </ul>
    */
    public void Delete2ScreenByScreenIDTabByTabIDFieldByIDV1(Consumer<Delete2ScreenByScreenIDTabByTabIDFieldByIDV1OperationSpec> spec) {
        Delete2ScreenByScreenIDTabByTabIDFieldByIDV1OperationSpec r = new Delete2ScreenByScreenIDTabByTabIDFieldByIDV1OperationSpec(spec);
        api.Delete2ScreenByScreenIDTabByTabIDFieldByIDV1(r.screenId(), r.tabId(), r.id());
    }

    /**
    * Post2ScreenByScreenIDTabByTabIDFieldByIDMoveV1
    * Move screen tab field
    * Moves a screen tab field.
    * 
    * If `after` and `position` are provided in the request, `position` is ignored.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>screenId: The ID of the screen.</li>
    *   <li>tabId: The ID of the screen tab.</li>
    *   <li>id: The ID of the field.</li>
    *   <li>payload: </li>
    * </ul>
    */
    public void Post2ScreenByScreenIDTabByTabIDFieldByIDMoveV1(Consumer<Post2ScreenByScreenIDTabByTabIDFieldByIDMoveV1OperationSpec> spec) {
        Post2ScreenByScreenIDTabByTabIDFieldByIDMoveV1OperationSpec r = new Post2ScreenByScreenIDTabByTabIDFieldByIDMoveV1OperationSpec(spec);
        api.Post2ScreenByScreenIDTabByTabIDFieldByIDMoveV1(r.screenId(), r.tabId(), r.id(), r.payload());
    }

}
