// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.PageBeanScreenScheme;
import io.github.primelib.jira4j.rest.v2.models.ScreenSchemeDetails;
import io.github.primelib.jira4j.rest.v2.models.ScreenSchemeId;
import io.github.primelib.jira4j.rest.v2.models.UpdateScreenSchemeDetails;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * JiraClientScreenSchemesApi
 *
 * This resource represents screen schemes in classic projects. Use it to get, create, update, and delete screen schemes.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraClientScreenSchemesApi {

    /**
     * Get2ScreenschemeV1
     * Get screen schemes
     * Returns a [paginated](#pagination) list of screen schemes.
    * 
    * Only screen schemes used in classic projects are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/screenscheme
     *
     * @param startAt The index of the first item to return in a page of results (page offset).
     * @param maxResults The maximum number of items to return per page.
     * @param id The list of screen scheme IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&amp;id=10001`.
     * @param expand Use [expand](#expansion) include additional information in the response. This parameter accepts `issueTypeScreenSchemes` that, for each screen schemes, returns information about the issue type screen scheme the screen scheme is assigned to.
     * @param queryString String used to perform a case-insensitive partial match with screen scheme name.
     * @param orderBy [Order](#ordering) the results by a field:
    * 
    *  *  `id` Sorts by screen scheme ID.
    *  *  `name` Sorts by screen scheme name.
     */
    @RequestLine("GET /rest/api/2/screenscheme?startAt={startAt}&maxResults={maxResults}&id={id}&expand={expand}&queryString={queryString}&orderBy={orderBy}")
    @Headers({
        "Accept: application/json"
    })
    PageBeanScreenScheme get2ScreenschemeV1(
            @Nullable @Param("startAt") Long startAt,
            @Nullable @Param("maxResults") Integer maxResults,
            @Nullable @Param("id") List<Long> id,
            @Nullable @Param("expand") String expand,
            @Nullable @Param("queryString") String queryString,
            @Nullable @Param("orderBy") String orderBy
    );

    /**
     * Post2ScreenschemeV1
     * Create screen scheme
     * Creates a screen scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: POST /rest/api/2/screenscheme
     *
     * @param payload 
     */
    @RequestLine("POST /rest/api/2/screenscheme")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    ScreenSchemeId post2ScreenschemeV1(
            @NotNull ScreenSchemeDetails payload
    );

    /**
     * Put2ScreenschemeByScreenSchemeIDV1
     * Update screen scheme
     * Updates a screen scheme. Only screen schemes used in classic projects can be updated.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/screenscheme/{screenSchemeId}
     *
     * @param screenSchemeId The ID of the screen scheme.
     * @param payload The screen scheme update details.
     */
    @RequestLine("PUT /rest/api/2/screenscheme/{screenSchemeId}")
    @Headers({
        "Content-Type: application/json"
    })
    void put2ScreenschemeByScreenSchemeIdv1(
            @NotNull @Param("screenSchemeId") String screenSchemeId,
            @NotNull UpdateScreenSchemeDetails payload
    );

    /**
     * Delete2ScreenschemeByScreenSchemeIDV1
     * Delete screen scheme
     * Deletes a screen scheme. A screen scheme cannot be deleted if it is used in an issue type screen scheme.
    * 
    * Only screens schemes used in classic projects can be deleted.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/screenscheme/{screenSchemeId}
     *
     * @param screenSchemeId The ID of the screen scheme.
     */
    @RequestLine("DELETE /rest/api/2/screenscheme/{screenSchemeId}")
    void delete2ScreenschemeByScreenSchemeIdv1(
            @NotNull @Param("screenSchemeId") String screenSchemeId
    );

}
