// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.ProjectEmailAddress;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * JiraClientProjectEmailApi
 *
 * This resource represents the email address used to send a project's notifications. Use it to get and set the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraClientProjectEmailApi {

    /**
     * Get2ProjectByProjectIDEmailV1
     * Get project's sender email
     * Returns the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
    * 
    * **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *
     * API Method: GET /rest/api/2/project/{projectId}/email
     *
     * @param projectId The project ID.
     */
    @RequestLine("GET /rest/api/2/project/{projectId}/email")
    @Headers({
        "Accept: application/json"
    })
    ProjectEmailAddress get2ProjectByProjectIdemailV1(
            @NotNull @Param("projectId") Long projectId
    );

    /**
     * Put2ProjectByProjectIDEmailV1
     * Set project's sender email
     * Sets the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
    * 
    * If `emailAddress` is an empty string, the default email address is restored.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) or *Administer Projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)
     *
     * API Method: PUT /rest/api/2/project/{projectId}/email
     *
     * @param projectId The project ID.
     * @param payload The project's sender email address to be set.
     */
    @RequestLine("PUT /rest/api/2/project/{projectId}/email")
    @Headers({
        "Content-Type: application/json"
    })
    void put2ProjectByProjectIdemailV1(
            @NotNull @Param("projectId") Long projectId,
            @NotNull ProjectEmailAddress payload
    );

}
