// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.AddAtlassianTeamRequest;
import io.github.primelib.jira4j.rest.v2.models.CreatePlanOnlyTeamRequest;
import io.github.primelib.jira4j.rest.v2.models.GetAtlassianTeamResponse;
import io.github.primelib.jira4j.rest.v2.models.GetPlanOnlyTeamResponse;
import io.github.primelib.jira4j.rest.v2.models.PageWithCursorGetTeamResponseForPage;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * JiraClientTeamsInPlanApi
 *
 * This resource represents planning settings for plan-only and Atlassian teams in a plan. Use it to get, create, update and delete planning settings.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraClientTeamsInPlanApi {

    /**
     * Get2PlansPlanByPlanIDTeamV1
     * Get teams in plan paginated
     * Returns a [paginated](#pagination) list of plan-only and Atlassian teams in a plan.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/plans/plan/{planId}/team
     *
     * @param planId The ID of the plan.
     * @param cursor The cursor to start from. If not provided, the first page will be returned.
     * @param maxResults The maximum number of plan teams to return per page. The maximum value is 50. The default value is 50.
     */
    @RequestLine("GET /rest/api/2/plans/plan/{planId}/team?cursor={cursor}&maxResults={maxResults}")
    @Headers({
        "Accept: application/json"
    })
    PageWithCursorGetTeamResponseForPage get2PlansPlanByPlanIdteamV1(
            @NotNull @Param("planId") Long planId,
            @Nullable @Param("cursor") String cursor,
            @Nullable @Param("maxResults") Integer maxResults
    );

    /**
     * Post2PlansPlanByPlanIDTeamAtlassianV1
     * Add Atlassian team to plan
     * Adds an existing Atlassian team to a plan and configures their plannning settings.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: POST /rest/api/2/plans/plan/{planId}/team/atlassian
     *
     * @param planId The ID of the plan.
     * @param payload 
     */
    @RequestLine("POST /rest/api/2/plans/plan/{planId}/team/atlassian")
    @Headers({
        "Content-Type: application/json"
    })
    void post2PlansPlanByPlanIdteamAtlassianV1(
            @NotNull @Param("planId") Long planId,
            @NotNull AddAtlassianTeamRequest payload
    );

    /**
     * Get2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1
     * Get Atlassian team in plan
     * Returns planning settings for an Atlassian team in a plan.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/plans/plan/{planId}/team/atlassian/{atlassianTeamId}
     *
     * @param planId The ID of the plan.
     * @param atlassianTeamId The ID of the Atlassian team.
     */
    @RequestLine("GET /rest/api/2/plans/plan/{planId}/team/atlassian/{atlassianTeamId}")
    @Headers({
        "Accept: application/json"
    })
    GetAtlassianTeamResponse get2PlansPlanByPlanIdteamAtlassianByAtlassianTeamIdv1(
            @NotNull @Param("planId") Long planId,
            @NotNull @Param("atlassianTeamId") String atlassianTeamId
    );

    /**
     * Put2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1
     * Update Atlassian team in plan
     * Updates any of the following planning settings of an Atlassian team in a plan using [JSON Patch](https://datatracker.ietf.org/doc/html/rfc6902).
    * 
    *  *  planningStyle
    *  *  issueSourceId
    *  *  sprintLength
    *  *  capacity
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    * 
    * *Note that "add" operations do not respect array indexes in target locations. Call the "Get Atlassian team in plan" endpoint to find out the order of array elements.*
     *
     * API Method: PUT /rest/api/2/plans/plan/{planId}/team/atlassian/{atlassianTeamId}
     *
     * @param planId The ID of the plan.
     * @param atlassianTeamId The ID of the Atlassian team.
     * @param payload 
     */
    @RequestLine("PUT /rest/api/2/plans/plan/{planId}/team/atlassian/{atlassianTeamId}")
    @Headers({
        "Content-Type: application/json-patch+json"
    })
    void put2PlansPlanByPlanIdteamAtlassianByAtlassianTeamIdv1(
            @NotNull @Param("planId") Long planId,
            @NotNull @Param("atlassianTeamId") String atlassianTeamId,
            @NotNull Object payload
    );

    /**
     * Delete2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1
     * Remove Atlassian team from plan
     * Removes an Atlassian team from a plan and deletes their planning settings.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/plans/plan/{planId}/team/atlassian/{atlassianTeamId}
     *
     * @param planId The ID of the plan.
     * @param atlassianTeamId The ID of the Atlassian team.
     */
    @RequestLine("DELETE /rest/api/2/plans/plan/{planId}/team/atlassian/{atlassianTeamId}")
    void delete2PlansPlanByPlanIdteamAtlassianByAtlassianTeamIdv1(
            @NotNull @Param("planId") Long planId,
            @NotNull @Param("atlassianTeamId") String atlassianTeamId
    );

    /**
     * Post2PlansPlanByPlanIDTeamPlanonlyV1
     * Create plan-only team
     * Creates a plan-only team and configures their planning settings.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: POST /rest/api/2/plans/plan/{planId}/team/planonly
     *
     * @param planId The ID of the plan.
     * @param payload 
     */
    @RequestLine("POST /rest/api/2/plans/plan/{planId}/team/planonly")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    Long post2PlansPlanByPlanIdteamPlanonlyV1(
            @NotNull @Param("planId") Long planId,
            @NotNull CreatePlanOnlyTeamRequest payload
    );

    /**
     * Get2PlansPlanByPlanIDTeamPlanonlyByPlanOnlyTeamIDV1
     * Get plan-only team
     * Returns planning settings for a plan-only team.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/plans/plan/{planId}/team/planonly/{planOnlyTeamId}
     *
     * @param planId The ID of the plan.
     * @param planOnlyTeamId The ID of the plan-only team.
     */
    @RequestLine("GET /rest/api/2/plans/plan/{planId}/team/planonly/{planOnlyTeamId}")
    @Headers({
        "Accept: application/json"
    })
    GetPlanOnlyTeamResponse get2PlansPlanByPlanIdteamPlanonlyByPlanOnlyTeamIdv1(
            @NotNull @Param("planId") Long planId,
            @NotNull @Param("planOnlyTeamId") Long planOnlyTeamId
    );

    /**
     * Put2PlansPlanByPlanIDTeamPlanonlyByPlanOnlyTeamIDV1
     * Update plan-only team
     * Updates any of the following planning settings of a plan-only team using [JSON Patch](https://datatracker.ietf.org/doc/html/rfc6902).
    * 
    *  *  name
    *  *  planningStyle
    *  *  issueSourceId
    *  *  sprintLength
    *  *  capacity
    *  *  memberAccountIds
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    * 
    * *Note that "add" operations do not respect array indexes in target locations. Call the "Get plan-only team" endpoint to find out the order of array elements.*
     *
     * API Method: PUT /rest/api/2/plans/plan/{planId}/team/planonly/{planOnlyTeamId}
     *
     * @param planId The ID of the plan.
     * @param planOnlyTeamId The ID of the plan-only team.
     * @param payload 
     */
    @RequestLine("PUT /rest/api/2/plans/plan/{planId}/team/planonly/{planOnlyTeamId}")
    @Headers({
        "Content-Type: application/json-patch+json"
    })
    void put2PlansPlanByPlanIdteamPlanonlyByPlanOnlyTeamIdv1(
            @NotNull @Param("planId") Long planId,
            @NotNull @Param("planOnlyTeamId") Long planOnlyTeamId,
            @NotNull Object payload
    );

    /**
     * Delete2PlansPlanByPlanIDTeamPlanonlyByPlanOnlyTeamIDV1
     * Delete plan-only team
     * Deletes a plan-only team and their planning settings.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/plans/plan/{planId}/team/planonly/{planOnlyTeamId}
     *
     * @param planId The ID of the plan.
     * @param planOnlyTeamId The ID of the plan-only team.
     */
    @RequestLine("DELETE /rest/api/2/plans/plan/{planId}/team/planonly/{planOnlyTeamId}")
    void delete2PlansPlanByPlanIdteamPlanonlyByPlanOnlyTeamIdv1(
            @NotNull @Param("planId") Long planId,
            @NotNull @Param("planOnlyTeamId") Long planOnlyTeamId
    );

}
