// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.EntityProperty;
import io.github.primelib.jira4j.rest.v2.models.PropertyKeys;
import io.github.primelib.jira4j.rest.v2.operations.Delete2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2CommentByCommentIDPropertiesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientIssueCommentPropertiesConsumerApi
 *
 * This resource represents [issue comment](#api-group-Issue-comments) properties, which provides for storing custom data against an issue comment. Use is to get, set, and delete issue comment properties as well as obtain the keys of all properties on a comment. Comment properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/).
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientIssueCommentPropertiesConsumerApi {
    private final JiraClientIssueCommentPropertiesApi api;

    public JiraClientIssueCommentPropertiesConsumerApi(JiraClientIssueCommentPropertiesApi api) {
        this.api = api;
    }


    /**
     * Get2CommentByCommentIDPropertiesV1
     * Get comment property keys
     * Returns the keys of all the properties of a comment.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     *
     * API Method: GET /rest/api/2/comment/{commentId}/properties
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>commentId: The ID of the comment.</li>
     * </ul>
     */
    public PropertyKeys get2CommentByCommentIdpropertiesV1(Consumer<Get2CommentByCommentIDPropertiesV1OperationSpec> spec) {
        Get2CommentByCommentIDPropertiesV1OperationSpec r = new Get2CommentByCommentIDPropertiesV1OperationSpec(spec);
        return api.get2CommentByCommentIdpropertiesV1(r.commentId());
    }

    /**
     * Get2CommentByCommentIDPropertyByPropertyKeyV1
     * Get comment property
     * Returns the value of a comment property.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     *
     * API Method: GET /rest/api/2/comment/{commentId}/properties/{propertyKey}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>commentId: The ID of the comment.</li>
     *   <li>propertyKey: The key of the property.</li>
     * </ul>
     */
    public EntityProperty get2CommentByCommentIdpropertyByPropertyKeyV1(Consumer<Get2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec> spec) {
        Get2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec r = new Get2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec(spec);
        return api.get2CommentByCommentIdpropertyByPropertyKeyV1(r.commentId(), r.propertyKey());
    }

    /**
     * Put2CommentByCommentIDPropertyByPropertyKeyV1
     * Set comment property
     * Creates or updates the value of a property for a comment. Use this resource to store custom data against a comment.
    * 
    * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
    * 
    * **[Permissions](#permissions) required:** either of:
    * 
    *  *  *Edit All Comments* [project permission](https://confluence.atlassian.com/x/yodKLg) to create or update the value of a property on any comment.
    *  *  *Edit Own Comments* [project permission](https://confluence.atlassian.com/x/yodKLg) to create or update the value of a property on a comment created by the user.
     *
     * API Method: PUT /rest/api/2/comment/{commentId}/properties/{propertyKey}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>commentId: The ID of the comment.</li>
     *   <li>propertyKey: The key of the property. The maximum length is 255 characters.</li>
     *   <li>payload: The value of the property. The value has to be a valid, non-empty [JSON](https://tools.ietf.org/html/rfc4627) value. The maximum length of the property value is 32768 bytes.</li>
     * </ul>
     */
    public Object put2CommentByCommentIdpropertyByPropertyKeyV1(Consumer<Put2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec> spec) {
        Put2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec r = new Put2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec(spec);
        return api.put2CommentByCommentIdpropertyByPropertyKeyV1(r.commentId(), r.propertyKey(), r.payload());
    }

    /**
     * Delete2CommentByCommentIDPropertyByPropertyKeyV1
     * Delete comment property
     * Deletes a comment property.
    * 
    * **[Permissions](#permissions) required:** either of:
    * 
    *  *  *Edit All Comments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete a property from any comment.
    *  *  *Edit Own Comments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete a property from a comment created by the user.
     *
     * API Method: DELETE /rest/api/2/comment/{commentId}/properties/{propertyKey}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>commentId: The ID of the comment.</li>
     *   <li>propertyKey: The key of the property.</li>
     * </ul>
     */
    public void delete2CommentByCommentIdpropertyByPropertyKeyV1(Consumer<Delete2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec> spec) {
        Delete2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec r = new Delete2CommentByCommentIDPropertyByPropertyKeyV1OperationSpec(spec);
        api.delete2CommentByCommentIdpropertyByPropertyKeyV1(r.commentId(), r.propertyKey());
    }

}
