// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.GetPlanResponse;
import io.github.primelib.jira4j.rest.v2.models.PageWithCursorGetPlanResponseForPage;
import io.github.primelib.jira4j.rest.v2.operations.Get2PlansPlanByPlanIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2PlansPlanV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2PlansPlanByPlanIDDuplicateV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2PlansPlanV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2PlansPlanByPlanIDArchiveV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2PlansPlanByPlanIDTrashV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2PlansPlanByPlanIDV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientPlansConsumerApi
 *
 * This resource represents plans. Use it to get, create, duplicate, update, trash and archive plans.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientPlansConsumerApi {
    private final JiraClientPlansApi api;

    public JiraClientPlansConsumerApi(JiraClientPlansApi api) {
        this.api = api;
    }


    /**
     * Get2PlansPlanV1
     * Get plans paginated
     * Returns a [paginated](#pagination) list of plans.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/plans/plan
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>includeTrashed: Whether to include trashed plans in the results.</li>
     *   <li>includeArchived: Whether to include archived plans in the results.</li>
     *   <li>cursor: The cursor to start from. If not provided, the first page will be returned.</li>
     *   <li>maxResults: The maximum number of plans to return per page. The maximum value is 50. The default value is 50.</li>
     * </ul>
     */
    public PageWithCursorGetPlanResponseForPage get2PlansPlanV1(Consumer<Get2PlansPlanV1OperationSpec> spec) {
        Get2PlansPlanV1OperationSpec r = new Get2PlansPlanV1OperationSpec(spec);
        return api.get2PlansPlanV1(r.includeTrashed(), r.includeArchived(), r.cursor(), r.maxResults());
    }

    /**
     * Post2PlansPlanV1
     * Create plan
     * Creates a plan.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: POST /rest/api/2/plans/plan
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>useGroupId: Whether to accept group IDs instead of group names. Group names are deprecated.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public Long post2PlansPlanV1(Consumer<Post2PlansPlanV1OperationSpec> spec) {
        Post2PlansPlanV1OperationSpec r = new Post2PlansPlanV1OperationSpec(spec);
        return api.post2PlansPlanV1(r.useGroupId(), r.payload());
    }

    /**
     * Get2PlansPlanByPlanIDV1
     * Get plan
     * Returns a plan.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/plans/plan/{planId}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>planId: The ID of the plan.</li>
     *   <li>useGroupId: Whether to return group IDs instead of group names. Group names are deprecated.</li>
     * </ul>
     */
    public GetPlanResponse get2PlansPlanByPlanIdv1(Consumer<Get2PlansPlanByPlanIDV1OperationSpec> spec) {
        Get2PlansPlanByPlanIDV1OperationSpec r = new Get2PlansPlanByPlanIDV1OperationSpec(spec);
        return api.get2PlansPlanByPlanIdv1(r.planId(), r.useGroupId());
    }

    /**
     * Put2PlansPlanByPlanIDV1
     * Update plan
     * Updates any of the following details of a plan using [JSON Patch](https://datatracker.ietf.org/doc/html/rfc6902).
    * 
    *  *  name
    *  *  leadAccountId
    *  *  scheduling
    *     
    *      *  estimation with StoryPoints, Days or Hours as possible values
    *      *  startDate
    *         
    *          *  type with DueDate, TargetStartDate, TargetEndDate or DateCustomField as possible values
    *          *  dateCustomFieldId
    *      *  endDate
    *         
    *          *  type with DueDate, TargetStartDate, TargetEndDate or DateCustomField as possible values
    *          *  dateCustomFieldId
    *      *  inferredDates with None, SprintDates or ReleaseDates as possible values
    *      *  dependencies with Sequential or Concurrent as possible values
    *  *  issueSources
    *     
    *      *  type with Board, Project or Filter as possible values
    *      *  value
    *  *  exclusionRules
    *     
    *      *  numberOfDaysToShowCompletedIssues
    *      *  issueIds
    *      *  workStatusIds
    *      *  workStatusCategoryIds
    *      *  issueTypeIds
    *      *  releaseIds
    *  *  crossProjectReleases
    *     
    *      *  name
    *      *  releaseIds
    *  *  customFields
    *     
    *      *  customFieldId
    *      *  filter
    *  *  permissions
    *     
    *      *  type with View or Edit as possible values
    *      *  holder
    *         
    *          *  type with Group or AccountId as possible values
    *          *  value
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    * 
    * *Note that "add" operations do not respect array indexes in target locations. Call the "Get plan" endpoint to find out the order of array elements.*
     *
     * API Method: PUT /rest/api/2/plans/plan/{planId}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>planId: The ID of the plan.</li>
     *   <li>useGroupId: Whether to accept group IDs instead of group names. Group names are deprecated.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public void put2PlansPlanByPlanIdv1(Consumer<Put2PlansPlanByPlanIDV1OperationSpec> spec) {
        Put2PlansPlanByPlanIDV1OperationSpec r = new Put2PlansPlanByPlanIDV1OperationSpec(spec);
        api.put2PlansPlanByPlanIdv1(r.planId(), r.useGroupId(), r.payload());
    }

    /**
     * Put2PlansPlanByPlanIDArchiveV1
     * Archive plan
     * Archives a plan.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/plans/plan/{planId}/archive
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>planId: The ID of the plan.</li>
     * </ul>
     */
    public void put2PlansPlanByPlanIdarchiveV1(Consumer<Put2PlansPlanByPlanIDArchiveV1OperationSpec> spec) {
        Put2PlansPlanByPlanIDArchiveV1OperationSpec r = new Put2PlansPlanByPlanIDArchiveV1OperationSpec(spec);
        api.put2PlansPlanByPlanIdarchiveV1(r.planId());
    }

    /**
     * Post2PlansPlanByPlanIDDuplicateV1
     * Duplicate plan
     * Duplicates a plan.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: POST /rest/api/2/plans/plan/{planId}/duplicate
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>planId: The ID of the plan.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public Long post2PlansPlanByPlanIdduplicateV1(Consumer<Post2PlansPlanByPlanIDDuplicateV1OperationSpec> spec) {
        Post2PlansPlanByPlanIDDuplicateV1OperationSpec r = new Post2PlansPlanByPlanIDDuplicateV1OperationSpec(spec);
        return api.post2PlansPlanByPlanIdduplicateV1(r.planId(), r.payload());
    }

    /**
     * Put2PlansPlanByPlanIDTrashV1
     * Trash plan
     * Moves a plan to trash.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/plans/plan/{planId}/trash
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>planId: The ID of the plan.</li>
     * </ul>
     */
    public void put2PlansPlanByPlanIdtrashV1(Consumer<Put2PlansPlanByPlanIDTrashV1OperationSpec> spec) {
        Put2PlansPlanByPlanIDTrashV1OperationSpec r = new Put2PlansPlanByPlanIDTrashV1OperationSpec(spec);
        api.put2PlansPlanByPlanIdtrashV1(r.planId());
    }

}
