// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.WorkflowRulesSearchDetails;
import io.github.primelib.jira4j.rest.v2.operations.PostAtlassianConnect1MigrationWorkflowRuleSearchV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.PutAtlassianConnect1MigrationFieldV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.PutAtlassianConnect1MigrationPropertyByEntityTypeV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientAppMigrationConsumerApi
 *
 * This resource supports [app migrations](https://developer.atlassian.com/platform/app-migration/). Use it to:
 * - [to request migrated workflow rules details](https://developer.atlassian.com/platform/app-migration/tutorials/migration-app-workflow-rules/).
 * - [perform bulk updates of entity properties](https://developer.atlassian.com/platform/app-migration/tutorials/entity-properties-bulk-api/).
 * - [perform bulk updates of issue custom field values](https://developer.atlassian.com/platform/app-migration/tutorials/migrating-app-custom-fields/).
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientAppMigrationConsumerApi {
    private final JiraClientAppMigrationApi api;

    public JiraClientAppMigrationConsumerApi(JiraClientAppMigrationApi api) {
        this.api = api;
    }


    /**
     * PutAtlassianConnect1MigrationFieldV1
     * Bulk update custom field value
     * Updates the value of a custom field added by Connect apps on one or more issues.
    * The values of up to 200 custom fields can be updated.
    * 
    * **[Permissions](#permissions) required:** Only Connect apps can make this request
     *
     * API Method: PUT /rest/atlassian-connect/1/migration/field
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>atlassianTransferId: The ID of the transfer.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public Object putAtlassianConnect1MigrationFieldV1(Consumer<PutAtlassianConnect1MigrationFieldV1OperationSpec> spec) {
        PutAtlassianConnect1MigrationFieldV1OperationSpec r = new PutAtlassianConnect1MigrationFieldV1OperationSpec(spec);
        return api.putAtlassianConnect1MigrationFieldV1(r.atlassianTransferId(), r.payload());
    }

    /**
     * PutAtlassianConnect1MigrationPropertyByEntityTypeV1
     * Bulk update entity properties
     * Updates the values of multiple entity properties for an object, up to 50 updates per request. This operation is for use by Connect apps during app migration.
     *
     * API Method: PUT /rest/atlassian-connect/1/migration/properties/{entityType}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>atlassianTransferId: The app migration transfer ID.</li>
     *   <li>entityType: The type indicating the object that contains the entity properties.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public void putAtlassianConnect1MigrationPropertyByEntityTypeV1(Consumer<PutAtlassianConnect1MigrationPropertyByEntityTypeV1OperationSpec> spec) {
        PutAtlassianConnect1MigrationPropertyByEntityTypeV1OperationSpec r = new PutAtlassianConnect1MigrationPropertyByEntityTypeV1OperationSpec(spec);
        api.putAtlassianConnect1MigrationPropertyByEntityTypeV1(r.atlassianTransferId(), r.entityType(), r.payload());
    }

    /**
     * PostAtlassianConnect1MigrationWorkflowRuleSearchV1
     * Get workflow transition rule configurations
     * Returns configurations for workflow transition rules migrated from server to cloud and owned by the calling Connect app.
     *
     * API Method: POST /rest/atlassian-connect/1/migration/workflow/rule/search
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>atlassianTransferId: The app migration transfer ID.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public WorkflowRulesSearchDetails postAtlassianConnect1MigrationWorkflowRuleSearchV1(Consumer<PostAtlassianConnect1MigrationWorkflowRuleSearchV1OperationSpec> spec) {
        PostAtlassianConnect1MigrationWorkflowRuleSearchV1OperationSpec r = new PostAtlassianConnect1MigrationWorkflowRuleSearchV1OperationSpec(spec);
        return api.postAtlassianConnect1MigrationWorkflowRuleSearchV1(r.atlassianTransferId(), r.payload());
    }

}
