// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.IssueMatches;
import io.github.primelib.jira4j.rest.v2.models.IssuePickerSuggestions;
import io.github.primelib.jira4j.rest.v2.models.JqlcountResultsBean;
import io.github.primelib.jira4j.rest.v2.models.SearchAndReconcileResults;
import io.github.primelib.jira4j.rest.v2.models.SearchResults;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssuePickerV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2SearchJqlV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2SearchV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2JqlMatchV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2SearchApproximateCountV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2SearchJqlV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2SearchV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientIssueSearchConsumerApi
 *
 * This resource represents various ways to search for issues. Use it to search for issues with a JQL query and find issues to populate an issue picker.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientIssueSearchConsumerApi {
    private final JiraClientIssueSearchApi api;

    public JiraClientIssueSearchConsumerApi(JiraClientIssueSearchApi api) {
        this.api = api;
    }


    /**
     * Get2IssuePickerV1
     * Get issue picker suggestions
     * Returns lists of issues matching a query string. Use this resource to provide auto-completion suggestions when the user is looking for an issue using a word or string.
    * 
    * This operation returns two lists:
    * 
    *  *  `History Search` which includes issues from the user's history of created, edited, or viewed issues that contain the string in the `query` parameter.
    *  *  `Current Search` which includes issues that match the JQL expression in `currentJQL` and contain the string in the `query` parameter.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** None.
     *
     * API Method: GET /rest/api/2/issue/picker
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: A string to match against text fields in the issue such as title, description, or comments.</li>
     *   <li>currentJql: A JQL query defining a list of issues to search for the query term. Note that `username` and `userkey` cannot be used as search terms for this parameter, due to privacy reasons. Use `accountId` instead.</li>
     *   <li>currentIssueKey: The key of an issue to exclude from search results. For example, the issue the user is viewing when they perform this query.</li>
     *   <li>currentProjectId: The ID of a project that suggested issues must belong to.</li>
     *   <li>showSubTasks: Indicate whether to include subtasks in the suggestions list.</li>
     *   <li>showSubTaskParent: When `currentIssueKey` is a subtask, whether to include the parent issue in the suggestions if it matches the query.</li>
     * </ul>
     */
    public IssuePickerSuggestions get2IssuePickerV1(Consumer<Get2IssuePickerV1OperationSpec> spec) {
        Get2IssuePickerV1OperationSpec r = new Get2IssuePickerV1OperationSpec(spec);
        return api.get2IssuePickerV1(r.query(), r.currentJql(), r.currentIssueKey(), r.currentProjectId(), r.showSubTasks(), r.showSubTaskParent());
    }

    /**
     * Post2JqlMatchV1
     * Check issues against JQL
     * Checks whether one or more issues would be returned by one or more JQL queries.
    * 
    * **[Permissions](#permissions) required:** None, however, issues are only matched against JQL queries where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * API Method: POST /rest/api/2/jql/match
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
     */
    public IssueMatches post2JqlMatchV1(Consumer<Post2JqlMatchV1OperationSpec> spec) {
        Post2JqlMatchV1OperationSpec r = new Post2JqlMatchV1OperationSpec(spec);
        return api.post2JqlMatchV1(r.payload());
    }

    /**
     * Get2SearchV1
     * Currently being removed. Search for issues using JQL (GET)
     * Endpoint is currently being removed. [More details](https://developer.atlassian.com/changelog/#CHANGE-2046)
    * 
    * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ).
    * 
    * If the JQL query expression is too large to be encoded as a query parameter, use the [POST](#api-rest-api-2-search-post) version of this resource.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * API Method: GET /rest/api/2/search
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>jql: The [JQL](https://confluence.atlassian.com/x/egORLQ) that defines the search. Note:   *  If no JQL expression is provided, all issues are returned.  *  `username` and `userkey` cannot be used as search terms due to privacy reasons. Use `accountId` instead.  *  If a user has hidden their email address in their user profile, partial matches of the email address will not find the user. An exact match is required.</li>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page. To manage page size, Jira may return fewer items per page where a large number of fields or properties are requested. The greatest number of items returned per page is achieved when requesting `id` or `key` only.</li>
     *   <li>validateQuery: Determines how to validate the JQL query and treat the validation results. Supported values are:   *  `strict` Returns a 400 response code if any errors are found, along with a list of all errors (and warnings).  *  `warn` Returns all errors as warnings.  *  `none` No validation is performed.  *  `true` *Deprecated* A legacy synonym for `strict`.  *  `false` *Deprecated* A legacy synonym for `warn`.  Note: If the JQL is not correctly formed a 400 response code is returned, regardless of the `validateQuery` value.</li>
     *   <li>fields: A list of fields to return for each issue, use it to retrieve a subset of fields. This parameter accepts a comma-separated list. Expand options include:   *  `*all` Returns all fields.  *  `*navigable` Returns navigable fields.  *  Any issue field, prefixed with a minus to exclude.  Examples:   *  `summary,comment` Returns only the summary and comments fields.  *  `-description` Returns all navigable (default) fields except description.  *  `*all,-comment` Returns all fields except comments.  This parameter may be specified multiple times. For example, `fields=field1,field2&amp;fields=field3`.  Note: All navigable fields are returned by default. This differs from [GET issue](#api-rest-api-2-issue-issueIdOrKey-get) where the default is all fields.</li>
     *   <li>expand: Use [expand](#expansion) to include additional information about issues in the response. This parameter accepts a comma-separated list. Expand options include:   *  `renderedFields` Returns field values rendered in HTML format.  *  `names` Returns the display name of each field.  *  `schema` Returns the schema describing a field type.  *  `transitions` Returns all possible transitions for the issue.  *  `operations` Returns all possible operations for the issue.  *  `editmeta` Returns information about how each field can be edited.  *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.  *  `versionedRepresentations` Instead of `fields`, returns `versionedRepresentations` a JSON array containing each version of a field's value, with the highest numbered item representing the most recent version.</li>
     *   <li>properties: A list of issue property keys for issue properties to include in the results. This parameter accepts a comma-separated list. Multiple properties can also be provided using an ampersand separated list. For example, `properties=prop1,prop2&amp;properties=prop3`. A maximum of 5 issue property keys can be specified.</li>
     *   <li>fieldsByKeys: Reference fields by their key (rather than ID).</li>
     *   <li>failFast: Whether to fail the request quickly in case of an error while loading fields for an issue. For `failFast=true`, if one field fails, the entire operation fails. For `failFast=false`, the operation will continue even if a field fails. It will return a valid response, but without values for the failed field(s).</li>
     * </ul>
     * @deprecated
     */
    @Deprecated
    public SearchResults get2SearchV1(Consumer<Get2SearchV1OperationSpec> spec) {
        Get2SearchV1OperationSpec r = new Get2SearchV1OperationSpec(spec);
        return api.get2SearchV1(r.jql(), r.startAt(), r.maxResults(), r.validateQuery(), r.fields(), r.expand(), r.properties(), r.fieldsByKeys(), r.failFast());
    }

    /**
     * Post2SearchV1
     * Currently being removed. Search for issues using JQL (POST)
     * Endpoint is currently being removed. [More details](https://developer.atlassian.com/changelog/#CHANGE-2046)
    * 
    * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ).
    * 
    * There is a [GET](#api-rest-api-2-search-get) version of this resource that can be used for smaller JQL query expressions.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * API Method: POST /rest/api/2/search
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: A JSON object containing the search request.</li>
     * </ul>
     * @deprecated
     */
    @Deprecated
    public SearchResults post2SearchV1(Consumer<Post2SearchV1OperationSpec> spec) {
        Post2SearchV1OperationSpec r = new Post2SearchV1OperationSpec(spec);
        return api.post2SearchV1(r.payload());
    }

    /**
     * Post2SearchApproximateCountV1
     * Count issues using JQL
     * Provide an estimated count of the issues that match the [JQL](https://confluence.atlassian.com/x/egORLQ). Recent updates might not be immediately visible in the returned output. This endpoint requires JQL to be bounded.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * API Method: POST /rest/api/2/search/approximate-count
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: A JSON object containing the search request.</li>
     * </ul>
     */
    public JqlcountResultsBean post2SearchApproximateCountV1(Consumer<Post2SearchApproximateCountV1OperationSpec> spec) {
        Post2SearchApproximateCountV1OperationSpec r = new Post2SearchApproximateCountV1OperationSpec(spec);
        return api.post2SearchApproximateCountV1(r.payload());
    }

    /**
     * Get2SearchJqlV1
     * Search for issues using JQL enhanced search (GET)
     * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ). Recent updates might not be immediately visible in the returned search results. If you need [read-after-write](https://developer.atlassian.com/cloud/jira/platform/search-and-reconcile/) consistency, you can utilize the `reconcileIssues` parameter to ensure stronger consistency assurances. This operation can be accessed anonymously.
    * 
    * If the JQL query expression is too large to be encoded as a query parameter, use the [POST](#api-rest-api-2-search-post) version of this resource.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * API Method: GET /rest/api/2/search/jql
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>jql: A [JQL](https://confluence.atlassian.com/x/egORLQ) expression. For performance reasons, this parameter requires a bounded query. A bounded query is a query with a search restriction.   *  Example of an unbounded query: `order by key desc`.  *  Example of a bounded query: `assignee = currentUser() order by key`.  Additionally, `orderBy` clause can contain a maximum of 7 fields.</li>
     *   <li>nextPageToken: The token for a page to fetch that is not the first page. The first page has a `nextPageToken` of `null`. Use the `nextPageToken` to fetch the next page of issues.  Note: The `nextPageToken` field is **not included** in the response for the last page, indicating there is no next page.</li>
     *   <li>maxResults: The maximum number of items to return per page. To manage page size, API may return fewer items per page where a large number of fields or properties are requested. The greatest number of items returned per page is achieved when requesting `id` or `key` only. It returns max 5000 issues.</li>
     *   <li>fields: A list of fields to return for each issue, use it to retrieve a subset of fields. This parameter accepts a comma-separated list. Expand options include:   *  `*all` Returns all fields.  *  `*navigable` Returns navigable fields.  *  `id` Returns only issue IDs.  *  Any issue field, prefixed with a minus to exclude.  The default is `id`.  Examples:   *  `summary,comment` Returns only the summary and comments fields only.  *  `-description` Returns all navigable (default) fields except description.  *  `*all,-comment` Returns all fields except comments.  Multiple `fields` parameters can be included in a request.  Note: By default, this resource returns IDs only. This differs from [GET issue](#api-rest-api-2-issue-issueIdOrKey-get) where the default is all fields.</li>
     *   <li>expand: Use [expand](#expansion) to include additional information about issues in the response. Note that, unlike the majority of instances where `expand` is specified, `expand` is defined as a comma-delimited string of values. The expand options are:   *  `renderedFields` Returns field values rendered in HTML format.  *  `names` Returns the display name of each field.  *  `schema` Returns the schema describing a field type.  *  `transitions` Returns all possible transitions for the issue.  *  `operations` Returns all possible operations for the issue.  *  `editmeta` Returns information about how each field can be edited.  *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.  *  `versionedRepresentations` Instead of `fields`, returns `versionedRepresentations` a JSON array containing each version of a field's value, with the highest numbered item representing the most recent version.  Examples: `"names,changelog"` Returns the display name of each field as well as a list of recent updates to an issue.</li>
     *   <li>properties: A list of up to 5 issue properties to include in the results. This parameter accepts a comma-separated list.</li>
     *   <li>fieldsByKeys: Reference fields by their key (rather than ID). The default is `false`.</li>
     *   <li>failFast: Fail this request early if we can't retrieve all field data.</li>
     *   <li>reconcileIssues: Strong consistency issue ids to be reconciled with search results. Accepts max 50 ids</li>
     * </ul>
     */
    public SearchAndReconcileResults get2SearchJqlV1(Consumer<Get2SearchJqlV1OperationSpec> spec) {
        Get2SearchJqlV1OperationSpec r = new Get2SearchJqlV1OperationSpec(spec);
        return api.get2SearchJqlV1(r.jql(), r.nextPageToken(), r.maxResults(), r.fields(), r.expand(), r.properties(), r.fieldsByKeys(), r.failFast(), r.reconcileIssues());
    }

    /**
     * Post2SearchJqlV1
     * Search for issues using JQL enhanced search (POST)
     * Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ). Recent updates might not be immediately visible in the returned search results. If you need [read-after-write](https://developer.atlassian.com/cloud/jira/platform/search-and-reconcile/) consistency, you can utilize the `reconcileIssues` parameter to ensure stronger consistency assurances. This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * API Method: POST /rest/api/2/search/jql
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
     */
    public SearchAndReconcileResults post2SearchJqlV1(Consumer<Post2SearchJqlV1OperationSpec> spec) {
        Post2SearchJqlV1OperationSpec r = new Post2SearchJqlV1OperationSpec(spec);
        return api.post2SearchJqlV1(r.payload());
    }

}
