// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.TaskProgressBeanObject;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * JiraClientTasksApi
 *
 * This resource represents a [long-running asynchronous tasks](#async-operations). Use it to obtain details about the progress of a long-running task or cancel a long-running task.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraClientTasksApi {

    /**
     * Get2TaskByTaskIDV1
     * Get task
     * Returns the status of a [long-running asynchronous task](#async).
    * 
    * When a task has finished, this operation returns the JSON blob applicable to the task. See the documentation of the operation that created the task for details. Task details are not permanently retained. As of September 2019, details are retained for 14 days although this period may change without notice.
    * 
    * **Deprecation notice:** The required OAuth 2.0 scopes will be updated on June 15, 2024.
    * 
    *  *  `read:jira-work`
    * 
    * **[Permissions](#permissions) required:** either of:
    * 
    *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *  *  Creator of the task.
     *
     * API Method: GET /rest/api/2/task/{taskId}
     *
     * @param taskId The ID of the task.
     */
    @RequestLine("GET /rest/api/2/task/{taskId}")
    @Headers({
        "Accept: application/json"
    })
    TaskProgressBeanObject get2TaskByTaskIdv1(
            @NotNull @Param("taskId") String taskId
    );

    /**
     * Post2TaskByTaskIDCancelV1
     * Cancel task
     * Cancels a task.
    * 
    * **[Permissions](#permissions) required:** either of:
    * 
    *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    *  *  Creator of the task.
     *
     * API Method: POST /rest/api/2/task/{taskId}/cancel
     *
     * @param taskId The ID of the task.
     */
    @RequestLine("POST /rest/api/2/task/{taskId}/cancel")
    void post2TaskByTaskIdcancelV1(
            @NotNull @Param("taskId") String taskId
    );

}
