// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.TimeTrackingConfiguration;
import io.github.primelib.jira4j.rest.v2.models.TimeTrackingProvIDEr;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * JiraClientTimeTrackingApi
 *
 * This resource represents time tracking and time tracking providers. Use it to get and set the time tracking provider, get and set the time tracking options, and disable time tracking.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraClientTimeTrackingApi {

    /**
     * Get2ConfigurationTimetrackingV1
     * Get selected time tracking provider
     * Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then a successful but empty response is returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/configuration/timetracking
     *
     */
    @RequestLine("GET /rest/api/2/configuration/timetracking")
    @Headers({
        "Accept: application/json"
    })
    TimeTrackingProvIDEr get2ConfigurationTimetrackingV1();

    /**
     * Put2ConfigurationTimetrackingV1
     * Select time tracking provider
     * Selects a time tracking provider.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/configuration/timetracking
     *
     * @param payload 
     */
    @RequestLine("PUT /rest/api/2/configuration/timetracking")
    @Headers({
        "Content-Type: application/json"
    })
    void put2ConfigurationTimetrackingV1(
            @NotNull TimeTrackingProvIDEr payload
    );

    /**
     * Get2ConfigurationTimetrackingListV1
     * Get all time tracking providers
     * Returns all time tracking providers. By default, Jira only has one time tracking provider: *JIRA provided time tracking*. However, you can install other time tracking providers via apps from the Atlassian Marketplace. For more information on time tracking providers, see the documentation for the [ Time Tracking Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/) module.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/configuration/timetracking/list
     *
     */
    @RequestLine("GET /rest/api/2/configuration/timetracking/list")
    @Headers({
        "Accept: application/json"
    })
    List<TimeTrackingProvIDEr> get2ConfigurationTimetrackingListV1();

    /**
     * Get2ConfigurationTimetrackingOptionsV1
     * Get time tracking settings
     * Returns the time tracking settings. This includes settings such as the time format, default time unit, and others. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/configuration/timetracking/options
     *
     */
    @RequestLine("GET /rest/api/2/configuration/timetracking/options")
    @Headers({
        "Accept: application/json"
    })
    TimeTrackingConfiguration get2ConfigurationTimetrackingOptionsV1();

    /**
     * Put2ConfigurationTimetrackingOptionsV1
     * Set time tracking settings
     * Sets the time tracking settings.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/configuration/timetracking/options
     *
     * @param payload 
     */
    @RequestLine("PUT /rest/api/2/configuration/timetracking/options")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    TimeTrackingConfiguration put2ConfigurationTimetrackingOptionsV1(
            @NotNull TimeTrackingConfiguration payload
    );

}
