// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.IssueTypeSchemeId;
import io.github.primelib.jira4j.rest.v2.models.PageBeanIssueTypeScheme;
import io.github.primelib.jira4j.rest.v2.models.PageBeanIssueTypeSchemeMapping;
import io.github.primelib.jira4j.rest.v2.models.PageBeanIssueTypeSchemeProjects;
import io.github.primelib.jira4j.rest.v2.operations.Delete2IssuetypeschemeByIssueTypeSchemeIDIssuetypeByIssueTypeIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Delete2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssuetypeschemeMappingV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssuetypeschemeProjectV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Get2IssuetypeschemeV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Post2IssuetypeschemeV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeMoveV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2IssuetypeschemeProjectV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientIssueTypeSchemesConsumerApi
 *
 * This resource represents issue type schemes in classic projects. Use it to:
 * 
 *  *  get issue type schemes and a list of the projects that use them.
 *  *  associate issue type schemes with projects.
 *  *  add issue types to issue type schemes.
 *  *  delete issue types from issue type schemes.
 *  *  create, update, and delete issue type schemes.
 *  *  change the order of issue types in issue type schemes.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientIssueTypeSchemesConsumerApi {
    private final JiraClientIssueTypeSchemesApi api;

    public JiraClientIssueTypeSchemesConsumerApi(JiraClientIssueTypeSchemesApi api) {
        this.api = api;
    }


    /**
     * Get2IssuetypeschemeV1
     * Get all issue type schemes
     * Returns a [paginated](#pagination) list of issue type schemes.
    * 
    * Only issue type schemes used in classic projects are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/issuetypescheme
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>id: The list of issue type schemes IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&amp;id=10001`.</li>
     *   <li>orderBy: [Order](#ordering) the results by a field:   *  `name` Sorts by issue type scheme name.  *  `id` Sorts by issue type scheme ID.</li>
     *   <li>expand: Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expand options include:   *  `projects` For each issue type schemes, returns information about the projects the issue type scheme is assigned to.  *  `issueTypes` For each issue type schemes, returns information about the issueTypes the issue type scheme have.</li>
     *   <li>queryString: String used to perform a case-insensitive partial match with issue type scheme name.</li>
     * </ul>
     */
    public PageBeanIssueTypeScheme get2IssuetypeschemeV1(Consumer<Get2IssuetypeschemeV1OperationSpec> spec) {
        Get2IssuetypeschemeV1OperationSpec r = new Get2IssuetypeschemeV1OperationSpec(spec);
        return api.get2IssuetypeschemeV1(r.startAt(), r.maxResults(), r.id(), r.orderBy(), r.expand(), r.queryString());
    }

    /**
     * Post2IssuetypeschemeV1
     * Create issue type scheme
     * Creates an issue type scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: POST /rest/api/2/issuetypescheme
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
     */
    public IssueTypeSchemeId post2IssuetypeschemeV1(Consumer<Post2IssuetypeschemeV1OperationSpec> spec) {
        Post2IssuetypeschemeV1OperationSpec r = new Post2IssuetypeschemeV1OperationSpec(spec);
        return api.post2IssuetypeschemeV1(r.payload());
    }

    /**
     * Get2IssuetypeschemeMappingV1
     * Get issue type scheme items
     * Returns a [paginated](#pagination) list of issue type scheme items.
    * 
    * Only issue type scheme items used in classic projects are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/issuetypescheme/mapping
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>issueTypeSchemeId: The list of issue type scheme IDs. To include multiple IDs, provide an ampersand-separated list. For example, `issueTypeSchemeId=10000&amp;issueTypeSchemeId=10001`.</li>
     * </ul>
     */
    public PageBeanIssueTypeSchemeMapping get2IssuetypeschemeMappingV1(Consumer<Get2IssuetypeschemeMappingV1OperationSpec> spec) {
        Get2IssuetypeschemeMappingV1OperationSpec r = new Get2IssuetypeschemeMappingV1OperationSpec(spec);
        return api.get2IssuetypeschemeMappingV1(r.startAt(), r.maxResults(), r.issueTypeSchemeId());
    }

    /**
     * Get2IssuetypeschemeProjectV1
     * Get issue type schemes for projects
     * Returns a [paginated](#pagination) list of issue type schemes and, for each issue type scheme, a list of the projects that use it.
    * 
    * Only issue type schemes used in classic projects are returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/issuetypescheme/project
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>projectId: The list of project IDs. To include multiple project IDs, provide an ampersand-separated list. For example, `projectId=10000&amp;projectId=10001`.</li>
     * </ul>
     */
    public PageBeanIssueTypeSchemeProjects get2IssuetypeschemeProjectV1(Consumer<Get2IssuetypeschemeProjectV1OperationSpec> spec) {
        Get2IssuetypeschemeProjectV1OperationSpec r = new Get2IssuetypeschemeProjectV1OperationSpec(spec);
        return api.get2IssuetypeschemeProjectV1(r.startAt(), r.maxResults(), r.projectId());
    }

    /**
     * Put2IssuetypeschemeProjectV1
     * Assign issue type scheme to project
     * Assigns an issue type scheme to a project.
    * 
    * If any issues in the project are assigned issue types not present in the new scheme, the operation will fail. To complete the assignment those issues must be updated to use issue types in the new scheme.
    * 
    * Issue type schemes can only be assigned to classic projects.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/issuetypescheme/project
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
     */
    public void put2IssuetypeschemeProjectV1(Consumer<Put2IssuetypeschemeProjectV1OperationSpec> spec) {
        Put2IssuetypeschemeProjectV1OperationSpec r = new Put2IssuetypeschemeProjectV1OperationSpec(spec);
        api.put2IssuetypeschemeProjectV1(r.payload());
    }

    /**
     * Put2IssuetypeschemeByIssueTypeSchemeIDV1
     * Update issue type scheme
     * Updates an issue type scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/issuetypescheme/{issueTypeSchemeId}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>issueTypeSchemeId: The ID of the issue type scheme.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public void put2IssuetypeschemeByIssueTypeSchemeIdv1(Consumer<Put2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec> spec) {
        Put2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec r = new Put2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec(spec);
        api.put2IssuetypeschemeByIssueTypeSchemeIdv1(r.issueTypeSchemeId(), r.payload());
    }

    /**
     * Delete2IssuetypeschemeByIssueTypeSchemeIDV1
     * Delete issue type scheme
     * Deletes an issue type scheme.
    * 
    * Only issue type schemes used in classic projects can be deleted.
    * 
    * Any projects assigned to the scheme are reassigned to the default issue type scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/issuetypescheme/{issueTypeSchemeId}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>issueTypeSchemeId: The ID of the issue type scheme.</li>
     * </ul>
     */
    public void delete2IssuetypeschemeByIssueTypeSchemeIdv1(Consumer<Delete2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec> spec) {
        Delete2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec r = new Delete2IssuetypeschemeByIssueTypeSchemeIDV1OperationSpec(spec);
        api.delete2IssuetypeschemeByIssueTypeSchemeIdv1(r.issueTypeSchemeId());
    }

    /**
     * Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeV1
     * Add issue types to issue type scheme
     * Adds issue types to an issue type scheme.
    * 
    * The added issue types are appended to the issue types list.
    * 
    * If any of the issue types exist in the issue type scheme, the operation fails and no issue types are added.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/issuetypescheme/{issueTypeSchemeId}/issuetype
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>issueTypeSchemeId: The ID of the issue type scheme.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public void put2IssuetypeschemeByIssueTypeSchemeIdissuetypeV1(Consumer<Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeV1OperationSpec> spec) {
        Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeV1OperationSpec r = new Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeV1OperationSpec(spec);
        api.put2IssuetypeschemeByIssueTypeSchemeIdissuetypeV1(r.issueTypeSchemeId(), r.payload());
    }

    /**
     * Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeMoveV1
     * Change order of issue types
     * Changes the order of issue types in an issue type scheme.
    * 
    * The request body parameters must meet the following requirements:
    * 
    *  *  all of the issue types must belong to the issue type scheme.
    *  *  either `after` or `position` must be provided.
    *  *  the issue type in `after` must not be in the issue type list.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/issuetypescheme/{issueTypeSchemeId}/issuetype/move
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>issueTypeSchemeId: The ID of the issue type scheme.</li>
     *   <li>payload: </li>
     * </ul>
     */
    public void put2IssuetypeschemeByIssueTypeSchemeIdissuetypeMoveV1(Consumer<Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeMoveV1OperationSpec> spec) {
        Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeMoveV1OperationSpec r = new Put2IssuetypeschemeByIssueTypeSchemeIDIssuetypeMoveV1OperationSpec(spec);
        api.put2IssuetypeschemeByIssueTypeSchemeIdissuetypeMoveV1(r.issueTypeSchemeId(), r.payload());
    }

    /**
     * Delete2IssuetypeschemeByIssueTypeSchemeIDIssuetypeByIssueTypeIDV1
     * Remove issue type from issue type scheme
     * Removes an issue type from an issue type scheme.
    * 
    * This operation cannot remove:
    * 
    *  *  any issue type used by issues.
    *  *  any issue types from the default issue type scheme.
    *  *  the last standard issue type from an issue type scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/issuetypescheme/{issueTypeSchemeId}/issuetype/{issueTypeId}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>issueTypeSchemeId: The ID of the issue type scheme.</li>
     *   <li>issueTypeId: The ID of the issue type.</li>
     * </ul>
     */
    public void delete2IssuetypeschemeByIssueTypeSchemeIdissuetypeByIssueTypeIdv1(Consumer<Delete2IssuetypeschemeByIssueTypeSchemeIDIssuetypeByIssueTypeIDV1OperationSpec> spec) {
        Delete2IssuetypeschemeByIssueTypeSchemeIDIssuetypeByIssueTypeIDV1OperationSpec r = new Delete2IssuetypeschemeByIssueTypeSchemeIDIssuetypeByIssueTypeIDV1OperationSpec(spec);
        api.delete2IssuetypeschemeByIssueTypeSchemeIdissuetypeByIssueTypeIdv1(r.issueTypeSchemeId(), r.issueTypeId());
    }

}
