// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.jira4j.rest.v2.models.BulkIssueIsWatching;
import io.github.primelib.jira4j.rest.v2.models.IssueList;
import io.github.primelib.jira4j.rest.v2.models.Watchers;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * JiraClientIssueWatchersApi
 *
 * This resource represents users watching an issue. Use it to get details of users watching an issue as well as start and stop a user watching an issue.
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface JiraClientIssueWatchersApi {

    /**
     * Post2IssueWatchingV1
     * Get is watching issue bulk
     * Returns, for the user, details of the watched status of issues from a list. If an issue ID is invalid, the returned watched status is `false`.
    * 
    * This operation requires the **Allow users to watch issues** option to be *ON*. This option is set in General configuration for Jira. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * API Method: POST /rest/api/2/issue/watching
     *
     * @param payload A list of issue IDs.
     */
    @RequestLine("POST /rest/api/2/issue/watching")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    BulkIssueIsWatching post2IssueWatchingV1(
            @NotNull IssueList payload
    );

    /**
     * Get2IssueByIssueIDOrKeyWatchersV1
     * Get issue watchers
     * Returns the watchers for an issue.
    * 
    * This operation requires the **Allow users to watch issues** option to be *ON*. This option is set in General configuration for Jira. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is ini
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  To see details of users on the watchlist other than themselves, *View voters and watchers* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *
     * API Method: GET /rest/api/2/issue/{issueIdOrKey}/watchers
     *
     * @param issueIdOrKey The ID or key of the issue.
     */
    @RequestLine("GET /rest/api/2/issue/{issueIdOrKey}/watchers")
    @Headers({
        "Accept: application/json"
    })
    Watchers get2IssueByIssueIdorKeyWatchersV1(
            @NotNull @Param("issueIdOrKey") String issueIdOrKey
    );

    /**
     * Post2IssueByIssueIDOrKeyWatchersV1
     * Add watcher
     * Adds a user as a watcher of an issue by passing the account ID of the user. For example, `"5b10ac8d82e05b22cc7d4ef5"`. If no user is specified the calling user is added.
    * 
    * This operation requires the **Allow users to watch issues** option to be *ON*. This option is set in General configuration for Jira. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  To add users other than themselves to the watchlist, *Manage watcher list* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *
     * API Method: POST /rest/api/2/issue/{issueIdOrKey}/watchers
     *
     * @param issueIdOrKey The ID or key of the issue.
     * @param payload The account ID of the user. Note that username cannot be used due to privacy changes.
     */
    @RequestLine("POST /rest/api/2/issue/{issueIdOrKey}/watchers")
    @Headers({
        "Content-Type: application/json"
    })
    void post2IssueByIssueIdorKeyWatchersV1(
            @NotNull @Param("issueIdOrKey") String issueIdOrKey,
            @NotNull String payload
    );

    /**
     * Delete2IssueByIssueIDOrKeyWatchersV1
     * Delete watcher
     * Deletes a user as a watcher of an issue.
    * 
    * This operation requires the **Allow users to watch issues** option to be *ON*. This option is set in General configuration for Jira. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    *  *  To remove users other than themselves from the watchlist, *Manage watcher list* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *
     * API Method: DELETE /rest/api/2/issue/{issueIdOrKey}/watchers
     *
     * @param issueIdOrKey The ID or key of the issue.
     * @param username This parameter is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
     * @param accountId The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required.
     */
    @RequestLine("DELETE /rest/api/2/issue/{issueIdOrKey}/watchers?username={username}&accountId={accountId}")
    void delete2IssueByIssueIdorKeyWatchersV1(
            @NotNull @Param("issueIdOrKey") String issueIdOrKey,
            @Nullable @Param("username") String username,
            @Nullable @Param("accountId") String accountId
    );

}
