// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.ContainerForProjectFeatures;
import io.github.primelib.jira4j.rest.v2.operations.Get2ProjectByProjectIDOrKeyFeaturesV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2ProjectByProjectIDOrKeyFeatureByFeatureKeyV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientProjectFeaturesConsumerApi
 *
 * This resource represents project features. Use it to get the list of features for a project and modify the state of a feature. The project feature endpoint is available only for Jira Software, both for team- and company-managed projects.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientProjectFeaturesConsumerApi {
    private final JiraClientProjectFeaturesApi api;

    public JiraClientProjectFeaturesConsumerApi(JiraClientProjectFeaturesApi api) {
        this.api = api;
    }


    /**
     * Get2ProjectByProjectIDOrKeyFeaturesV1
     * Get project features
     * Returns the list of features for a project.
     *
     * API Method: GET /rest/api/2/project/{projectIdOrKey}/features
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>projectIdOrKey: The ID or (case-sensitive) key of the project.</li>
     * </ul>
     */
    public ContainerForProjectFeatures get2ProjectByProjectIdorKeyFeaturesV1(Consumer<Get2ProjectByProjectIDOrKeyFeaturesV1OperationSpec> spec) {
        Get2ProjectByProjectIDOrKeyFeaturesV1OperationSpec r = new Get2ProjectByProjectIDOrKeyFeaturesV1OperationSpec(spec);
        return api.get2ProjectByProjectIdorKeyFeaturesV1(r.projectIdOrKey());
    }

    /**
     * Put2ProjectByProjectIDOrKeyFeatureByFeatureKeyV1
     * Set project feature state
     * Sets the state of a project feature.
     *
     * API Method: PUT /rest/api/2/project/{projectIdOrKey}/features/{featureKey}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>projectIdOrKey: The ID or (case-sensitive) key of the project.</li>
     *   <li>featureKey: The key of the feature.</li>
     *   <li>payload: Details of the feature state change.</li>
     * </ul>
     */
    public ContainerForProjectFeatures put2ProjectByProjectIdorKeyFeatureByFeatureKeyV1(Consumer<Put2ProjectByProjectIDOrKeyFeatureByFeatureKeyV1OperationSpec> spec) {
        Put2ProjectByProjectIDOrKeyFeatureByFeatureKeyV1OperationSpec r = new Put2ProjectByProjectIDOrKeyFeatureByFeatureKeyV1OperationSpec(spec);
        return api.put2ProjectByProjectIdorKeyFeatureByFeatureKeyV1(r.projectIdOrKey(), r.featureKey(), r.payload());
    }

}
