// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.ServerInformation;
import io.github.primelib.jira4j.rest.v2.operations.Get2ServerInfoV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientServerInfoConsumerApi
 *
 * This resource provides information about the Jira instance.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientServerInfoConsumerApi {
    private final JiraClientServerInfoApi api;

    public JiraClientServerInfoConsumerApi(JiraClientServerInfoApi api) {
        this.api = api;
    }


    /**
     * Get2ServerInfoV1
     * Get Jira instance info
     * Returns information about the Jira instance.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** None.
     *
     * API Method: GET /rest/api/2/serverInfo
     *
     */
    public ServerInformation get2ServerInfoV1(Consumer<Get2ServerInfoV1OperationSpec> spec) {
        Get2ServerInfoV1OperationSpec r = new Get2ServerInfoV1OperationSpec(spec);
        return api.get2ServerInfoV1();
    }

}
