// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.client;

import io.github.primelib.jira4j.rest.v2.models.AnnouncementBannerConfiguration;
import io.github.primelib.jira4j.rest.v2.operations.Get2AnnouncementBannerV1OperationSpec;
import io.github.primelib.jira4j.rest.v2.operations.Put2AnnouncementBannerV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * JiraClientAnnouncementBannerConsumerApi
 *
 * This resource represents an announcement banner. Use it to retrieve and update banner configuration.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraClientAnnouncementBannerConsumerApi {
    private final JiraClientAnnouncementBannerApi api;

    public JiraClientAnnouncementBannerConsumerApi(JiraClientAnnouncementBannerApi api) {
        this.api = api;
    }


    /**
     * Get2AnnouncementBannerV1
     * Get announcement banner configuration
     * Returns the current announcement banner configuration.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: GET /rest/api/2/announcementBanner
     *
     */
    public AnnouncementBannerConfiguration get2AnnouncementBannerV1(Consumer<Get2AnnouncementBannerV1OperationSpec> spec) {
        Get2AnnouncementBannerV1OperationSpec r = new Get2AnnouncementBannerV1OperationSpec(spec);
        return api.get2AnnouncementBannerV1();
    }

    /**
     * Put2AnnouncementBannerV1
     * Update announcement banner configuration
     * Updates the announcement banner configuration.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/announcementBanner
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
     */
    public void put2AnnouncementBannerV1(Consumer<Put2AnnouncementBannerV1OperationSpec> spec) {
        Put2AnnouncementBannerV1OperationSpec r = new Put2AnnouncementBannerV1OperationSpec(spec);
        api.put2AnnouncementBannerV1(r.payload());
    }

}
