// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Delete2MypreferencesV1
 * <p>
 * Deletes a preference of the user, which restores the default value of system defined settings.
 * 
 * Note that these keys are deprecated:
 * 
 *  *  *jira.user.locale* The locale of the user. By default, not set. The user takes the instance locale.
 *  *  *jira.user.timezone* The time zone of the user. By default, not set. The user takes the instance timezone.
 * 
 * Use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API to manage timezone and locale instead.
 * 
 * **[Permissions](#permissions) required:** Permission to access Jira.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Delete2MypreferencesV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the preference.
     *
     */
    @NonNull
    private String key;

    /**
     * Constructs a validated instance of {@link Delete2MypreferencesV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Delete2MypreferencesV1OperationSpec(Consumer<Delete2MypreferencesV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(key, "key is a required parameter!");
    }
}
