// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * DeleteAtlassianConnect1AppModuleDynamicV1
 * <p>
 * Remove all or a list of modules registered by the calling app.
 * 
 * **[Permissions](#permissions) required:** Only Connect apps can make this request.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class DeleteAtlassianConnect1AppModuleDynamicV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the module to remove. To include multiple module keys, provide multiple copies of this parameter.
     * For example, `moduleKey=dynamic-attachment-entity-property&amp;moduleKey=dynamic-select-field`.
     * Nonexistent keys are ignored.
     *
     */
    @Nullable
    private List<String> moduleKey;

    /**
     * Constructs a validated instance of {@link DeleteAtlassianConnect1AppModuleDynamicV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public DeleteAtlassianConnect1AppModuleDynamicV1OperationSpec(Consumer<DeleteAtlassianConnect1AppModuleDynamicV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
