// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2IssuePickerV1
 * <p>
 * Returns lists of issues matching a query string. Use this resource to provide auto-completion suggestions when the user is looking for an issue using a word or string.
 * 
 * This operation returns two lists:
 * 
 *  *  `History Search` which includes issues from the user's history of created, edited, or viewed issues that contain the string in the `query` parameter.
 *  *  `Current Search` which includes issues that match the JQL expression in `currentJQL` and contain the string in the `query` parameter.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:** None.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2IssuePickerV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * A string to match against text fields in the issue such as title, description, or comments.
     *
     */
    @Nullable
    private String query;

    /**
     * A JQL query defining a list of issues to search for the query term. Note that `username` and `userkey` cannot be used as search terms for this parameter, due to privacy reasons. Use `accountId` instead.
     *
     */
    @Nullable
    private String currentJql;

    /**
     * The key of an issue to exclude from search results. For example, the issue the user is viewing when they perform this query.
     *
     */
    @Nullable
    private String currentIssueKey;

    /**
     * The ID of a project that suggested issues must belong to.
     *
     */
    @Nullable
    private String currentProjectId;

    /**
     * Indicate whether to include subtasks in the suggestions list.
     *
     */
    @Nullable
    private Boolean showSubTasks;

    /**
     * When `currentIssueKey` is a subtask, whether to include the parent issue in the suggestions if it matches the query.
     *
     */
    @Nullable
    private Boolean showSubTaskParent;

    /**
     * Constructs a validated instance of {@link Get2IssuePickerV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2IssuePickerV1OperationSpec(Consumer<Get2IssuePickerV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
