// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2ProjectRecentV1
 * <p>
 * Returns a list of up to 20 projects recently viewed by the user that are still visible to the user.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:** Projects are returned only where the user has one of:
 * 
 *  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2ProjectRecentV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expanded options include:
     * 
     *  *  `description` Returns the project description.
     *  *  `projectKeys` Returns all project keys associated with a project.
     *  *  `lead` Returns information about the project lead.
     *  *  `issueTypes` Returns all issue types associated with the project.
     *  *  `url` Returns the URL associated with the project.
     *  *  `permissions` Returns the permissions associated with the project.
     *  *  `insight` EXPERIMENTAL. Returns the insight details of total issue count and last issue update time for the project.
     *  *  `*` Returns the project with all available expand options.
     *
     */
    @Nullable
    private String expand;

    /**
     * EXPERIMENTAL. A list of project properties to return for the project. This parameter accepts a comma-separated list. Invalid property names are ignored.
     *
     */
    @Nullable
    private List<String> properties;

    /**
     * Constructs a validated instance of {@link Get2ProjectRecentV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2ProjectRecentV1OperationSpec(Consumer<Get2ProjectRecentV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
