// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Get2UserAssignableMultiProjectSearchV1
 * <p>
 * Returns a list of users who can be assigned issues in one or more projects. The list may be restricted to users whose attributes match a string.
 * 
 * This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that can be assigned issues in the projects. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who can be assigned issues in the projects, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
 * 
 * Privacy controls are applied to the response based on the users' preferences. This could mean, for example, that the user's email address is hidden. See the [Profile visibility overview](https://developer.atlassian.com/cloud/jira/platform/profile-visibility/) for more details.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for each project specified in `projectKeys`.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2UserAssignableMultiProjectSearchV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * A query string that is matched against user attributes, such as `displayName` and `emailAddress`, to find relevant users. The string can match the prefix of the attribute's value. For example, *query=john* matches a user with a `displayName` of *John Smith* and a user with an `emailAddress` of *johnson@example.com*. Required, unless `accountId` is specified.
     *
     */
    @Nullable
    private String query;

    /**
     * This parameter is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
     *
     */
    @Nullable
    private String username;

    /**
     * A query string that is matched exactly against user `accountId`. Required, unless `query` is specified.
     *
     */
    @Nullable
    private String accountId;

    /**
     * A list of project keys (case sensitive). This parameter accepts a comma-separated list.
     *
     */
    @NonNull
    private String projectKeys;

    /**
     * The index of the first item to return in a page of results (page offset).
     *
     */
    @Nullable
    private Integer startAt;

    /**
     * The maximum number of items to return per page.
     *
     */
    @Nullable
    private Integer maxResults;

    /**
     * Constructs a validated instance of {@link Get2UserAssignableMultiProjectSearchV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2UserAssignableMultiProjectSearchV1OperationSpec(Consumer<Get2UserAssignableMultiProjectSearchV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(projectKeys, "projectKeys is a required parameter!");
    }
}
