// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2ProjectTemplateLiveTemplateV1
 * <p>
 * Get custom template
 * 
 * This API endpoint allows you to get a live custom project template details by either templateKey or projectId
 * 
 * ***Note: Custom Templates are only supported for Jira Enterprise edition.***
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2ProjectTemplateLiveTemplateV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * optional - The \{@link String\} containing the project key linked to the custom template to retrieve
     *
     */
    @Nullable
    private String projectId;

    /**
     * optional - The \{@link String\} containing the key of the custom template to retrieve
     *
     */
    @Nullable
    private String templateKey;

    /**
     * Constructs a validated instance of {@link Get2ProjectTemplateLiveTemplateV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2ProjectTemplateLiveTemplateV1OperationSpec(Consumer<Get2ProjectTemplateLiveTemplateV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
