// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2ScreenschemeV1
 * <p>
 * Returns a [paginated](#pagination) list of screen schemes.
 * 
 * Only screen schemes used in classic projects are returned.
 * 
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2ScreenschemeV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The index of the first item to return in a page of results (page offset).
     *
     */
    @Nullable
    private Long startAt;

    /**
     * The maximum number of items to return per page.
     *
     */
    @Nullable
    private Integer maxResults;

    /**
     * The list of screen scheme IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&amp;id=10001`.
     *
     */
    @Nullable
    private List<Long> id;

    /**
     * Use [expand](#expansion) include additional information in the response. This parameter accepts `issueTypeScreenSchemes` that, for each screen schemes, returns information about the issue type screen scheme the screen scheme is assigned to.
     *
     */
    @Nullable
    private String expand;

    /**
     * String used to perform a case-insensitive partial match with screen scheme name.
     *
     */
    @Nullable
    private String queryString;

    /**
     * [Order](#ordering) the results by a field:
     * 
     *  *  `id` Sorts by screen scheme ID.
     *  *  `name` Sorts by screen scheme name.
     *
     */
    @Nullable
    private String orderBy;

    /**
     * Constructs a validated instance of {@link Get2ScreenschemeV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2ScreenschemeV1OperationSpec(Consumer<Get2ScreenschemeV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
