// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1
 * <p>
 * Returns a permission grant.
 * 
 * **[Permissions](#permissions) required:** Permission to access Jira.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the permission scheme.
     *
     */
    @NonNull
    private Long schemeId;

    /**
     * The ID of the permission grant.
     *
     */
    @NonNull
    private Long permissionId;

    /**
     * Use expand to include additional information in the response. This parameter accepts a comma-separated list. Note that permissions are always included when you specify any value. Expand options include:
     * 
     *  *  `all` Returns all expandable information.
     *  *  `field` Returns information about the custom field granted the permission.
     *  *  `group` Returns information about the group that is granted the permission.
     *  *  `permissions` Returns all permission grants for each permission scheme.
     *  *  `projectRole` Returns information about the project role granted the permission.
     *  *  `user` Returns information about the user who is granted the permission.
     *
     */
    @Nullable
    private String expand;

    /**
     * Constructs a validated instance of {@link Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec(Consumer<Get2PermissionschemeBySchemeIDPermissionByPermissionIDV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(schemeId, "schemeId is a required parameter!");
        Objects.requireNonNull(permissionId, "permissionId is a required parameter!");
    }
}
