// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.WorkflowCreateValIDAteRequest;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Post2WorkflowsCreateValIDAtionV1
 * <p>
 * Validate the payload for bulk create workflows.
 * 
 * **[Permissions](#permissions) required:**
 * 
 *  *  *Administer Jira* project permission to create all, including global-scoped, workflows
 *  *  *Administer projects* project permissions to create project-scoped workflows
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Post2WorkflowsCreateValIDAtionV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * payload
     *
     */
    @NonNull
    private WorkflowCreateValIDAteRequest payload;

    /**
     * Constructs a validated instance of {@link Post2WorkflowsCreateValIDAtionV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Post2WorkflowsCreateValIDAtionV1OperationSpec(Consumer<Post2WorkflowsCreateValIDAtionV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
