// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.BulkFetchIssueRequestBean;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Post2IssueBulkfetchV1
 * <p>
 * Returns the details for a set of requested issues. You can request up to 100 issues.
 * 
 * Each issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned.
 * 
 * Issues will be returned in ascending `id` order. If there are errors, Jira will return a list of issues which couldn't be fetched along with error messages.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:** Issues are included in the response where the user has:
 * 
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Post2IssueBulkfetchV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * A JSON object containing the information about which issues and fields to fetch.
     *
     */
    @NonNull
    private BulkFetchIssueRequestBean payload;

    /**
     * Constructs a validated instance of {@link Post2IssueBulkfetchV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Post2IssueBulkfetchV1OperationSpec(Consumer<Post2IssueBulkfetchV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
