// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Post2IssuetypeByIDAvatar2V1
 * <p>
 * Loads an avatar for the issue type.
 * 
 * Specify the avatar's local file location in the body of the request. Also, include the following headers:
 * 
 *  *  `X-Atlassian-Token: no-check` To prevent XSRF protection blocking the request, for more information see [Special Headers](#special-request-headers).
 *  *  `Content-Type: image/image type` Valid image types are JPEG, GIF, or PNG.
 * 
 * For example:  
 * `curl --request POST \ --user email@example.com:&lt;api_token&gt; \ --header 'X-Atlassian-Token: no-check' \ --header 'Content-Type: image/&lt; image_type&gt;' \ --data-binary "&lt;@/path/to/file/with/your/avatar&gt;" \ --url 'https://your-domain.atlassian.net/rest/api/2/issuetype/{issueTypeId}'This`
 * 
 * The avatar is cropped to a square. If no crop parameters are specified, the square originates at the top left of the image. The length of the square's sides is set to the smaller of the height or width of the image.
 * 
 * The cropped image is then used to create avatars of 16x16, 24x24, 32x32, and 48x48 in size.
 * 
 * After creating the avatar, use [ Update issue type](#api-rest-api-2-issuetype-id-put) to set it as the issue type's displayed avatar.
 * 
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Post2IssuetypeByIDAvatar2V1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the issue type.
     *
     */
    @NonNull
    private String id;

    /**
     * The X coordinate of the top-left corner of the crop region.
     *
     */
    @Nullable
    private Integer x;

    /**
     * The Y coordinate of the top-left corner of the crop region.
     *
     */
    @Nullable
    private Integer y;

    /**
     * The length of each side of the crop region.
     *
     */
    @NonNull
    private Integer size;

    /**
     * payload
     *
     */
    @NonNull
    private Object payload;

    /**
     * Constructs a validated instance of {@link Post2IssuetypeByIDAvatar2V1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Post2IssuetypeByIDAvatar2V1OperationSpec(Consumer<Post2IssuetypeByIDAvatar2V1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(id, "id is a required parameter!");
        Objects.requireNonNull(size, "size is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
