// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.WorkflowReadRequest;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Post2WorkflowsV1
 * <p>
 * Returns a list of workflows and related statuses by providing workflow names, workflow IDs, or project and issue types.
 * 
 * **[Permissions](#permissions) required:**
 * 
 *  *  *Administer Jira* global permission to access all, including project-scoped, workflows
 *  *  At least one of the *Administer projects* and *View (read-only) workflow* project permissions to access project-scoped workflows
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Post2WorkflowsV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * Return the new field `approvalConfiguration` instead of the deprecated status properties for approval configuration.
     *
     */
    @Nullable
    private Boolean useApprovalConfiguration;

    /**
     * payload
     *
     */
    @NonNull
    private WorkflowReadRequest payload;

    /**
     * Constructs a validated instance of {@link Post2WorkflowsV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Post2WorkflowsV1OperationSpec(Consumer<Post2WorkflowsV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
