// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.ScreenableTab;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Put2ScreenByScreenIDTabByTabIDV1
 * <p>
 * Updates the name of a screen tab.
 * 
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Put2ScreenByScreenIDTabByTabIDV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the screen.
     *
     */
    @NonNull
    private Long screenId;

    /**
     * The ID of the screen tab.
     *
     */
    @NonNull
    private Long tabId;

    /**
     * payload
     *
     */
    @NonNull
    private ScreenableTab payload;

    /**
     * Constructs a validated instance of {@link Put2ScreenByScreenIDTabByTabIDV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Put2ScreenByScreenIDTabByTabIDV1OperationSpec(Consumer<Put2ScreenByScreenIDTabByTabIDV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(screenId, "screenId is a required parameter!");
        Objects.requireNonNull(tabId, "tabId is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
