// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Put2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1
 * <p>
 * Updates any of the following planning settings of an Atlassian team in a plan using [JSON Patch](https://datatracker.ietf.org/doc/html/rfc6902).
 * 
 *  *  planningStyle
 *  *  issueSourceId
 *  *  sprintLength
 *  *  capacity
 * 
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 * 
 * *Note that "add" operations do not respect array indexes in target locations. Call the "Get Atlassian team in plan" endpoint to find out the order of array elements.*
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Put2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the plan.
     *
     */
    @NonNull
    private Long planId;

    /**
     * The ID of the Atlassian team.
     *
     */
    @NonNull
    private String atlassianTeamId;

    /**
     * payload
     *
     */
    @NonNull
    private Object payload;

    /**
     * Constructs a validated instance of {@link Put2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Put2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1OperationSpec(Consumer<Put2PlansPlanByPlanIDTeamAtlassianByAtlassianTeamIDV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(planId, "planId is a required parameter!");
        Objects.requireNonNull(atlassianTeamId, "atlassianTeamId is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
