// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.IssueArchivalSyncRequest;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Put2IssueUnarchiveV1
 * <p>
 * Enables admins to unarchive up to 1000 issues in a single request using issue ID/key, returning details of the issue(s) unarchived in the process and the errors encountered, if any.
 * 
 * **Note that:**
 * 
 *  *  you can't unarchive subtasks directly, only through their parent issues
 *  *  you can only unarchive issues from software, service management, and business projects
 * 
 * **[Permissions](#permissions) required:** Jira admin or site admin: [global permission](https://confluence.atlassian.com/x/x4dKLg)
 * 
 * **License required:** Premium or Enterprise
 * 
 * **Signed-in users only:** This API can't be accessed anonymously.
 * 
 *   
 * 
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Put2IssueUnarchiveV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * Contains a list of issue keys or IDs to be unarchived.
     *
     */
    @NonNull
    private IssueArchivalSyncRequest payload;

    /**
     * Constructs a validated instance of {@link Put2IssueUnarchiveV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Put2IssueUnarchiveV1OperationSpec(Consumer<Put2IssueUnarchiveV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
