// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.ConnectCustomFieldValues;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * PutAtlassianConnect1MigrationFieldV1
 * <p>
 * Updates the value of a custom field added by Connect apps on one or more issues.
 * The values of up to 200 custom fields can be updated.
 * 
 * **[Permissions](#permissions) required:** Only Connect apps can make this request
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class PutAtlassianConnect1MigrationFieldV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the transfer.
     *
     */
    @NonNull
    private String atlassianTransferId;

    /**
     * payload
     *
     */
    @NonNull
    private ConnectCustomFieldValues payload;

    /**
     * Constructs a validated instance of {@link PutAtlassianConnect1MigrationFieldV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public PutAtlassianConnect1MigrationFieldV1OperationSpec(Consumer<PutAtlassianConnect1MigrationFieldV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(atlassianTransferId, "atlassianTransferId is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
