// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * NumberTypeEnum
 *
 */
@JsonTypeName("NumberTypeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum NumberTypeEnum {
    BIG_DECIMAL("BIG_DECIMAL"),
    BIG_INTEGER("BIG_INTEGER"),
    DOUBLE("DOUBLE"),
    FLOAT("FLOAT"),
    INT("INT"),
    LONG("LONG"),
    ;

    private final String value;

    NumberTypeEnum(String value) {
        this.value = value;
    }
}
