// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * SecurityLevelPayload
 * <p>
 * The payload for creating a security level. See https://support.atlassian.com/jira-cloud-administration/docs/configure-issue-security-schemes/
 *
 */
@JsonTypeName("SecurityLevelPayload")
@JsonPropertyOrder({
    "description",
    "isDefault",
    "name",
    "securityLevelMembers"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SecurityLevelPayload {

    /**
     * The description of the security level
     */
    @JsonProperty("description")
    protected String description;

    /**
     * Whether the security level is default for the security scheme
     */
    @JsonProperty("isDefault")
    protected Boolean isDefault;

    /**
     * The name of the security level
     */
    @JsonProperty("name")
    protected String name;

    /**
     * The members of the security level
     */
    @JsonProperty("securityLevelMembers")
    protected List<SecurityLevelMemberPayload> securityLevelMembers;

    /**
     * Constructs a validated instance of {@link SecurityLevelPayload}.
     *
     * @param spec the specification to process
     */
    public SecurityLevelPayload(Consumer<SecurityLevelPayload> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected SecurityLevelPayload() {
    }

    /**
     * Constructs a validated instance of {@link SecurityLevelPayload}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SecurityLevelPayload(Consumer)} instead.
     * @param description The description of the security level
     * @param isDefault Whether the security level is default for the security scheme
     * @param name The name of the security level
     * @param securityLevelMembers The members of the security level
     */
    @ApiStatus.Internal
    public SecurityLevelPayload(String description, Boolean isDefault, String name, List<SecurityLevelMemberPayload> securityLevelMembers) {
        this.description = description;
        this.isDefault = isDefault;
        this.name = name;
        this.securityLevelMembers = securityLevelMembers;
    }


    /**
     * Fluent getter for description.
     * <p>
     * The description of the security level
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the security level
     *
     * @param description description
     * @return this
     */
    public SecurityLevelPayload description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the security level
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the security level
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for isDefault.
     * <p>
     * Whether the security level is default for the security scheme
     *
     * @return isDefault
     */
    public Boolean isDefault() {
        return this.isDefault;
    }

    /**
     * Fluent setter for isDefault.
     * <p>
     * Whether the security level is default for the security scheme
     *
     * @param isDefault isDefault
     * @return this
     */
    public SecurityLevelPayload isDefault(Boolean isDefault) {
        this.isDefault = isDefault;
        return this;
    }

    /**
     * Gets the value of isDefault.
     * <p>
     * Whether the security level is default for the security scheme
     *
     * @return isDefault
     */
    @JsonProperty("isDefault")
    public Boolean getIsDefault() {
        return this.isDefault;
    }

    /**
     * Sets the value of isDefault.
     * <p>
     * Whether the security level is default for the security scheme
     *
     * @param isDefault isDefault
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The name of the security level
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the security level
     *
     * @param name name
     * @return this
     */
    public SecurityLevelPayload name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the security level
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the security level
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for securityLevelMembers.
     * <p>
     * The members of the security level
     *
     * @return securityLevelMembers
     */
    public List<SecurityLevelMemberPayload> securityLevelMembers() {
        return this.securityLevelMembers;
    }

    /**
     * Fluent setter for securityLevelMembers.
     * <p>
     * The members of the security level
     *
     * @param securityLevelMembers securityLevelMembers
     * @return this
     */
    public SecurityLevelPayload securityLevelMembers(List<SecurityLevelMemberPayload> securityLevelMembers) {
        this.securityLevelMembers = securityLevelMembers;
        return this;
    }

    /**
     * Gets the value of securityLevelMembers.
     * <p>
     * The members of the security level
     *
     * @return securityLevelMembers
     */
    @JsonProperty("securityLevelMembers")
    public List<SecurityLevelMemberPayload> getSecurityLevelMembers() {
        return this.securityLevelMembers;
    }

    /**
     * Sets the value of securityLevelMembers.
     * <p>
     * The members of the security level
     *
     * @param securityLevelMembers securityLevelMembers
     */
    public void setSecurityLevelMembers(List<SecurityLevelMemberPayload> securityLevelMembers) {
        this.securityLevelMembers = securityLevelMembers;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SecurityLevelPayload that = (SecurityLevelPayload) o;
        return
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.isDefault, that.isDefault) &&
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.securityLevelMembers, that.securityLevelMembers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.description, 
            this.isDefault, 
            this.name, 
            this.securityLevelMembers
        );
    }

    @Override
    public String toString() {
        return "SecurityLevelPayload{" +
            "description=" + description + ", " + 
            "isDefault=" + isDefault + ", " + 
            "name=" + name + ", " + 
            "securityLevelMembers=" + securityLevelMembers +
            "}";
    }
}
