// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Delete2ProjectTemplateRemoveTemplateV1
 * <p>
 * Remove custom template
 * 
 * This API endpoint allows you to remove a specified customised template
 * 
 * ***Note: Custom Templates are only supported for Jira Enterprise edition.***
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Delete2ProjectTemplateRemoveTemplateV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The \{@link String\} containing the key of the custom template to remove
     *
     */
    @NonNull
    private String templateKey;

    /**
     * Constructs a validated instance of {@link Delete2ProjectTemplateRemoveTemplateV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Delete2ProjectTemplateRemoveTemplateV1OperationSpec(Consumer<Delete2ProjectTemplateRemoveTemplateV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(templateKey, "templateKey is a required parameter!");
    }
}
