// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2UiModificationsV1
 * <p>
 * Gets UI modifications. UI modifications can only be retrieved by Forge apps.
 * 
 * **[Permissions](#permissions) required:** None.
 * 
 * The new `read:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2UiModificationsV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The index of the first item to return in a page of results (page offset).
     *
     */
    @Nullable
    private Long startAt;

    /**
     * The maximum number of items to return per page.
     *
     */
    @Nullable
    private Integer maxResults;

    /**
     * Use expand to include additional information in the response. This parameter accepts a comma-separated list. Expand options include:
     * 
     *  *  `data` Returns UI modification data.
     *  *  `contexts` Returns UI modification contexts.
     *
     */
    @Nullable
    private String expand;

    /**
     * Constructs a validated instance of {@link Get2UiModificationsV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2UiModificationsV1OperationSpec(Consumer<Get2UiModificationsV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
