// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Get2ProjectTypeByProjectTypeKeyAccessibleV1
 * <p>
 * Returns a [project type](https://confluence.atlassian.com/x/Var1Nw) if it is accessible to the user.
 * 
 * **[Permissions](#permissions) required:** Permission to access Jira.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2ProjectTypeByProjectTypeKeyAccessibleV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the project type.
     *
     */
    @NonNull
    private String projectTypeKey;

    /**
     * Constructs a validated instance of {@link Get2ProjectTypeByProjectTypeKeyAccessibleV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2ProjectTypeByProjectTypeKeyAccessibleV1OperationSpec(Consumer<Get2ProjectTypeByProjectTypeKeyAccessibleV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(projectTypeKey, "projectTypeKey is a required parameter!");
    }
}
