// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2ScreensTabsV1
 * <p>
 * Returns the list of tabs for a bulk of screens.
 * 
 * **[Permissions](#permissions) required:**
 * 
 *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2ScreensTabsV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The list of screen IDs. To include multiple screen IDs, provide an ampersand-separated list. For example, `screenId=10000&amp;screenId=10001`.
     *
     */
    @Nullable
    private List<Long> screenId;

    /**
     * The list of tab IDs. To include multiple tab IDs, provide an ampersand-separated list. For example, `tabId=10000&amp;tabId=10001`.
     *
     */
    @Nullable
    private List<Long> tabId;

    /**
     * The index of the first item to return in a page of results (page offset).
     *
     */
    @Nullable
    private Long startAt;

    /**
     * The maximum number of items to return per page. The maximum number is 100,
     *
     */
    @Nullable
    private Integer maxResult;

    /**
     * Constructs a validated instance of {@link Get2ScreensTabsV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2ScreensTabsV1OperationSpec(Consumer<Get2ScreensTabsV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
