// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2GroupV1
 * <p>
 * This operation is deprecated, use [`group/member`](#api-rest-api-2-group-member-get).
 * 
 * Returns all users in a group.
 * 
 * **[Permissions](#permissions) required:** either of:
 * 
 *  *  *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @deprecated
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Deprecated
@Generated(value = "io.github.primelib.primecodegen")
public class Get2GroupV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * As a group's name can change, use of `groupId` is recommended to identify a group.  
     * The name of the group. This parameter cannot be used with the `groupId` parameter.
     *
     */
    @Nullable
    private String groupname;

    /**
     * The ID of the group. This parameter cannot be used with the `groupName` parameter.
     *
     */
    @Nullable
    private String groupId;

    /**
     * List of fields to expand.
     *
     */
    @Nullable
    private String expand;

    /**
     * Constructs a validated instance of {@link Get2GroupV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2GroupV1OperationSpec(Consumer<Get2GroupV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
