// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2FieldconfigurationV1
 * <p>
 * Returns a [paginated](#pagination) list of field configurations. The list can be for all field configurations or a subset determined by any combination of these criteria:
 * 
 *  *  a list of field configuration item IDs.
 *  *  whether the field configuration is a default.
 *  *  whether the field configuration name or description contains a query string.
 * 
 * Only field configurations used in company-managed (classic) projects are returned.
 * 
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2FieldconfigurationV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The index of the first item to return in a page of results (page offset).
     *
     */
    @Nullable
    private Long startAt;

    /**
     * The maximum number of items to return per page.
     *
     */
    @Nullable
    private Integer maxResults;

    /**
     * The list of field configuration IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&amp;id=10001`.
     *
     */
    @Nullable
    private List<Long> id;

    /**
     * If *true* returns default field configurations only.
     *
     */
    @Nullable
    private Boolean isDefault;

    /**
     * The query string used to match against field configuration names and descriptions.
     *
     */
    @Nullable
    private String query;

    /**
     * Constructs a validated instance of {@link Get2FieldconfigurationV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2FieldconfigurationV1OperationSpec(Consumer<Get2FieldconfigurationV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
