// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * Get2JqlAutocompletedataSuggestionsV1
 * <p>
 * Returns the JQL search auto complete suggestions for a field.
 * 
 * Suggestions can be obtained by providing:
 * 
 *  *  `fieldName` to get a list of all values for the field.
 *  *  `fieldName` and `fieldValue` to get a list of values containing the text in `fieldValue`.
 *  *  `fieldName` and `predicateName` to get a list of all predicate values for the field.
 *  *  `fieldName`, `predicateName`, and `predicateValue` to get a list of predicate values containing the text in `predicateValue`.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:** None.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2JqlAutocompletedataSuggestionsV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The name of the field.
     *
     */
    @Nullable
    private String fieldName;

    /**
     * The partial field item name entered by the user.
     *
     */
    @Nullable
    private String fieldValue;

    /**
     * The name of the [ CHANGED operator predicate](https://confluence.atlassian.com/x/hQORLQ#Advancedsearching-operatorsreference-CHANGEDCHANGED) for which the suggestions are generated. The valid predicate operators are *by*, *from*, and *to*.
     *
     */
    @Nullable
    private String predicateName;

    /**
     * The partial predicate item name entered by the user.
     *
     */
    @Nullable
    private String predicateValue;

    /**
     * Constructs a validated instance of {@link Get2JqlAutocompletedataSuggestionsV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2JqlAutocompletedataSuggestionsV1OperationSpec(Consumer<Get2JqlAutocompletedataSuggestionsV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
