// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.JqlQueriesToParse;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Post2JqlParseV1
 * <p>
 * Parses and validates JQL queries.
 * 
 * Validation is performed in context of the current user.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:** None.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Post2JqlParseV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * How to validate the JQL query and treat the validation results. Validation options include:
     * 
     *  *  `strict` Returns all errors. If validation fails, the query structure is not returned.
     *  *  `warn` Returns all errors. If validation fails but the JQL query is correctly formed, the query structure is returned.
     *  *  `none` No validation is performed. If JQL query is correctly formed, the query structure is returned.
     *
     */
    @NonNull
    private String validation;

    /**
     * payload
     *
     */
    @NonNull
    private JqlQueriesToParse payload;

    /**
     * Constructs a validated instance of {@link Post2JqlParseV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Post2JqlParseV1OperationSpec(Consumer<Post2JqlParseV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(validation, "validation is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
