// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.DashboardDetails;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Put2DashboardByIDV1
 * <p>
 * Updates a dashboard, replacing all the dashboard details with those provided.
 * 
 * **[Permissions](#permissions) required:** None
 * 
 * The dashboard to be updated must be owned by the user.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Put2DashboardByIDV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the dashboard to update.
     *
     */
    @NonNull
    private String id;

    /**
     * Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
     *
     */
    @Nullable
    private Boolean extendAdminPermissions;

    /**
     * Replacement dashboard details.
     *
     */
    @NonNull
    private DashboardDetails payload;

    /**
     * Constructs a validated instance of {@link Put2DashboardByIDV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Put2DashboardByIDV1OperationSpec(Consumer<Put2DashboardByIDV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(id, "id is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
