// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira4j.rest.v2.operations;

import io.github.primelib.jira4j.rest.v2.models.User;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * Put2IssueByIssueIDOrKeyAssigneeV1
 * <p>
 * Assigns an issue to a user. Use this operation when the calling user does not have the *Edit Issues* permission but has the *Assign issue* permission for the project that the issue is in.
 * 
 * If `name` or `accountId` is set to:
 * 
 *  *  `"-1"`, the issue is assigned to the default assignee for the project.
 *  *  `null`, the issue is set to unassigned.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:**
 * 
 *  *  *Browse Projects* and *Assign Issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID or key of the issue to be assigned.
     *
     */
    @NonNull
    private String issueIdOrKey;

    /**
     * The request object with the user that the issue is assigned to.
     *
     */
    @NonNull
    private User payload;

    /**
     * Constructs a validated instance of {@link Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec(Consumer<Put2IssueByIssueIDOrKeyAssigneeV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(issueIdOrKey, "issueIdOrKey is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
